### PR TITLE
A: https://www.123movies2022.org/

### PR DESCRIPTION
**Pull request by felippesantos46**
Block adserver and popups at https://www.123movies2022.org/

Screenshots:
Screenshot 2021-12-31 at 11 04 57
Screenshot 2021-12-31 at 11 02 43
Screenshot 2021-12-31 at 11 07 24

### CODE REVIEW

**Comment by ryanbr** [comment]
@felippesantos46  rebase plz

**Comment by felippesantos46** [comment]
Hey @ryanbr Done !

**Comment by spirillen** [comment]
@felippesantos46 there are still conflict, try again, there might have been a merge that makes a new conflict

**Comment by felippesantos46** [comment]
@spirillen I've also rebased wrongly before, so my bad 😅. 
@ryanbr I believe now we are good to go !

**Pull request merged**
