### PR TITLE
A: etsy.com - Hide cookie dialog

### PR DESCRIPTION
**Pull request by Nojuuu**
`https://www.etsy.com/`

Fixed https://github.com/easylist/easylist/pull/9536. 

The problem was that the page "shrank" slightly each time you expanded the preview image.

### CODE REVIEW

**Comment by peace2000** [comment]
@Nojuuu 

EL Cookie's uBO list currently has this rule:
`etsy.com##body,html:style(overflow: auto !important; position: initial !important;)`

If I add this to my custom filters:
`etsy.com###gdpr-single-choice-overlay`

I see no issues at all. Images and even videos seem to work without an issue. https://www.etsy.com/fi-en/listing/751174027/55140-cm-wide-light-grey-linen-curtain?sts=1

Do you know this site better? Can you confirm?

**Comment by peace2000** [comment]
Hmm... it seems to be possible to prevent the shifting of the body element via:

`etsy.com##body:style(padding-right: 0 !important)`

**Comment by Nojuuu** [comment]
Not sure, closed this while back since it didn't seem to get merged and there started to be a lot of changes to the file so I would have had kept rebasing it.

**Comment by peace2000** [comment]
https://github.com/easylist/easylist/pull/12776

Added a fix and it was merged.

**Pull request closed without merging**
