### PR TITLE
A: foreca.com (generic survey block, annoyance)

### PR DESCRIPTION
**Pull request by peace2000**
Referring to this message: https://github.com/easylist/easylist/issues/12507#issuecomment-1179505506

EP should not block a survey (it's fixed in EP now), but Annoyance list should block it. Blocking the survey this way won't cause issues.

### CODE REVIEW

**Comment by ryanbr** [comment]
`fanboy-addon/fanboy_annoyance_thirdparty.txt:||confirmit.com^$third-party`  ?

**Comment by peace2000** [comment]
I guess that would be better.

confirmit.com is indeed in wide usage: https://publicwww.com/websites/%22confirmit.com%22/

**Comment by ryanbr** [comment]
Or maybe move it too notifications third-party?

**Comment by peace2000** [comment]
Edited my PR.

**Comment by ryanbr** [comment]
remove it from one list/txt file, move it to the other..

**Comment by peace2000** [comment]
I moved it to fanboy_notifications_thirdparty.txt, isn't that the correct one?

**Comment by peace2000** [comment]
kuva

?

**Pull request closed without merging**
