### PR TITLE
A: https://new.qq.com/newsvideo.htm#/cover/mzc002008ssw79b/j3307cbquqh

### PR DESCRIPTION
**Pull request by shenzhiming88**
Probably trackers.
image

### CODE REVIEW

**Comment by spirillen** [comment]
I have listed it as tracker, so have adaway

`https://github.com/AdAway/adaway.github.io/pull/262/files`

**Comment by shenzhiming88** [comment]
@ryanbr

**Comment by shenzhiming88** [comment]
> I have listed it as tracker, so have adaway
> 
> `https://github.com/AdAway/adaway.github.io/pull/262/files`

Wow, how did you collect so many (all Tencent-related, it seems) domain names.

**Comment by spirillen** [comment]
> > I have listed it as tracker, so have adaway
> > `https://github.com/AdAway/adaway.github.io/pull/262/files`
> 
> Wow, how did you collect so many (all Tencent-related, it seems) domain names.

you'll have to ask jawz101 about that :wave:

**Pull request merged**
