### PR TITLE
P: ivoox.com (podcasts / videos won't work (multiple domains)

### PR DESCRIPTION
**Pull request by peace2000**
Blocking the whole domain of `privacy-center.org` causes issues. https://github.com/uBlockOrigin/uAssets/issues/7644 & https://github.com/easylist/easylist/issues/6049 in order to block the gdpr prompt, the blocking of the script is enough. The whole domain doesn't need to be blocked.

Sample domains for the script usage (the script has different language variants, I used a wild card to cover all of them):
https://www.ibtimes.com/
https://www.lavozdegalicia.es/
https://www.filmweb.pl/
https://meteofrance.com/
https://en.softonic.com/

Edit. I removed a separate whitelist rule which contains some domains in which videos do work if this script is blocked but the domain is not touched.

Test links:
https://www.mundodeportivo.com/ciclismo/vuelta-espana/20201029/4969946822/sam-bennett-gana-el-sprint-en-aguilar-de-campoo-de-la-vuelta-por-pura-potencia.html
https://www.lavanguardia.com/internacional/20201029/4966493765/acuchillado-niza-francia-iglesia.html
https://www.ivoox.com/hititas-por-dioses-lbp-audios-mp3_rf_48708708_1.html

These domains do need whitelisting even for the script:
https://www.allocine.fr/article/fichearticle_gen_carticle=18697876.html
https://www.funradio.fr/news/le-vacher-time-du-29-octobre-2020-7800913647
https://www.gamestar.de/videos/star-wars-squadrons-test-video-zur-weltraum-action,101425.html
https://www.nieuwsblad.be/cnt/dmf20201029_95025354
https://www.rtl.fr/actu/politique/coronavirus-macron-entre-precautions-justifications-et-avertissements-7800912637
https://www.standaard.be/cnt/dmf20201029_94687662
https://www.telegraaf.nl/video/1733224436/aanslag-nice-kwade-individuen-grootste-terreurdreiging

### CODE REVIEW

**Review by krystian3w — APPROVED** [review]

**Review by krystian3w — APPROVED** [review]

**Review by krystian3w — APPROVED** [review]

**Comment by peace2000** [comment]
Too complicated, also hard to handle things as pull req's age and other stuff is getting added to lists...

**Comment by krystian3w** [comment]
OK.

**Pull request closed without merging**
