### PR TITLE
A: (nsfw) dailyporn.club (fixes https://github.com/AdguardTeam/Adguar…

### PR DESCRIPTION
**Pull request by Yuki2718**
…dFilters/issues/101974)
https://github.com/AdguardTeam/AdguardFilters/issues/101974

### CODE REVIEW

**Review by spirillen — COMMENTED** [review]
You missed one on the right side of the player.

Without deeper inspection it could makes me think it is some tracking image as it can't be blocked by a direct rule but the following rule seems to handler it

```css
dailyporn.club##.right
```

!NOT WORKING:
```css
||dailyporn.club/img/prism.png
```

**Comment by Yuki2718** [comment]
`/prism.png` is not a tracking pixel and adding `##.right` doesn't change anything on my end. But there are some unblocked ads.

**Comment by spirillen** [comment]
>  adding `##.right` doesn't change anything on my end

It's true that there currently is no visual changes with `##.right` today but what about tomorrow? that's why I mentioned it.

> But there are some unblocked ads.

Yeps, just got there, I didn't see them yesterday.

This one removed the one in the bottom

```css
dailyporn.club###fixedban
```

This one takes the top banner

```css
||hyperlnk.xyz^$script
```

This one removes the lower right popup

```css
||dailyporn.club/nba/frntndlodr12.js$script
```

**Comment by spirillen** [comment]
After reviewing  `hyperlnk.xyz` you might better try 
```css
||https://hyperlnk.xyz/?y9zZXh1aG90LmNvbS$script
```

**Pull request merged**
