### PR TITLE
A: http://www.psx-place.com/forums/

### PR DESCRIPTION
**Pull request by smed79**
```
http://www.psx-place.com/js/ipbforo/js/jquery.totop.js
http://www.psx-place.com/js/ipbforo/js/jquery.min.totop.js
```

### CODE REVIEW

**Comment by peace2000** [comment]
Still relevant, `/jquery.totop.` is being used on many webpages: https://publicwww.com/websites/%22%2Fjquery.totop.min.js%22/

**Comment by peace2000** [comment]
Still relevant, `/jquery.totop.` is being used on many webpages: https://publicwww.com/websites/%22%2Fjquery.totop.%22/ so a general block rule is justifiable.

**Comment by Khrin** [comment]
A similar filter was removed due to excessive false positives and honestly I believe such generic filter could have the same behaviour.

**Comment by peace2000** [comment]
Oh ok. But site specific filter for this site would do?

**Comment by Khrin** [comment]
I'm not sure if it's worth the effort.

**Pull request closed without merging**
