### PR TITLE
A: https://tieba.baidu.com/f?ie=utf-8&kw=Test

### PR DESCRIPTION
**Pull request by DeepChirp**
Please see - `http://sofire.bdstatic.com/push/privacy.html`

> Baidu Huitui is a technology service platform that provides mobile application message push service for mobile application developers ("Developers"). After integrating the Baidu Huitui Software Development Kit (SDK) ("Huitui SDK") into their mobile applications, developers can push messages to the end users of their mobile applications ("end users") through the Baidu Huitui platform. When the Developer integrates the Huitui SDK with its mobile application and uses the Baidu Huitui service, the Developer entrusts Baidu Huitui to process data and information related to the Developer's mobile application, which may include the personal information of the End Users of the Developer's mobile application ("End Users"). This Privacy Policy is intended to help developers and end users understand the types of personal information we collect from end users and how we use and protect end users' personal information. For ease of reading and understanding by Developers and End Users, we have defined specific terms, please see "Appendix 1: Definitions" of this Privacy Policy for details of these definitions.

According to the official website, this domain is used to collect users' private information.

image

### CODE REVIEW

**Comment by spirillen** [comment]
Thanks for this one :smiley:

**Comment by shenzhiming88** [comment]
> Thanks for this one 😃

Uh, but why did you add `tieba.baidu.com` instead of `sofire.bdstatic.com`?

**Comment by spirillen** [comment]
> > Thanks for this one smiley
> 
> Uh, but why did you add `tieba.baidu.com` instead of `sofire.bdstatic.com`?

Good thanks for that question. I mistakenly taken the title not the problem, will be fixed ASAP

**Comment by Yuki2718** [comment]
`bdstatic.com` is always third-party, so third-party flag is not needed.

**Pull request closed without merging**
