### PR TITLE
A: (nsfw) danbooru.donmai.us

### PR DESCRIPTION
**Pull request by Yuki2718**

### CODE REVIEW

**Comment by deusexcalamus** [comment]
Blocking isshiki.donmai.us causes issues with functionality on the site (danbooru.donmai.us) by preventing people from seeing the number of views a post has.

**Comment by Yuki2718** [comment]
@deusexcalamus Why did you remove comment?

**Comment by Yuki2718** [comment]
I checked the site without login, but now suspect `isshiki.donmai.us/post_views` may be needed if you logged in *and* updated files.

**Comment by deusexcalamus** [comment]
@Yuki2718 I didn't mean to remove it permanently. I was gonna rewrite it to be a bit more than just one line and forgot to actually...rewrite it. lol

**Comment by Yuki2718** [comment]
> 
>  namely the ability to see how many people have viewed a specific post on the site.

What is this? I can't find any difference with or without it gets blocked. Can you show screenshot of that (with NSFW images masked)?

**Comment by nonamethanks** [comment]
Yeah, we use this for userscripts and to optimize caching based on which posts are most viewed among other things, it's a fully internal component that's on a secondary domain for historical reasons. It shouldn't be blocked by default.

**Comment by Yuki2718** [comment]
Thanks for reporting, will open a PR to remove the rule.

**Comment by deusexcalamus** [comment]
Has this been fixed yet?
I could've sworn it started working for a little while, then stopped.

**Comment by Yuki2718** [comment]
Not yet.

**Pull request merged**
