### PR TITLE
P: https://www.mustijamirri.fi/

### PR DESCRIPTION
**Pull request by Nojuuu**
Hides cookie dialog/background overlay and fixes scrolling.

### CODE REVIEW

**Comment by Nojuuu** [comment]
@peace2000  @:ing you in case  you want to add temporary fix

**Comment by Nojuuu** [comment]
I made a small change because this seems to be the actual behaviour of the site after you accept cookies.

**Comment by peace2000** [comment]
Added a temporary fix.

**Comment by peace2000** [comment]
For ABP it's needed to add whitelistings, uBO can handle.

**Comment by Nojuuu** [comment]
Had to remake: https://github.com/easylist/easylist/pull/9918

**Pull request closed without merging**
