### PR TITLE
A: https://www.nextinpact.com/

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by papci** [comment]
Hi, can you provide us the reason of this PR ? This is not an Ad resource.

**Comment by Khrin** [comment]
This pull request is for EasyPrivacy (tracking), not EasyList (advertisements).

**Comment by papci** [comment]
@Khrin : this is not a domain that break easyprivacy rules (https://easylist.to/2011/08/31/what-is-acceptable-first-party-tracking.html). 
image

**Comment by ryanbr** [comment]
Can be trimmed @smed79 ? Only seeing ||tim.nextinpact.com^

**Pull request merged**
