### PR TITLE
A: https://www.gaiaonline.com/

### PR DESCRIPTION
**Pull request by CbumDino**
Bottom popup banner + Placeholders at https://www.gaiaonline.com/
Screenshot 2024-07-24 at 12 08 00
gaiaonline com2

### CODE REVIEW

**Comment by Yuki2718** [comment]
I don't see `###closeDisplay` unless I turn off either uBO or AG. @Khrin Can you check?

**Comment by Khrin** [comment]
Why i do see `owebsearch.com` edited?

**Comment by Yuki2718** [comment]
Looks somehow the change in https://github.com/easylist/easylist/pull/19645 was caried over.

**Comment by Khrin** [comment]
Now I can only see `gaiaonline.com###gaiaonline_leaderboard_atf`. Hopefully `gaiaonline.com###iframeDisplay` blocks also  `gaiaonline.com###closeDisplay`...

**Pull request closed without merging**
