### PR TITLE
A: https://www.brack.ch/

### PR DESCRIPTION
**Pull request by salim-b**

### CODE REVIEW

**Comment by spirillen** [comment]
If it ain't in the German filter I will suggest 1 of these in addition

```
brack.ch##.popup-box
##.daydeal-box
```

**Comment by salim-b** [comment]
> If it ain't in the German filter I will suggest 1 of these in addition
> 
> ```
> brack.ch##.popup-box
> ##.daydeal-box
> ```

This PR is for the [EasyList Cookie list](https://github.com/easylist/easylist/tree/master/easylist_cookie). The filters you propose would probably be best added to [Fanboy's Annoyance list](https://github.com/easylist/easylist/tree/master/fanboy-addon), I guess.

**Comment by spirillen** [comment]
You can still add them to the same PR

Not sure if I wouldn't add them to `easylist_general_block.txt` or `easylist_specific_block.txt`

**Comment by salim-b** [comment]
Ok, added `brack.ch##.daydeal-box` to `easylist_specific_hide.txt`.

**Review by spirillen — APPROVED** [review]

**Pull request closed without merging**
