### PR TITLE
A: https://sblive.online/mfootball1.html

### PR DESCRIPTION
**Pull request by smed79**
https://forums.lanik.us/viewtopic.php?f=62&t=42563

### CODE REVIEW

**Comment by peace2000** [comment]
Cannot connect to that domain at the moment.

**Comment by peace2000** [comment]
Doesn't seem to have been online for a long time.

https://web.archive.org/web/20190822190338/https://sblive.online/
https://web.archive.org/web/20190715183606/https://sblive.online/

**Comment by smed79** [comment]
Still a good generic.

**Comment by Khrin** [comment]
I disagree.

**Comment by smed79** [comment]
Ok, thank you.

**Pull request closed without merging**
