### PR TITLE
Add rum.condenastdigital.com analytics filter

### PR DESCRIPTION
**Pull request by migueldemoura**
Script load `https://rum.condenastdigital.com/client/boomerang-1.0.e7f702e5362e8a8f56f0cf3040ee24077d13a9a8.min.js`
Ping `https://rum.condenastdigital.com/beacon`

### CODE REVIEW

**Comment by Khrin** [comment]
Where's located?

**Comment by ryanbr** [comment]
@migueldemoura https://publicwww.com/websites/%22rum.condenastdigital.com%22/ I couldn't find an example site, do post.

**Comment by dcxstq2** [comment]
Example:
```
https://www.teenvogue.com/story/mitch-mcconnell-abortion-ban-roe
https://www.gqindia.com/get-smart/content/eco-warrior-zitin-munshi-is-helping-simplify-sustainability-for-young-entrepreneurs-in-india
```

The following sites also have the `condenastdigital` script, but I don't see the `rum.condenastdigital.com` request on them.
```
https://www.tatler.com
https://www.vogue.fr/
https://www.vogue.in/
https://www.revistagq.com/
```

**Comment by migueldemoura** [comment]
> @migueldemoura https://publicwww.com/websites/%22rum.condenastdigital.com%22/ I couldn't find an example site, do post.

I can pull this next week, I'm afraid I won't have my personal laptop until then.

**Comment by dcxstq2** [comment]
@Khrin 

The only way to really reproduce it is to spend time on the website. Try to reproduce it by clicking on a few different links.
But I can't always reproduce either.


URLs:

```
teenvogue.com/story/economic-disobedience-what-is
https://www.revistagq.com/video/watch/rosalia-10-cosas-sin-las-que-no-puede-vivir
```

```
https://rum.condenastdigital.com/client/boomerang-1.0.e7f702e5362e8a8f56f0cf3040ee24077d13a9a8.min.js
https://rum.condenastdigital.com/beacon
```

<details>
 <summary>Screenshot</summary>
 
rum1


</details>

<details>
 <summary>Screenshot</summary>

annotely_image


</details>

**Pull request merged**
