### PR TITLE
A: (nsfw) cuntest.net (fixes https://github.com/AdguardTeam/AdguardFi…

### PR DESCRIPTION
**Pull request by Yuki2718**
…lters/issues/102724)
https://github.com/AdguardTeam/AdguardFilters/issues/102724

### CODE REVIEW

**Comment by Yuki2718** [comment]
@Khrin @ryanbr  Can you move `||t.irtyc.com^` to EL as `||irtyc.com^`? Looks to be the same as already-blocked `||irtya.com^`. Sorry for misclassification.

**Comment by spirillen** [comment]
> ||irtya.com^

I would say `||irtya.com^` is adware, while you call `||irtyc.com^` tracking... I would call them both AdWare... as they are both porn affiliate links, of curse there are tracking of `href from`. Just my 1 cent

`https://t.irtya.com/7q5ik8niwy?offer_id=3788&aff_id=381&file_id=216070`

`https://t.irtyc.com/guz21fi4n4?aff_id=381&offer_id=3788&bo=3471,3472,3473,3474,3475&aff_sub=cuntnetmob`

**Comment by spirillen** [comment]
`view-source:https://t.irtyc.com/guz21fi4n4?aff_id=381&offer_id=3788&bo=3471,3472,3473,3474,3475&aff_sub=cuntnetmob`

```js
<script type="text/javascript" src="//ckstatic.com/js/historyjs/history.js"></script>
        <script type="text/javascript">
            var hash = (window.location && window.location.hash) ? window.location.hash : "";
            var dest = "https://a.vfghc.com/efa9bdbb-1afa-47b6-823c-9d64897c2ebc?subID1=cuntnetmob&affiliateID=44543&source=102f06ab6740e7274d3238660a801b&subID2=381" + hash;
            var boDest = "/ii1l4agvup?nopop=1&aff_id=381&offer_id=3788&bo=3472%2C3473%2C3474%2C3475&aff_sub=cuntnetmob&campaign_id=3471";
            var moveToBO = 0;
            window.addEventListener(
                "pageshow",
                function () {
                    if (moveToBO != 0) {
                        moveToBO = 0;
                        window.location.href = boDest;
                    }
                }
            );
            window.addEventListener("pagehide", function() {
                moveToBO = 1;
            });

            History.replaceState({"data": "0"}, boDest, boDest);

            setTimeout(function() {
                window.location.href = dest;
            }, 100);
        </script>
```

**Comment by Yuki2718** [comment]
And have you read https://github.com/easylist/easylist/pull/10009#issuecomment-991468347 ?

**Comment by spirillen** [comment]
> And have you read [#10009 (comment)](https://github.com/easylist/easylist/pull/10009#issuecomment-991468347) ?

Yes I did, my reply was regarding that comment

I didn't find any trails of any query relation. between the two domains. 

The only relation I can see is they both end up calling `vfghc.com`

**Comment by Yuki2718** [comment]
`irtya.com` is an adserver, should be in EL - this is what I meant.

**Comment by Khrin** [comment]
> `irtya.com` is an adserver, should be in EL - this is what I meant.

Already it is.

**Comment by spirillen** [comment]
Super, I came to think of, if I had misunderstood your comment while I was in the dungeon (cellar)

**Comment by Yuki2718** [comment]
> > `irtya.com` is an adserver, should be in EL - this is what I meant.
> 
> Already it is.

Whoops, I meant `irtyc.com` ...

**Pull request merged**
