### PR TITLE
A: `khanacademy.org`

### PR DESCRIPTION
**Pull request by kulkom**
Screenshot from 2024-04-01 20-30-01

Screenshot from 2024-04-01 20-29-33 (this one was shown when khanacademy.org/api/internal/graphql/getActiveDonationAsks was blocked but khanacademy.org###donate-banner wasn't hidden)
***
Screenshot from 2024-04-01 21-09-32

Screenshot from 2024-04-01 21-09-16

### CODE REVIEW

**Comment by ryanbr** [comment]
Wildcards aren't needed

**Comment by kulkom** [comment]
@ryanbr I have already removed them in efe5fc2 shortly after opening this PR. Sorry for adding them in the first place, I'm not very familiar with the syntax of adblock filter lists.

**Comment by ryanbr** [comment]
`||kastatic.org/images/donate/$domain=khanacademy.org`

**Comment by kulkom** [comment]
@ryanbr Done

**Comment by latteier** [comment]
Hi there! I just wanted to let you know that parts of this change triggered effects that may not have been intended. https://github.com/easylist/easylist/issues/19033

**Pull request merged**
