### PR TITLE
A: https://www.betaseries.com/en/series/tri_popularite

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by DandelionSprout** [comment]
The page elements have changed slightly since Oct 2020. I now propose:
```
! https://www.betaseries.com/en/shows/tri_popularite
betaseries.com##.parent-ad-desktop
! https://www.betaseries.com/en/show/nella-the-princess-knight (May need up to 3 pageloads)
||betaseries.com/images/partner^
```

**Comment by ryanbr** [comment]
Not seeing this @smed79  is this a valid commit?

**Comment by smed79** [comment]
> Not seeing this @smed79 is this a valid commit?

@ryanbr Check here 
- `https://www.betaseries.com/en/show/nella-the-princess-knight`
- https://i.ibb.co/yqDj8mq/123.jpg (Amazon Prime ads)

**Comment by ryanbr** [comment]
I'm looking at the commit, "clearhaus-top-banner.png" which I'm not seeing

**Comment by DandelionSprout** [comment]
I... think you're looking at the wrong row, ryanbr.

**Comment by ryanbr** [comment]
1. Click on `Commits" at the top of https://github.com/easylist/easylist/pull/6148
2. Click on the bottom `Merge branch 'master' into patch-980` 

```
-||bikeforums.net/images/sponsors/
+||binlist.net/clearhaus-top-banner.png
```

Unless I'm missing something, this commit is invalid.

**Comment by ryanbr** [comment]
I'm closing.

**Comment by DandelionSprout** [comment]
Closed or not, I think «Files changed», i.e. https://github.com/easylist/easylist/pull/6148/files, is that tab that actually matters.

**Pull request closed without merging**
