### PR TITLE
Add Shareon

### PR DESCRIPTION
**Pull request by kytta**
Closes https://github.com/easylist/easylist/issues/15037

### CODE REVIEW

**Comment by ryanbr** [comment]
This would create false positives on 1st party content

**Comment by kytta** [comment]
> This would create false positives on 1st party content

Yeah I thought that too, I just took example of the other list entries. How would one make something like this possible? Or is the name too generic for this?

**Comment by kytta** [comment]
> `##button[ng-click^=shareOn]`

I want to point out that this entry has nothing to do with my package, as it's not an Angular component :)

---

> `/shareon.` has the slight drawback that it would also match `https:/`**`/shareon.`**`js.org`, but there are ways to narrow it down, from the common (`/shareon.$third-party`) to the rather rare (`/[a-z0-9]\/shareon\./`)

Aw shucks, you're right! Well, one could do a list of all possible scripts:

```
/shareon.es.js
/shareon.iife.js
/shareon.umd.js
/shareon.min.css
```

**Comment by krystian3w** [comment]
Also works:

```adb
/shareon.$script,stylesheet
```

due homepage don't use first party scripts and css files yet.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/15037

**Pull request closed without merging**
