### PR TITLE
M: Removed propellerads redundant filters

### PR DESCRIPTION
**Pull request by SMed79**

### CODE REVIEW

**Comment by ryanbr** [comment]
Why are they considered redundant?

**Comment by SMed79** [comment]
these are propellerads domains, added here https://github.com/easylist/easylist/commit/f8bb8a856586cb33f0c98afca3b56b4209463765#diff-4903e7590de76df1abe1703921a2c88bR4229

**Comment by ryanbr** [comment]
So I guess I can close this?

**Comment by SMed79** [comment]
First you should remove the section "**! youwatch.org adservers**"

**Comment by SMed79** [comment]
https://github.com/easylist/easylist/issues/982

**Pull request closed without merging**
