### PR TITLE
pageviews.toolforge.org/ad_block_test.js

### PR DESCRIPTION
**Pull request by tbertels**

### CODE REVIEW

**Comment by llacb47** [comment]
Why?

**Comment by tbertels** [comment]
On https://pageviews.toolforge.org:

> Looks like you are using an ad blocker!
Pageviews Analysis shows no ads, but the ad blockers blacklist websites that collect metrics. In our case, we're just trying to show you metrics, not collect them!

>This issue may be resolved by simply **updating your ad blocker, specifically the EasyPrivacy list**.

Unless it gets added to the whitelist, updating the EasyPrivacy list won't change anything.

**Comment by llacb47** [comment]
Easyprivacy doesn't fix anti adblock.

**Comment by tbertels** [comment]
Why does it say `Anti-Adblock`
at https://github.com/easylist/easylist/blob/master/easylist/easylist_whitelist.txt#L475?

**Comment by ryanbr** [comment]
Those are existing rules, and very limited to certain sites. To Limit liability.

**Pull request closed without merging**
