### PR TITLE
A: https://www.youtube-nocookie.com/embed/Dx01aFTyzgM

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by ryanbr** [comment]
Are we sure about this.. If I recall correctly stats/watchtime? broke things @smed79

**Comment by llacb47** [comment]
That breaks youtube watch history.

**Comment by llacb47** [comment]
Don't you have to remove nocookie aswell?

**Comment by smed79** [comment]
Could you provide steps to reproduce the issue on YT nocookie?

**Comment by ryanbr** [comment]
Testing in Enhanced Trackers list, to be sure.

**Comment by ryanbr** [comment]
Given we just resolved many recent YT issues. I'll leave this,

**Pull request closed without merging**
