### PR TITLE
http://shink.in

### PR DESCRIPTION
**Pull request by abpvn**

### CODE REVIEW

**Comment by monzta** [comment]
What is the reason for blocking newrelic.com? It's a tracking service that is already blocked in EasyPrivacy. Please also provide an example URL for shink.in. Thanks!

**Comment by abpvn** [comment]
Sorry about  newrelic.com it only tracking service. But another filter is hiding disable adblock warning and block popup

**Comment by abpvn** [comment]
I've updated filter. Here is example [http://shink.in/oMXpJ](http://shink.in/oMXpJ)

**Comment by abpvn** [comment]
Hi @monzta filter is updated. So can you merge this pull request?

**Comment by monzta** [comment]
Sorry, looks like ryanbr took care of it already: https://github.com/easylist/easylist/commit/d79bb8ca8b92eab5b3f0b42e7646f38dbe398d3f

**Pull request closed without merging**
