### PR TITLE
A: nuudelit.fi (generic cookie block & specific hide)

### PR DESCRIPTION
**Pull request by peace2000**
Generic cookie block & specific hide rule.

Sample pages:
https://www.tuska.fi/
http://kalkinpoisto.com/
https://www.nuudelit.fi/
https://www.oivasivut.fi/
https://paajala.fi/
https://www.linseed.fi/
http://mokkivesi.fi/
http://hanavesi.fi/
http://hanavesitesti.fi/
http://www.keskustaopiskelijat.fi/

Note: "banneri" is a Finnish variant of "banner".

### CODE REVIEW

**Comment by ryanbr** [comment]
@peace2000  probably too generic, just join the domains together and make it speciifc

**Comment by peace2000** [comment]
@ryanbr Are you referring to both of my suggestions or just to another?

**Comment by ryanbr** [comment]
That is what I'm saying, `##.alert_banneri` too generic, make it domain specific for each

**Comment by peace2000** [comment]
@ryanbr Done.

**Pull request merged**
