### PR TITLE
A: (discordbots.org) #3780

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by Oliyy** [comment]
Hey, I own this site. This is clearly a malicious PR, we do not operate popup ads on the site and we're pending acceptable ads approval.

**Comment by TheOnlyKirb** [comment]
> Hey, I own this site. This is clearly a malicious PR, we do not operate popup ads on the site and we're pending acceptable ads approval.

I did, yes, post a report regarding the site circumventing the ads, the original report was not intended to be malicious in any manner and I have discussed with [Ken](https://github.com/NotWeeb) and believe that the nature of the ads are fine at this point. Hope this helps settle things/clears things up. I will also state that I do not believe @smed79 was attempting to troll anyone with these PRs.

**Comment by PimDeWitte** [comment]
Duplicate discussion of https://github.com/easylist/easylist/pull/3780 - requesting a close here also

**Comment by llacb47** [comment]
Someone correct me if I'm wrong, but doesn't only ABP honor "acceptable ads"? I don't think it is a thing in this filter list.

**Comment by TheOnlyKirb** [comment]
> Someone correct me if I'm wrong, but doesn't only ABP honor "acceptable ads"? I don't think it is a thing in this filter list.

While AdBlockPlus does maintain a fair amount of the content regarding Acceptable Ads, EasyList has been known to have a sort of honor system for ads that are non-invasive and not  part of an ad network. In this case these ads are not intrusive, and don't belong to an ad network. Of course it is to be noted I don't speak for EasyList as a group or maintainer.

**Comment by smed79** [comment]
EasyList and ALL additional regional lists block ALL ads by default.

https://easylist.to/pages/policy.html
https://adblockplus.org/en/about#blacklisted-ads

This concept of [non intrusive ads](https://adblockplus.org/en/acceptable-ads) is created and managed by Eyeo. 

To get discordbots.org whitelisted on their list, follow the link 
https://adblockplus.org/en/acceptable-ads#get-whitelisted

**Comment by PimDeWitte** [comment]
> EasyList and ALL additional regional lists block ALL ads by default.
> 
> https://easylist.to/pages/policy.html
> https://adblockplus.org/en/about#blacklisted-ads
> 
> The concept of [non intrusive ads](https://adblockplus.org/en/acceptable-ads) is created and managed by Eyeo. To get discordbots.org whitelisted on their list, follow the link https://adblockplus.org/en/acceptable-ads#get-whitelisted

The point in question here is not if the ads are acceptable, but why it was added to a Popads domains, which it is clearly not (as it's a top 5k alexa site and used by ltos of people every day). That seemed like overreach. That's what this PR is for, and therefore should not be merged.

**Comment by ryanbr** [comment]
Site isn't too bad, doesn't deserve a generic block. Sure if revolving ads start being added, we can revisit this. But as it stands its fine.

**Comment by Oliyy** [comment]
@ryanbr Hey I presume my PR was auto closed by a bot, can we get the partnered class removed as well seeing as it is no longer used? #3804

**Comment by llacb47** [comment]
Why, and then next week you'll start using it again...?

**Comment by TheOnlyKirb** [comment]
> Why, and then next week you'll start using it again...?

Well, the partnered class was connected to the same ad as what was already deemed acceptable/didn't warrant a generic block - so removing it shouldn't be an issue, correct me if I am wrong @Oliyy

**Comment by smed79** [comment]
> was already deemed acceptable

EasyList does not have acceptable ads https://github.com/easylist/easylist/pull/3786#issuecomment-512526814

**Comment by TheOnlyKirb** [comment]
> EasyList does not have acceptable ads [#3786 (comment)](https://github.com/easylist/easylist/pull/3786#issuecomment-512526814)

I understand this, we all do - I was referencing the comment from @ryanbr - unless I am misinterpreting their comment

**Comment by ryanbr** [comment]
I'm only referring to the generic block of this specific pull request, tldr no other changes are needed.

**Comment by Oliyy** [comment]
It's the same thing lol but sure...

**Pull request closed without merging**
