### PR TITLE
A: https://www.ianimes.org/

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by spirillen** [comment]
I'm getting a clue that it should be possible to block this domain entirely

I have the impression that this domain is all about tracking and violating users privacy. See attached.

As side note, as I only sees HTTP status code 504, in the last 5 minutes, this can be a temporary error, but i doubt and I would recommend to revisit this url later for confirmation.

<details><summary>Logger output</summary>

image

image



| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +127 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/404.html` |
| +127 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/favicon.ico` |
| +127 |  |  | `www.ianimes.org` | 1 | doc | `https://www.ianimes.org/index.php` |
| +2 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/404.html` |
| +2 |  |  | `www.ianimes.org` | 1 | image | `https://www.ianimes.org/favicon.ico` |
| +2 |  |  | `www.ianimes.org` | 1 | doc | `https://www.ianimes.org/index.php` |
| +1 |  |  | `www.ianimes.org` | 1 | doc | `https://www.ianimes.org/` |
| +1 |  |  | ianimes.org | 1 | doc | `https://ianimes.org/` |
| +0 |  |  | ianimes.org | 1 | doc | `http://ianimes.org/` |
</details>

**Comment by smed79** [comment]
@spirillen `ianimes.org` is an anime streaming site

https://imgur.com/5XQrfuC.png
https://imgur.com/JUV89Mw.png

**Comment by spirillen** [comment]
Hi thanks for your reply @smed79.
How did you get those screenshots? I still only get 504

**Comment by smed79** [comment]
> How did you get those screenshots?

anything special. Maybe the webmaster is blacklisting some ip addresses.

I would recommend you to try behind a vpn.

**Comment by spirillen** [comment]
well curl -I returns 504 from Germany and Finland, but yes, it could be IP related

**Pull request merged**
