### PR TITLE
A: https://www.nextinpact.com/

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by papci** [comment]
Please could you consider stopping blocking our  internal analytics ? We are now compliant to https://easylist.to/2011/08/31/what-is-acceptable-first-party-tracking.html.

**Comment by smed79** [comment]
@ryanbr @Khrin

**Comment by papci** [comment]
If you notice anything that should be removed let me know and i'll take a look.

**Comment by ryanbr** [comment]
renaming a piwik script doesn't make it better. We already block piwik. 

```
fanboy@Ubuntu:~/git/easylist/easyprivacy$ grep -r piwik *
easyprivacy_general.txt:/piwik-$domain=~github.com|~matomo.org|~piwik.org
easyprivacy_general.txt:/piwik.$image,script,domain=~matomo.org|~piwik.org
easyprivacy_general.txt:/piwik.*/ping?
easyprivacy_general.txt:/piwik.php
easyprivacy_general.txt:/piwik/*$domain=~github.com|~matomo.org|~piwik.org
easyprivacy_general.txt:/piwik1.
easyprivacy_general.txt:/piwik2.js
easyprivacy_general.txt:/piwik_
easyprivacy_general.txt:/piwikapi.js
easyprivacy_general.txt:/piwikC_
easyprivacy_general.txt:/piwikTracker.
easyprivacy_general.txt:://piwik.$third-party
```

Why shouldn't this script be treated any differently like any other piwik script. @papci

**Comment by papci** [comment]
because its a customized version of the original Piwik script. We have modded it and it should be complient with Easyprivacy rules.

**Comment by ryanbr** [comment]
Happy to merge this.

**Comment by papci** [comment]
@ryanbr is there any particular reason ?

**Comment by ryanbr** [comment]
It's still a tracker regardless, and Easyprivacy is a list designed for privacy. Also based on previous blocks, I see no reason to treat this any different, not playing favorites here.

**Comment by papci** [comment]
@ryanbr its not about being favorized over others, it's just about your own rules. If  theses rules are not more relevant, just remove the page from the internet. @llacb47 gave me rules link and said that following these rules will be considered by "easyprivacy staff" (https://github.com/easylist/easylist/pull/4848#issuecomment-584834855)

**Pull request merged**
