### PR TITLE
A: http://extramovies.casa/

### PR DESCRIPTION
**Pull request by smed79**
https://github.com/easylist/easylist/pull/3347#issuecomment-609068625

### CODE REVIEW

**Comment by ryanbr** [comment]
Being dealt with..

**Comment by ghajini** [comment]
Revolving ad servers
`*$script,3p,domain=extramovies.casa` 
will take care of it with offcourse require exceptions

**Comment by smed79** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/issues/374

**Comment by ghajini** [comment]
Fake buttons
`extramovies.casa##a.ad_btn`
`extramovies.casa##[href^="/dlbutton.php"]`

**Comment by smed79** [comment]
@ghajini https://git.io/JfMpI

**Pull request closed without merging**
