### PR TITLE
A: https://cloudvideo.tv/iznqu5t3jrnh

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by smed79** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4636

**Comment by ghajini** [comment]
Does the said filter is for https://github.com/uBlockOrigin/uAssets/issues/4636#issuecomment-472559230

It it was then it doesn't work on my end

**Comment by smed79** [comment]
The filter is for the vpn ad link https://imgur.com/9gxLtoM.png

**Comment by ghajini** [comment]
Ohk that may appear for deleted videos......
Also while in abp.....
`cloudvideo.tv/t0pjubv9pl91#`
Clicking on `download` and then in next page click on `direct link to download` generates VPN ads....ubo is fixed, abp suffers from this. .......so your pull request should include filter for this also

**Pull request merged**
