### PR TITLE
A: https://discordbots.org/

### PR DESCRIPTION
**Pull request by smed79**
https://forums.lanik.us/viewtopic.php?f=62&t=43272

### CODE REVIEW

**Comment by PimDeWitte** [comment]
As a core contributor to react native, and somebody who actively participates in open source software, and somebody who actively advertises on discordbots.org - it is not a pop ads domain, and ads adhere to acceptable ads, these are just troll PRs.

The site is also top 5K alexa - pop up ad domain, really @smed79?

**Comment by TheOnlyKirb** [comment]
Well lets not draw blame to any particular person such as @smed79, while I did, yes, post a report regarding the site circumventing the ads, I have discussed with [Ken](https://github.com/NotWeeb) and believe that the nature of the ads are fine at this point. Hope this helps settle things. I will also state that I do not believe @smed79 was attempting to troll anyone with these PRs.

**Comment by PimDeWitte** [comment]
> Well lets not draw blame to any particular person such as @smed79, as they are responding to a report, and doing their job. While I did, yes, post a report regarding the site circumventing the ads, I have discussed with [Ken](https://github.com/NotWeeb) and believe that the nature of the ads are fine at this point. The original issue was not stating they had popup ads, that was never mentioned, and if was mentioned, then it wasn't by me - the original issue was the circumventing of the filter. Hope this helps settle things. I will also state that I do not believe @smed79 was attempting to troll anyone with these PRs.

Thank you for clarifying. I'm actively working with DBL to make sure the ads are adhering to acceptable ads (including Medal's) and afaik they are pending acceptable ad whitelisting at the moment. With regards to circumventing - I will chat with Oliy, but as long as they adhere to acceptable ads I don't understand why we are blocking acceptable ads instead of focussing on the real offenders. 

Yes - it's everyone's right to block whatever ads they want. I totally respect that, but DBL's adhere to every possible standard and are not served through a network. They are the most legit ads there are. Thats' why we advertise there. And with actions like this, it hurts companies trying to advertise the right way. 

Thank you for clarifying, requesting a close here.

**Comment by ryanbr** [comment]
Yeah, safe to close.

**Comment by SilverCory** [comment]
Why was this closed? O_O They're still advertisements "acceptable" or not.

**Pull request closed without merging**
