### PR TITLE
M: Cleanup redundancy

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by ryanbr** [comment]
Whats this exactly?

**Comment by ryanbr** [comment]
Also note, old domains are removed via another tool.

**Comment by ryanbr** [comment]
We'll close this, these domaina still active (whois).

**Comment by smed79** [comment]
@ryanbr Sorry for the noise, the removal wasn't intentional (_bad timing pull request_).

What i was pointing is below
``` adblock
||udwjjxnexs.xyz^ has been made redundant by ||udwjjxnexs.xyz^
||tntgfyivhgz.com^ has been made redundant by ||tntgfyivhgz.com^
||ad2up.com^$third-party has been made redundant by ||ad2up.com^
||h12-media.com^$third-party has been made redundant by ||h12-media.com^
||adlogists.com^$third-party has been made redundant by ||adlogists.com^
||my.audmrk.com^ has been made redundant by ||audmrk.com^
||basepush.com^$third-party has been made redundant by ||basepush.com^
||betimbur.com^$third-party has been made redundant by ||betimbur.com^
||breakingfeedz.com^$third-party has been made redundant by ||breakingfeedz.com^
||btpnav.com^$third-party has been made redundant by ||btpnav.com^
||exoclick.com^$third-party has been made redundant by ||exoclick.com^
||mail.ezexfzek.com^ has been made redundant by ||ezexfzek.com^
||getsurv2you.org^ has been made redundant by ||getsurv2you.org
||hoo1luha.com^$third-party has been made redundant by ||hoo1luha.com^
||virus.newadsclicks.com^ has been made redundant by ||newadsclicks.com^
||oclaserver.com^$third-party has been made redundant by ||oclaserver.com^
||onvictinitor.com^$third-party has been made redundant by ||onvictinitor.com^
||padsdelivery.com^$third-party has been made redundant by ||padsdelivery.com^
||padstm.com^$third-party has been made redundant by ||padstm.com^
||vaccine.phee1oci.com^ has been made redundant by ||phee1oci.com^
||propellerads.com^$third-party has been made redundant by ||propellerads.com^
||rouwhapt.com^ has been made redundant by ||rouwhapt.com
||sdasasyydd.com^$third-party has been made redundant by ||sdasasyydd.com^
||tr-usual.xyz^ has been made redundant by ||tr-usual.xyz
||trackvoluum.com^$third-party has been made redundant by ||trackvoluum.com^
||youlamedia.com^$third-party has been made redundant by ||youlamedia.com^
```

**Comment by ryanbr** [comment]
Okay rebase @smed79  The comment regarding redundant should've been part of the orginal post.

**Pull request closed without merging**
