### PR TITLE
A: https://www.uploadmp4.com/be2a4093716f4faa

### PR DESCRIPTION
**Pull request by smed79**
https://forums.lanik.us/viewtopic.php?f=62&t=42566

### CODE REVIEW

**Comment by smed79** [comment]
@wizmak popup / popunder [#p145877](https://forums.lanik.us/viewtopic.php?p=145877&hilit=abort-on-property+ABP+filters#p145877)

**Comment by smed79** [comment]
@ryanbr @Khrin

**Comment by smed79** [comment]
@ryanbr @Khrin

**Comment by ryanbr** [comment]
Dead domain.

**Comment by smed79** [comment]
Yes :D

**Pull request closed without merging**
