### PR TITLE
A: (nsfw) www.40svintageporn.com

### PR DESCRIPTION
**Pull request by Yuki2718**
Analytics:

<details>
<summary>Screenshot</summary>

40svintageporn

</details>

### CODE REVIEW

**Comment by Yuki2718** [comment]
Also addressed ad frames and on-player overlay causing popup.

**Comment by ryanbr** [comment]
```
||40svintageporn.com/hit| -> ||40svintageporn.com/hit
||supersextube.pro/ntv-$subdocument -> ||supersextube.pro/ntv-
```

@Yuki2718

**Comment by Yuki2718** [comment]
@ryanbr Done.

**Review by spirillen — APPROVED** [review]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/porn-records/-/issues/191

</details>

**Pull request closed without merging**
