### PR TITLE
A: linkpizza.com/*advertiser* to whitelist

### PR DESCRIPTION
**Pull request by arjanpronk-kizitos**
Fixes internal ajax post when browsing /nl/advertiser and /advertiser (en) pages.

### CODE REVIEW

**Comment by Khrin** [comment]
Sorry, but we can't accept this. What's exactly broken? I don't see anything erroneously blocked.

**Comment by arjanpronk-kizitos** [comment]
Same issue as in https://github.com/easylist/easylist/pull/216, except now the translated versions of the urls which live on linkpizza.com/nl/advertiser/* experience this issue.

We unfortunately don't have any pages accessible without login where I can demonstrate this at the moment. But any Ajax post made, when sorting a table for example, is blocked as */advertiser is in the url.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/251834abe62df23b0036a418a2757c27a23694ba
Please can you tell if this fix helps?

**Comment by arjanpronk-kizitos** [comment]
This fixes the issue on /nl/advertiser/* pages but breaks /advertiser/* pages

**Pull request closed without merging**
