### PR TITLE
[16343] Remove lndo from privacy list.

### PR DESCRIPTION
**Pull request by almunnings**
Resolve https://github.com/easylist/easylist/issues/16343

lndo.site is a developer tool, localhost resolution is intended.

### CODE REVIEW

**Comment by NickDickinsonWilde** [comment]
LGTM

**Comment by tobybellwood** [comment]
As a [recognised contributor to](https://github.com/lando/cli/blob/main/contributors.yml#L168) and sponsor of Lando, I very much support it's removal from this list.

LGTM

**Comment by ryanbr** [comment]
Still not acceptable.

**Comment by pirog** [comment]
@ryanbr i am the maintainer of Lando, why has this been added? What policy does it violate? `*.lndo.site` is a well known router for local development. 

Also why is this project called easylist? You've certainly not made things easy for a large amount of developers.

**Comment by patrick-lienau** [comment]
@pirog, iof you look at @ryanbr's reference to b179159, you can see he did make a change. He added `$third-party` which apparently makes requests behave like CORS (my dreaded nemesis).

Imagine you have a site running in lando and have a page http://whatever.site.lndo/secrets.txt which is webaccessable because this is theoretical. Now if you went to some malicious site, they could (in theory) send an fetch request to `http://whatever.site.lndo/secrets.txt`and get your secrets... I guess. I'm not really worried about it but I suppose it could happen. 

Anyway, in **uBlock origin, I purged my cache then did check for updates and now my page loads correctly**. So while his terse reply was less than helpful, I suppose he did resolve the issue.

**Comment by almunnings** [comment]
This directly breaks trying to use lando for headless development. EG a JS app talking to a backend on another domain.

**Pull request closed without merging**
