### PR TITLE
P: https://atcoder.jp/posts/780

### PR DESCRIPTION
**Pull request by Yuki2718**
Links to their books:

atcoder1

atcoder2

### CODE REVIEW

**Comment by ryanbr** [comment]
These are amazon ads, should it be allowed. I'm hesitant @Yuki2718

**Comment by Yuki2718** [comment]
> These are amazon ads, should it be allowed. I'm hesitant 

They're their official books and not random ones only to earn ad revenue. Without whitelisting, all the visitor see is strange broken page, which results in whitelisting the whole page, exposing them to more ads and tracker as in `https://twitter.com/gojira_kyopro/status/1594888912630972416`.

**Comment by Khrin** [comment]
@Yuki2718 Why is required such a filter for `assoc-amazon.com`? Why not using `@@||assoc-amazon.com/widgets/cm?$subdocument,domain=atcoder.jp`?

**Comment by Yuki2718** [comment]
@Khrin I will change.

**Comment by Khrin** [comment]
Thanks.

**Pull request merged**
