### PR TITLE
Improve specificity of citi.com tracker block

### PR DESCRIPTION
**Pull request by samfitz66**
Improves the specificity of the block issued for https://github.com/easylist/easylist/issues/9233, while taking into account concerns raised in https://github.com/easylist/easylist/issues/9274

### CODE REVIEW

**Comment by ryanbr** [comment]
Closing, filter is still good. Nothing has broken. If we had any replicated issues maybe would be reviewed.

**Comment by iam-py-test** [comment]
> Improves the specificity of the block issued for #9233, while taking into account concerns raised in #9274

Provide a url which is broken so people can investigate...

**Comment by samfitz66** [comment]
I can't provide a URL for you to test as our affected URL is part of our SaaS product, but here's a screenshot:

image

Would really appreciate if you could merge this to make the block more specific. Of course we could change the naming of our internal endpoints, but this will be considerable effort, so would really help us if you could change on your end instead, as otherwise we need to tell all our clients to disable ublock in order for our app to work (which doesn't benefit either of us). Thank you 🙏

**Comment by iam-py-test** [comment]
Is there a way to create a test account and send the credentials to the Easylist team?
(I don’t have any access to this repo and don’t make decisions here either)

**Comment by samfitz66** [comment]
Can do if necessary, but they can see from the screenshot what would need to be changed to fix it and I believe this patch would work, it would fix the issue this is causing us without affecting the original Citi block.

@ryanbr - let me know if you would like me to set you up with a test account or have a demo to show this issue, or if the above screenshot is sufficient.

**Pull request closed without merging**
