### PR TITLE
A: https://receive-smss.com/sms/33752124546/

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by ryanbr** [comment]
Not seeing these urls @smed79

**Comment by smed79** [comment]
@ryanbr 

- https://imgur.com/GamzVfP.png 
- https://pastebin.com/N0Ny139i

**Comment by ryanbr** [comment]
Is there a better rule or cosmetic?

**Comment by smed79** [comment]
> Is there a better rule or cosmetic?

- `receive-smss.com##a[href^="https://app.smsplaza.io/"]`

**Comment by smed79** [comment]
fix https://github.com/abp-filters/abp-filters-anti-cv/issues/1075

**Pull request closed without merging**
