### PR TITLE
thehackernews.com ads

### PR DESCRIPTION
**Pull request by SeriousHoax**
Ads: 

<details><summary>Screenshot:</summary>

</details><br/>

### CODE REVIEW

**Comment by llacb47** [comment]
do you really need to use `>`?

**Comment by SeriousHoax** [comment]
> 
> 
> do you really need to use `>`?

You're right. I don't need to. I just changed it. Is it alright now?

**Comment by llacb47** [comment]
I mean, isn't it enough to use the class selectors by themselves?

**Comment by SeriousHoax** [comment]
> 
> 
> I mean, isn't it enough to use the class selectors by themselves?

Suggest me what you think should be the better option and I'll make the change.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/e71eac111e83417a526271c51d4e2e84edd8fb3b

**Comment by Yuki2718** [comment]
`##body .google.cf`
is less efficient than
`##body > .google.cf`
but in this case the simple class was enough as @llacb47 commented unless they caused false positive. Also you should check if those ads can't be blocked with dev tools before committing cosmetic filters, but in this case they're called from inline-script so unblockable in standard ABP syntax EasyList honors (though regex can be used, it's not worth as these images' paths will change soon).

I make PR only if I'm confident the rules are optimal, otherwise PR can take more time than issue reports by requesting correction and waiting for it, if they chose not to ignore the request and fix by themselves - often the case in AdGuard. Well, this should be reported back to AG so they can remove the redundant rules.

@llacb47 How do you think about
```
thehackernews.com##+js(acis, images, thn.li)
thehackernews.com##+js(acis, group, Math.random)

```
of kinds, worth reporting to uAssets?

**Pull request closed without merging**
