### PR TITLE
A: https://www.malwarebytes.com/vpn

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by simao** [comment]
Was this an error? It mentions malwarebytes.com but blocks am.i.mullvad.net which is part of https://mullvad.net/ But why block a well established vpn provider? (mullvad) Are they tracking something somewhere?

**Comment by jbjorkang** [comment]
Hi,

I lead the Infrastructure Team at Mullvad VPN, and subsequently maintain the DNS blocklist service that we provide. We caught wind of this addition and would also like to ask that it be removed.

am.i.mullvad.net has no trackers, this page is used solely to verify the connection status of customers using our VPN service.

Thanks in advance.

**Comment by Khrin** [comment]
@jbjorkang removed https://github.com/easylist/easylist/commit/2ab4ea8541a35bf0cce476692c86475a188e00cf

**Comment by jbjorkang** [comment]
> @jbjorkang removed https://github.com/easylist/easylist/commit/2ab4ea8541a35bf0cce476692c86475a188e00cf

Thank you kindly

**Pull request merged**
