### PR TITLE
A: elisa.fi (+others) (cookie dialog block)

### PR DESCRIPTION
**Pull request by peace2000**
https://elisa.fi/

https://elisaviihde.fi/

https://www.maaseuduntulevaisuus.fi/uutiset/84084a42-be65-48ff-a5ed-6eba564b6083 (this is the only news website, this link contains a video, that works fine if consent script is blocked.

### CODE REVIEW

**Comment by Nojuuu** [comment]
@peace2000 

https://github.com/AdguardTeam/AdguardFilters/issues/123027

https://elisa.fi/kauppa/puhelinliittymat

**Comment by peace2000** [comment]
@Nojuuu I don't see any issues on my end.

**Comment by Nojuuu** [comment]
For me it infinitely loads like in that issue report.

**Comment by peace2000** [comment]
Wait.. issue seems to appear if using incognito mode...

**Comment by peace2000** [comment]
When I refresh the page again, issue goes away. Though it should ofc work at the first time.

**Comment by peace2000** [comment]
Dont' have time today, will make PR tomorrow unless you are faster @Nojuuu

**Comment by Nojuuu** [comment]
Probably just removing from `cookielaw.org specifics` is enough? Cosmetic filters still hide the cookie popup and that thing loads fine.

**Comment by Nojuuu** [comment]
https://github.com/easylist/easylist/pull/12978

**Comment by peace2000** [comment]
@Nojuuu Yeah though for me the cookie popup flickers before it's hidden... Generic cosmetic doesn't work fast enough for this site.

**Comment by peace2000** [comment]
How does this work for you?

`||cdn.cookielaw.org^*/*.js$script,redirect=noopjs,domain=elisa.fi`

**Comment by Nojuuu** [comment]
Same loading issues with that.

**Comment by Nojuuu** [comment]
What if you just block the banner script
 `||cdn.cookielaw.org/scripttemplates/6.33.0/otBannerSdk.js$script,domain=elisa.fi`

**Comment by peace2000** [comment]
@Nojuuu Easylist maintainers aren't usually happy to add specific cosmetics if there's an existing generic filter.

in uBO, flickering of hidden elements is more common because thousands of generic cosmetics aren't loaded unconditionally, like ABP does and uses more resources because of that... If a generic cosmetic flickers on a specific page, the solution is to add a specific cosmetic to cover that issue. But Easylist maintainers aren't usually willing to do that.

Only option is find a way to block it.

```
||cdn.cookielaw.org/scripttemplates/*/assets/*.json$xmlhttprequest,domain=elisa.fi
||cdn.cookielaw.org/scripttemplates/*/assets/otCommonStyles.css$xmlhttprequest,domain=elisa.fi
```

These seem to block to banner without causing issues. Can you test too?

**Comment by Nojuuu** [comment]
Seems to work.

**Comment by peace2000** [comment]
https://github.com/easylist/easylist/pull/12987

**Pull request merged**
