### PR TITLE
P: blocking the cookie notification blocks also videos, rp.pl

### PR DESCRIPTION
**Pull request by peace2000**
https://github.com/ryanbr/fanboy-adblock/issues/1078

### CODE REVIEW

**Comment by Khrin** [comment]
On what page?

**Comment by peace2000** [comment]
rp.pl is an actual url :D

Here is a sample link from original issue report:

https://www.rp.pl/Media-i-internet/311079936-Wlasciciele-Multimediow-wycofali-sie-z-transakcji-z-Vectra.html

**Comment by ryanbr** [comment]
The wild card isn't needed.

**Comment by peace2000** [comment]
@ryanbr Removed it.

**Pull request closed without merging**
