### PR TITLE
A: google mobile ads hide, google.fi

### LINKED ISSUE #4004: Google ads not blocked when searching through a mobile browser
### List the website(s) you're having issues:

`www.google.fi`, `google.com` (not just those, all language variants are affected)

### What happens?

Google ads are not blocked

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Android 8
- Browser/version: Firefox 68.1
- Adblock Extension/version: Ublock Origin 1.22.2

### Other details:

This rule seems to block ads whichever language variant is being used: `##div#main > div.ZINbbc.xpd.O9g5cc.uUPGi`

You can also reproduce this problem on desktop by using an user agent switcher. More comfortable than using a cell phone to investigate this. :D

This user agent can used, for example:

Mozilla/5.0 (Android 9.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

### PR DESCRIPTION
**Pull request by peace2000**
Google ads for mobile users are not hid.

Here is my issue https://github.com/easylist/easylist/issues/4004 report I reported earlier.

Fixes #4004 

Earlier it seemed that this element was in use in all language variants but it doesn't seem to be so anymore. But it's definetely being used on google.fi.

To reproduce:

1. Use a mobile user agent on web browser. Here is one user agent that can be used:

`Mozilla/5.0 (Android 9.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0`

2. Use a search word that will spark ads, such as "tietokone" (computer in English). Word "mainos" means "an ad".

3. You might need to have a Finnish ip and browser.

65819492-d6fbbc00-e225-11e9-8a89-12e37a8e68d3

### CODE REVIEW

**Comment by peace2000** [comment]
Ads are blocked when I have this rule  `www.google.fi##div#main > div.ZINbbc.xpd.O9g5cc.uUPGi` and it activates in the logger:

Näyttökuva (99)

And mobile ad results (mainos) are blocked.

**Comment by llacb47** [comment]
You can also show the cosmetic filters applied by clicking the code icon in the toolbar...

**Comment by peace2000** [comment]
@ryanbr ?

**Comment by ryanbr** [comment]
Only specific to one google domain? are you sure?

**Comment by monzta** [comment]
Seems to be working for google.de as well.

**Comment by peace2000** [comment]
Easiest and to-be-sure solution would be to add every Google's language variant. It's hard to test every single one of them by using slow free proxies...

**Comment by monzta** [comment]
I checked some with a VPN and it seems to work. Feel free to create a PR with all domains for this filter but please add to the `! msn.com` section. I added another one I just found: https://github.com/easylist/easylist/commit/c61c116

**Comment by peace2000** [comment]
Hi! I updated this pull req. It has all google's regional domains and it's not in the msn section anymore. :D

**Comment by llacb47** [comment]
www not needed?

**Comment by peace2000** [comment]
Guess not but that's what I have copied directly from Easylist itself.

**Comment by monzta** [comment]
I'd suggest to leave www. as it could cause false positives on subdomains.

**Pull request merged**
