### PR TITLE
Update admiral tracking servers

### PR DESCRIPTION
**Pull request by seia-soto**
```
sittingpets.com
```

Co-authored-by: Mike-E-angelo <2931376+Mike-E-angelo@users.noreply.github.com>
refs https://github.com/ghostery/broken-page-reports/issues/743

### CODE REVIEW

**Comment by Yuki2718** [comment]
Is it on `www.usatoday.com`? I don't see that request.

**Comment by Mike-E-angelo** [comment]
I am pretty sure they are rotating through a list of domains to keep us guessing.  Here is what I have so far and it has made this site actually useable again 😁

```
||defensevest.com^
||worldlever.com^
||colossusssp.com^
||frogator.com^
||mindfulgem.com^
||teacupbooks.com^
||scenicdrops.com^
||sittingpets.com^
```

**Comment by Khrin** [comment]
Not seen on this domain.

**Comment by Mike-E-angelo** [comment]
> Not seen on this domain.

Hi @Khrin can you explain this, please?  While one domain might not be used today (or this week) there is some rotation going on with a new domain used per week-ish (is my observation).

**Comment by Mike-E-angelo** [comment]
> Hi @Khrin can you explain this, please? 

Maybe @seia-soto can explain what happened here. 🤔

**Comment by Mike-E-angelo** [comment]
Thank you for that @seia-soto it is appreciated. 🙏  Funny enough I removed all my rules in Ghostery and I no longer get nags on USA Today, so I guess everything is as it should be. 😀

**Pull request closed without merging**
