### PR TITLE
A: https://drift.com

### PR DESCRIPTION
**Pull request by chrisxzr**

### CODE REVIEW

**Comment by spirillen** [comment]
**_why_** should `js.` be blacklisted??

**Comment by chrisxzr** [comment]
@spirillen Chatbot-style popup that also blinks "New Messages!" in the page/tab/window title.

**Comment by Khrin** [comment]
Not for the Annoyances list.

**Comment by chrisxzr** [comment]
@Khrin What would this be considered then?

**Comment by spirillen** [comment]
@chrisxzr 

I would recommend you to add the rules, or actually rather update all the rules in the `easyprivacy/easyprivacy_thirdparty.txt` from:

```css
easylist$ git grep 'drift.com'
easyprivacy/easyprivacy_thirdparty.txt:||drift.com/impressions/
easyprivacy/easyprivacy_thirdparty.txt:||drift.com/targeting/
easyprivacy/easyprivacy_thirdparty.txt:||drift.com/track
easyprivacy/easyprivacy_thirdparty.txt:||event.api.drift.com^
easyprivacy/easyprivacy_thirdparty.txt:||metrics.api.drift.com^
```
To:

```css
easyprivacy/easyprivacy_thirdparty.txt:||drift.com^$3p
```

simply because the entire [domain](https://mypdns.org/my-privacy-dns/matrix/-/issues/3239) is also used for adware/(tracking|spying)

But since that might not be accepted, you could make an alternative PR, where you only append the `||js.driftt.com^$3p` to the adware list.

**Pull request closed without merging**
