### PR TITLE
P: https://radiko.jp/ (fixes https://github.com/AdguardTeam/AdguardFilters/issues/83956 )

### PR DESCRIPTION
**Pull request by hirorpt**
### List the website(s) you're having issues:
1. `https://radiko.jp/` (PC)
2. `https://radiko.jp/mobile/trial/` (Mobile)

### What happens?
1. Can't click "Accept the terms of use".
2. See https://github.com/AdguardTeam/AdguardFilters/issues/83956

### Screenshot
<details>
<summary>Screenshot</summary>

Screenshot
</details>

### CODE REVIEW

**Comment by spirillen** [comment]
I have another suggestion, if you would like to try it.

```perl
radiko.jp##.policy
```

```shell
$ dig +short googletagmanager.com @192.168.0.5
192.168.0.5
$ dig +short googletagmanager.com @192.168.0.53
192.168.0.5
```

It seems to work for me, rather than having ti whitelist badware

**Comment by hirorpt** [comment]
@spirillen 
Another issue remains.  https://github.com/AdguardTeam/AdguardFilters/issues/83956

**Comment by spirillen** [comment]
I don't see the error with the rule applied, since `https://radiko.jp/mobile/trial/` redirects to `https://radiko.jp/#!/out`

But again, it's only from a visual point as I have no clue about what the site says.

image

**Comment by hirorpt** [comment]
@spirillen 
Please test on Chrome for Andriod using real devices. I remember it didn't reproduced on Firefox for Android.

**Comment by spirillen** [comment]
> @spirillen
> Please test on Chronium-based browsers using real mobile devices. I remember it didn't reproduced on Firefox for Android.

I can't... No G access here and no :robot: devices with internet access, they are all on a very closely locked subnet

**Pull request merged**
