### PR TITLE
P: https://jmap.io/jmap-demo-webmail/ (fixes AdguardTeam/AdguardFilte…

### PR DESCRIPTION
**Pull request by hirorpt**
…rs#92873)
https://github.com/AdguardTeam/AdguardFilters/issues/92873

### CODE REVIEW

**Comment by ryanbr** [comment]
Paste the full url being fixed @hirorpt

**Comment by hirorpt** [comment]
`https://jmap.io/jmap-demo-webmail/`
<details><summary>Logger output</summary>

| | Filter/rule | Action taken | Context | Partyness |Type | Address of the resource on which filter was applied |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 | `/overture.$script,domain=~overture.doremus.org\|~overture.london\|~overture.plus` | -- | jmap.io | 1 | script | `https://jmap.io/jmap-demo-webmail/libs/Overture.js` |
</details>

**Comment by Yuki2718** [comment]
If I understand correctly, in this case `domain=~` will be preferred.

**Comment by ryanbr** [comment]
Include `$~third-party`

**Pull request merged**
