### PR TITLE
added bank of america adx for whitelist

### PR DESCRIPTION
**Pull request by jwin4740**
I work with ssb511 at bankofamerica and have been in contact with @Khrin .
We would like you to accept this pull request which is adds a generic filter to your whitelist.txt.

### CODE REVIEW

**Comment by ryanbr** [comment]
How does the existing whitelist fail?

**Comment by ssb511** [comment]
The one added by Khrin only works for loan page but not for make payment pages. We need to remove that and add much generic one. We need to remove my communications and also remove secure and make it generic to work for all bankofamerica URLs

**Comment by ssb511** [comment]
Here is whitelist we need to add
@@||bankofamerica.com^*?adx=$~third-party,xmlhttprequest

**Comment by ryanbr** [comment]
The main issue. we ask for a full url you're trying fix. We fix it. Then tell us it doesn't cover others.. So without example urls you're not helping your self. If there is no more constructive movement I'll be closing this pull request.

**Comment by ssb511** [comment]
@ryanbr 
here is another URL that is getting blocked
https://secure.bankofamerica.com/mypayments/widget/billpay-widget-card.go?adx=c10dd971dba4e2ac1c7d0f78d0c8189d74b78e5ffa559e869693b07376143fb0&eBillAvailable=false&source=summary&divId=widget-success&isWidget=true&request_locale=en-US&deviceId=Desktop&pageLocation=&callback=jQuery33103693945204460667_1567419439160&_=1567419439161
will try to get few more URLs.

**Comment by ssb511** [comment]
https://secure.bankofamerica.com/myaccounts/details/deposit/information-services.go?adx=xyz123456xyz123456xyz123456xyz123456xyz123456xyz123456
https://secure.bankofamerica.com/transfers/balgen/offers-transaction-history.go?adx=xyz123456xyz123456xyz123456xyz123456xyz123456xyz123456

**Comment by ssb511** [comment]
hello @ryanbr 
we have provided the URLs that you  asked for. Please let  us know if you need any thing else.

**Comment by ssb511** [comment]
@ryanbr,
Any update on fixing the URLs provided?

**Comment by Khrin** [comment]
The filter has been added two days ago. https://github.com/easylist/easylist/commit/3dc7df2252e1856ea9ad5c4e58c0e63394280598

**Comment by jwin4740** [comment]
Hello Khrin, we verified on our side and the fix seems to be working!!!
Thanks for your help.

**Pull request closed without merging**
