### PR TITLE
A: https://post.tv-asahi.co.jp/post-128983/ anti right-click, copy

### PR DESCRIPTION
**Pull request by Yuki2718**
Right-click, copy, drag etc disabled.

### CODE REVIEW

**Comment by ryanbr** [comment]
`||tv-asahi.co.jp/wp-content/themes/favclip-master/js/front.js`

Would be a better filter, if that is what you're aiming

**Comment by Yuki2718** [comment]
@ryanbr  Can you please add the rule on your side? Since mine is days old, fixing it on my end would cause conflict.

**Comment by spirillen** [comment]
Just a thought :thought_balloon: 

Wouldn't it be better to make it a more global rules as

```
/wp-content/themes/favclip-master/js/front.js
```

To prevent it from all similar sites (themes)?

**Comment by ryanbr** [comment]
Sure, okay.

**Pull request closed without merging**
