### PR TITLE
Update onetrust sdk exceptions

### PR DESCRIPTION
**Pull request by wavygecko**
This PR updates the list of sites for `#onetrust-banner-sdk` and `#onetrust-consent-sdk` exceptions.

### CODE REVIEW

**Comment by wavygecko** [comment]
@ryanbr added all Gamer Network sites that use OneTrust:

```
cosplaycentral.com
dicebreaker.com
digitalfoundry.net
eurogamer.cz
eurogamer.es
eurogamer.net
eurogamer.nl
eurogamer.pl
eurogamer.pt
gamesindustry.biz
jelly.deals
rockpapershotgun.com
thehaul.com
thepopverse.com
vg247.com
```

**Comment by ryanbr** [comment]
Whats removed and why?

**Comment by wavygecko** [comment]
@ryanbr I replaced `usgamer.net` because it redirects to `vg247.com` now. The other commit that says `Remove unnecessary eurogamer.de exception` was added by me in error (the .de site doesn't use OneTrust)

**Comment by ryanbr** [comment]
The rest? With such a large change it should be stated for each domain (add or removed) on why.

**Comment by wavygecko** [comment]
@ryanbr sorry, I'll make it clearer next time and/or do smaller changes. I made a diff check with each domain on its own line so it is easier to see: https://www.diffchecker.com/0NXNSTcg/
Besides adding the Gamer Network sites, the only other change I forgot was that I added matching `costco.com` and `panasonic.com` to `#onetrust-banner-sdk` rule that were already in the `#onetrust-consent-sdk` rule

**Pull request merged**
