### PR TITLE
Attempted fix for #5065 — Pornhub/Facebook

### PR DESCRIPTION
**Pull request by DandelionSprout**
I figured that I could just as well be the one who'd take care of #5065, which I've tried to do now.

I also did additional improvement of a select few `Facebook` entries.

### CODE REVIEW

**Comment by Khrin** [comment]
Filters like these cannot be accepted, because could be easily hijacked and needs to be made domain-specific. 
```
@@||pornhub.*/favicon.ico$image,domain=pornhub.etc
@@||help.pornhub.*^$domain=help.pornhub.etc
@@||cdn-*.pornhub.*^$image,domain=etc
@@||feedback.pornhub.*^$xmlhttprequest,domain=feedback.pornhub.etc
@@||img.pornhub.*/gif/*.gif|$image,~third-party
@@||pornhub.*/_Incapsula_Resource?$image,subdocument,xmlhttprequest
@@||pornhub.*/album/$xmlhttprequest
@@||pornhub.*/album_upload$xmlhttprequest
@@||pornhub.*/channel/$xmlhttprequest
@@||pornhub.*/chat/$xmlhttprequest
@@||pornhub.*/comment/$xmlhttprequest
@@||pornhub.*/community_ajax?$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/event/awards_vote$xmlhttprequest
@@||pornhub.*/front/$xmlhttprequest
@@||pornhub.*/gif/$xmlhttprequest
@@||pornhub.*/insights/$image,xmlhttprequest
@@||pornhub.*/jobs/?wc-ajax=$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/jobs/wp-content/$image,domain=pornhub.etc
@@||pornhub.*/live/$xmlhttprequest
@@||pornhub.*/newCreditCardModalDataTrackingAjax$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/oauth2/authorize?$popup
@@||pornhub.*/playlist/$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/playlist_json/$xmlhttprequest
@@||pornhub.*/pornstar/$xmlhttprequest
@@||pornhub.*/pornstars/$xmlhttprequest
@@||pornhub.*/premium/$xmlhttprequest
@@||pornhub.*/press/contact$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/recommended$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/sex/wp-content/uploads/$image,domain=pornhub.etc
@@||pornhub.*/stream/$xmlhttprequest
@@||pornhub.*/svvt/add?$xmlhttprequest
@@||pornhub.*/toys/?$xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/toys/wp-content/$image,script,xmlhttprequest,domain=pornhub.etc
@@||pornhub.*/upload/$xmlhttprequest
@@||pornhub.*/uploading/$xmlhttprequest
@@||pornhub.*/user/$xmlhttprequest
@@||pornhub.*/users/$xmlhttprequest
@@||pornhub.*/video/$xmlhttprequest
@@||pornhub.*/videos/$media,object,other
@@||pornhub.*/videouploading3/$xmlhttprequest
@@||pornhub.*/www-static/flash/gate.swf$object,other
@@||pornhub.*/www-static/images/$image
```

**Comment by DandelionSprout** [comment]
I've attempted to correct your concerns now.

I was unsure what the EasyList team's officially recommended approach to fixing these situations are, so I presumed that dividing them into 3 specific entries each would be preferable compared to using RegEx.

**Comment by llacb47** [comment]
why not add domain restrictions for all the whitelists, something like `@@||pornhub.*/svvt/add?$xmlhttprequest,domain=pornhub.com|pornhub.org|pornhub.net|pornhubthbh7ap3u.onion`

**Comment by DandelionSprout** [comment]
I had a lot of options to choose from, so I presumed that Khrin's primary fear was that someone would register some wildly fraudulent domain like `pornhub.ooo` and use it to spam virus ads on `Pornhub`.

**Comment by ryanbr** [comment]
`@@||pornhub.*` is open to abuse. not the first time pornhub used a whitelist like that.

**Comment by ryanbr** [comment]
Closing. no further changes made

**Comment by DandelionSprout** [comment]
I didn't know I had to do any further changes, let alone which ones... 😐

**Pull request closed without merging**
