### PR TITLE
A: `soap2day.cc`

### PR DESCRIPTION
**Pull request by eporubin**
Please add the domain to the existing filter it has popping ads on click in another tab. 
Thank you

### CODE REVIEW

**Comment by ryanbr** [comment]
Can't simply block the source domain, it'll cause false positives.  @eporubin

**Comment by eporubin** [comment]
Hi, @ryanbr  thank you for looking into it, please take in consideration that this domain `soap2day` has been reported by user several times already and the other domains endings such as `soap2day.ac` and `soap2day.sh` are already in the list and therefore I added the `soap2day.cc` on which our latest complain is. I understand your concern towards the actual domain/adverser but this domains change frequently their ads sources.

**Comment by eporubin** [comment]
Hi, Could I please get an explanation why all the soap2day domains were just removed? we get constant complains from users about this website and from what we experienced over the times its always popping in another tab with ads. And as I was saying tracking down the source domain wont help much they change them frequently and thats min 4 domain. If you came across false positives please exemplify. Thank you 🙏

**Comment by ryanbr** [comment]
Point, removed related filters.

**Pull request closed without merging**
