### PR TITLE
M: merging together privacy-mgmt.com stuff

### PR DESCRIPTION
**Pull request by peace2000**
All these rules are relating to the same script. So they can be merged.

`wrapperMessagingWithoutDetection.js` is a script that originates from `privacy-mgmt.com`. (Though sometimes that script is loaded from different domains, it's not always loaded from `privacy-mgmt.com`.

Samples (sites that load it from a different domain):
http://planetgameboy.de/
https://www.cio.com/

In addition to merging, I also changed the rule a bit:
`/wrapperMessagingWithoutDetection.js`
->
`/wrapperMessagingWithoutDetection*.js`
because some domains might use version numbers with that script, such as: https://www.wsj.com/

I also fixed a typo introduced in this commit:

https://github.com/easylist/easylist/commit/8c04ca11b37e8f66df544082bde36bf75be7a8b0 <details>
kuva
</details>

In my commit, I also sorted the domains in alphabetical order and removed duplicates.

### CODE REVIEW

**Comment by ryanbr** [comment]
https://www.idealo.co.uk/ & https://www.wsj.com  aren't covered by wrapperMessaging. need to check before making one rule to rule them all @peace2000

**Comment by peace2000** [comment]
@ryanbr For me, those sites do use it.

https://www.idealo.co.uk/
kuva

https://www.wsj.com/
kuva

**Comment by Khrin** [comment]
I think it's really fine for the moment.

**Comment by peace2000** [comment]
@Khrin What's the point of having multiple locations in lists for the same script?

Also, at least remove this typo:

https://github.com/easylist/easylist/commit/8c04ca11b37e8f66df544082bde36bf75be7a8b0

kuva

**Pull request closed without merging**
