### PR TITLE
A: finance.yahoo.com

### PR DESCRIPTION
**Pull request by llacb47**
I have no idea how this list is supposed to be organized so if this is wrong feel free to move it.

image

```
<div id="YDC-Overlay" class="YDC-Overlay" data-reactid="53">
	<div id="YDC-Overlay-Stack" class="YDC-Overlay-Stack Z(11) End(0) Pos(f) Start(0) lw-nav-open_Pos(r) lw-nav-open_Z(10) T(0)" data-reactid="54">
		<div id="YDC-Overlay-Stack-Composite" data-reactid="55">
			<div data-reactid="56">
				<div id="mrt-node-Overlay-0-Lightbox" data-locator="subtree-root">
					<div id="Overlay-0-Lightbox-Proxy" data-reactroot="" data-reactid="1" data-react-checksum="-1142446977">
						<div id="Overlay-0-Lightbox" class="lightbox" data-reactid="2">
							<div tabindex="-1" class="lightbox-wrapper Ta(c) Pos(f) T(0) Start(0) H(100%) W(100%)  D(n)! Op(0)" data-reactid="3">
								<div id="myLightboxContainer" class="Ta(start) Pos(r) Z(1) T(0) Maw(100%) P(0)  D(n)!" aria-describedby="lightbox-container" role="alertdialog" data-reactid="4"></div><b class="ModalShim" data-reactid="5"></b><b class="IEShim" data-reactid="6"></b></div>
						</div>
					</div>
				</div>
				<script>
				if(window.performance) {
					window.performance.mark && window.performance.mark('Overlay-0-Lightbox');
					window.performance.measure && window.performance.measure('Overlay-0-LightboxDone', 'PageStart', 'Overlay-0-Lightbox');
				}
				</script>
			</div>
			<div data-reactid="57">
				<div id="mrt-node-Overlay-1-Null" data-locator="subtree-root">
					<div id="Overlay-1-Null-Proxy" data-reactroot="" data-reactid="1" data-react-checksum="-1353506498">
						<div data-reactid="2"></div>
					</div>
				</div>
				<script>
				if(window.performance) {
					window.performance.mark && window.performance.mark('Overlay-1-Null');
					window.performance.measure && window.performance.measure('Overlay-1-NullDone', 'PageStart', 'Overlay-1-Null');
				}
				</script>
			</div>
			<div data-reactid="58">
				<div id="mrt-node-Overlay-2-NavFeatureCue" data-locator="subtree-root">
					<div id="Overlay-2-NavFeatureCue-Proxy" data-reactroot="" data-reactid="1" data-react-checksum="-1295048054"></div>
				</div>
				<script>
				if(window.performance) {
					window.performance.mark && window.performance.mark('Overlay-2-NavFeatureCue');
					window.performance.measure && window.performance.measure('Overlay-2-NavFeatureCueDone', 'PageStart', 'Overlay-2-NavFeatureCue');
				}
				</script>
			</div>
			<div data-reactid="59">
				<div id="mrt-node-Overlay-3-PremiumPromoFooter" data-locator="subtree-root">
					<div id="Overlay-3-PremiumPromoFooter-Proxy" data-reactroot="" data-reactid="1" data-react-checksum="216951578">
						<section class="Pos(f) Z(2) Start(0) End(0) Mx(a) Bdrststart(4px) Bdrstend(4px) H(100px) B(0px) Trsdu(0.3s) Trsp(bottom) D(n)--print" data-reactid="2">
							<div class="Pos(r) Maw($newGridWidth) M(a) Ta(c) W(833px)" data-reactid="3">
								<a class="Pos(r) H(100px) Bgpx(c) Bgr(nr) D(b) Bgz(a) Bgi($premiumMarketingBannerv2)" href="https://ad.doubleclick.net/ddm/trackclk/N360801.1913355YAHOOADMANAGER/B23703422.266351943;dc_trk_aid=460589216;dc_trk_cid=127471001;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=" data-reactid="4"></a>
								<button class="Pos(a) T(0) End(0) H(20px) W(20px) P(0)" data-reactid="5">
									<svg class="H(20px) W(20px) Fill(white)! Stk(white)! Cur(p)" width="20" style="fill:#000;stroke:#000;stroke-width:0;vertical-align:bottom;" height="20" viewBox="0 0 48 48" data-icon="close" data-reactid="6">
										<path d="M37.98 34.827l-9.9-9.9 9.9-9.898c.78-.782.78-2.05 0-2.83-.78-.78-2.047-.78-2.828 0l-9.9 9.9-9.898-9.9c-.78-.78-2.048-.78-2.828 0-.78.78-.78 2.047 0 2.828l9.9 9.9-9.9 9.898c-.78.78-.78 2.047 0 2.828.78.78 2.047.78 2.828 0l9.9-9.9 9.898 9.9c.78.78 2.048.78 2.828 0 .782-.78.782-2.047 0-2.827z" data-reactid="7"></path>
									</svg>
								</button>
							</div>
						</section>
					</div>
				</div>
				<script>
				if(window.performance) {
					window.performance.mark && window.performance.mark('Overlay-3-PremiumPromoFooter');
					window.performance.measure && window.performance.measure('Overlay-3-PremiumPromoFooterDone', 'PageStart', 'Overlay-3-PremiumPromoFooter');
				}
				</script>
			</div>
		</div>
	</div>
</div>
```

### CODE REVIEW

**Comment by Yuki2718** [comment]
> I have no idea how this list is supposed to be organized so if this is wrong feel free to move it.
> 

Probably ordered by ASCII code of the selector.

**Comment by Khrin** [comment]
I can't see this banner, but for what I see in the screenshot it shouldn't be listed in EasyList, being some kind of self-promotion?

**Comment by llacb47** [comment]
The destination URL links to doubleclick, making it a bit more evil than a normal self promo banner. If that's not a good reason to block then I will close.

**Comment by Khrin** [comment]
Generally it isn't for us, we have added whitelists for similar cases.

**Comment by llacb47** [comment]
Ok.

**Comment by Yuki2718** [comment]
Even for Fanboy Annoyances? @llacb47 Maybe that's worth PR to uAssets?

**Comment by Khrin** [comment]
That's right, looks all fine for the Fanboy's Annoyances list: https://github.com/easylist/easylist/commit/d58cbafe118b803a3e1d32220774f48a0d1e3594

**Pull request closed without merging**
