### PR TITLE
address huya.com tracking

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
https://github.com/uBlockOrigin/uAssets/pull/10610

### CODE REVIEW

**Comment by Khrin** [comment]
Why do many users in this discussion seem to be suggesting that the rules should actually be badfiltered?

@Yuki2718 @piquark6046 do you both know the site? thoughts on it?

**Comment by Yuki2718** [comment]
I don't, but it looks two user experienced loading issue which OP couldn't reproduce.

**Comment by JobcenterTycoon** [comment]
But only with `||p2p.huya.com^`? The filter is disabled at the moment.

**Comment by Yuki2718** [comment]
Oh, right.

**Comment by Yuki2718** [comment]
But it is classified as resource-abuse, so maybe more suited to easyprivacy_trackingservers_mining.txt though are not exactly miner.

**Comment by Khrin** [comment]
> But it is classified as resource-abuse, so maybe more suited to easyprivacy_trackingservers_mining.txt though are not exactly miner.

Yes, it is definitely out of the scope of the list.

**Comment by Khrin** [comment]
Also, I have never seen an instance of `||e-stat.huya.com^`, so I think it can be closed.

**Pull request closed without merging**
