### PR TITLE
 A: pull_request_template.md

### PR DESCRIPTION
**Pull request by krystian3w**
Add comment to all feature pull request with instruction what the letters mean.

```html
<!--
https://forums.lanik.us/viewtopic.php?p=131958#p131958

A: (as Addition) : means that a filter to block an advertisement has been added
P: (as Problem) : means that a problem has been fixed, for example by adding an exception in the case of a video that does not start, or in the case of an anti-adblock.
M: (as Moved or Modified) : means that a filter has been moved, added or deleted without being linked to a particular URL. This initial does not need to be followed by a URL.
--> 
```

### CODE REVIEW

**Comment by peace2000** [comment]
Good idea!

**Comment by krystian3w** [comment]
But ignored

**Comment by spirillen** [comment]
Hey @krystian3w 

May I suggest you add a short description on what ech file covers within the `easylist*/` folders, could be a super "remeberroll" when you are not a fulltime easylist reader/constributer

**Comment by krystian3w** [comment]
Honestly, they won't want such PR at all then.

Besides, I don't always find myself in which file to paste something because of collecting some filter groups into a small "regional" file.

Przechwytywanie |
--- |

**Comment by spirillen** [comment]
Yeah it's a shame they have turned down the suggestion of a `README.md` file in the past :cry: but let's see if they will like it this time, so everybody who think this is a good idea, give a feedback, comment or emojis....

**Comment by peace2000** [comment]
@Khrin Why not to add these explanations? New users users who are not aware of these would definetely benefit.

**Pull request closed without merging**
