### PR TITLE
A: https://vip7stream.pw/bc0069a07bf78daa34378fca6f0f3f59-live.html

### PR DESCRIPTION
**Pull request by smed79**
https://i.imgur.com/br8gKr4.png
https://forums.lanik.us/viewtopic.php?p=145348#p145348

### CODE REVIEW

**Comment by peace2000** [comment]
https://vip7stream.pw/ cannot be accessed.

**Comment by peace2000** [comment]
`adbetnet.com` is blocked already.

**Comment by smed79** [comment]
> adbetnet.com is blocked already.

no the popup !!

**Comment by peace2000** [comment]
||adbetnet.com^$third-party

Doesn't that block popups as well?

**Comment by Khrin** [comment]
@peace2000 Not for ABP.

**Comment by peace2000** [comment]
Oh, well that´s a flaw then.

**Comment by Khrin** [comment]
I don't think that should be intended as a flaw, but as a way to differentiate newly opened pages (`$popup`) and regular pages (`$document`), so a different approach as that used by Ublock Origin.

**Pull request merged**
