### PR TITLE
A: terveystalo.com

### PR DESCRIPTION
**Pull request by peace2000**
Cookie banner hide & block filters for https://www.terveystalo.com/. Note: I also rearranged Finnish addresses in the hiding list in alphabetical order.

I was at first about to make that network filter general, but it's not in use in any other domains so a specific rule is enough.

https://publicwww.com/websites/%22analytics-consent-manager.azureedge.net%22/

### CODE REVIEW

**Comment by Khrin** [comment]
We already sort rules by alphabetical order, but starting by filter's name, not by its domain.

**Comment by peace2000** [comment]
Oh. Well then I'll revert that...

**Comment by peace2000** [comment]
They are ok now. Also fixed one entry that was not alphabetically.

**Comment by peace2000** [comment]
They are ok now. Also fixed one entry that was not in correct order.

**Comment by Khrin** [comment]
Filters were already listed in correct order.

**Comment by peace2000** [comment]
@Khrin 
```

satakunnanautotalo.fi##.AVS-evasteseloste-container
kulttuurivihkot.fi##.activebar-container
americanairlines.fi##.alert
```

->

##.AVS-evasteseloste-container
##.activebar-container
##.alert

c and l are before v.

**Comment by peace2000** [comment]
Also `analytics-consent-manager.azureedge.net` doesn't seem to be in large scale use, despite it's general sounding name: https://publicwww.com/websites/%22analytics-consent-manager.azureedge.net%22/

**Pull request closed without merging**
