### PR TITLE
Addition to easylist_whitelist_international.txt

### PR DESCRIPTION
**Pull request by juliosgarbi**
Create exception to load googletagmanager script in www.saraiva.com.br

### CODE REVIEW

**Comment by monzta** [comment]
Why is it necessary?

**Comment by juliosgarbi** [comment]
Saraiva uses googletagmanager to inject the script of our product into your site. When we access Saraiva's website through Firefox with the ublock extension installed googletagmanager is blocked, thus blocking the injection of our script as well.

**Comment by monzta** [comment]
Could you post the URL of the script of your product please?

**Comment by juliosgarbi** [comment]
If you access this url http://saraiva.com.br/travessuras-da-menina-ma-1464513.html you can see our product here: 

our-product

Our product is a social module within Saraiva ecommerce.

The script that is called by GTM is the https://saraiva.more.social/expressions/dist/install.js but as Saraiva uses GTM to manage our script it stops being called when we go through firefox with ublock installed

**Comment by monzta** [comment]
Thanks! But then I would recommend using `saraiva.com.br` instead of `www.saraiva.com.br` in the filter.

**Comment by juliosgarbi** [comment]
Done!

**Pull request merged**
