### PR TITLE
Add api.markitondemand.com to whitelist

### PR DESCRIPTION
**Pull request by Far3**

### CODE REVIEW

**Comment by Khrin** [comment]
Why such a filter should be added? Is this domain incorrectly blocked somewhere?

**Comment by Far3** [comment]
Yes, I have documentation at the following forum post. It is blocking the serving of APIs on that domain. Further documentation below.

https://forums.lanik.us/viewtopic.php?f=64&t=42679

**Comment by Khrin** [comment]
I have removed the filter, and added a more specific one, to block just the tracking service.

**Comment by Far3** [comment]
Thank you very much @Khrin. When does this list get updated to https://easylist.to/easylist/easyprivacy.txt? On Saturday, March 2nd?

**Comment by Khrin** [comment]
Should be already updated. Users should automatically get latest version in a few days, depends by the software.

**Pull request closed without merging**
