### PR TITLE
A: (nsfw) https://hentaifreak.org/tags/dubbed-hentai/ (fixes https://…

### PR DESCRIPTION
**Pull request by Yuki2718**
…github.com/AdguardTeam/AdguardFilters/issues/88941)
https://github.com/AdguardTeam/AdguardFilters/issues/88941

### CODE REVIEW

**Comment by ryanbr** [comment]
`||hentaifreak.org/erogames/`  should be enough @Yuki2718  with the need to unneeded (slow) wildcards

**Comment by Yuki2718** [comment]
@ryanbr Done.

**Comment by ryanbr** [comment]
move `leojmp.com` into adservers.

**Comment by Yuki2718** [comment]
Moved to adult_adservers as it's not a revolving server. Not sure if `$third-party` is required.

**Comment by Khrin** [comment]
Doesn't seems to be needed anymore, I think. (At least on this site)

**Pull request closed without merging**
