### PR TITLE
Block cookie notice / consent manager more specifically

### PR DESCRIPTION
**Pull request by bencmbrook**
Adds some more specificity to this cookie notice rule to prevent breakage of unrelated services and websites. This blocks all functionality related to cookie notices / consent management.

### CODE REVIEW

**Comment by Khrin** [comment]
Any evidence of those "breakage of unrelated services and websites"?

**Comment by bencmbrook** [comment]
Hi @Khrin! Yes, absolutely. 

As one example, if you want to export your account data from MasterClass (**"Download all my data"**) (https://privacy.masterclass.com/policies?modal=take-control), their form submission will be blocked. 

https://github.com/easylist/easylist/assets/7354176/a51b1855-5826-4feb-9b74-8e798657fb47

Since `transcend.io` has a [wide variety of services](https://docs.transcend.io/docs#the-modern-privacy-stack), many websites make network requests to `transcend.io` for reasons unrelated to cookie notices, such as giving users a way to close their accounts.

So the goal of this PR is to be specific enough to block all cookie annoyances without causing breakage to other unrelated services.

Thank you for your consideration!

**Comment by ryanbr** [comment]
There is very little trust from transcend, they don't want to ever be targeted.

**Comment by bencmbrook** [comment]
Hey @ryanbr... I'm confused by that response. This PR preserves Transcend as a target. For context, Transcend helps consumers exercise their "Right to be Forgotten" with businesses. Consumers using EasyList are not able to exercise that right, because the entire domain name is blocked. 

Separately, Transcend has a cookie management product (at `cdn.transcend.io/cm/*/ui.js`), which does indeed meet the criteria for this list.

cc @Khrin, I think this is accurately represented in my prior comment...

**Comment by bencmbrook** [comment]
@ryanbr @Khrin bumping this thread. This is still breaking production services and preventing any EasyList users from deleting their data from businesses.

**Comment by ryanbr** [comment]
Its an optional list. and we block other consent managers, Transcend is no different. "cdn.transcend.io/cm/*/ui.js" isn't enough.

**Comment by bencmbrook** [comment]
Hi @ryanbr, thank you for your response.

> Transcend is treated no differently to the other consent managers we target: https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_thirdparty.txt

My ask is that Transcend is **treated with the same specificity as other consent managers**, e.g.:

https://github.com/easylist/easylist/blob/cc917d0d907ef683973700dd5906a0bf5982e92d/easylist_cookie/easylist_cookie_thirdparty.txt#L108

https://github.com/easylist/easylist/blob/cc917d0d907ef683973700dd5906a0bf5982e92d/easylist_cookie/easylist_cookie_thirdparty.txt#L34-L35

https://github.com/easylist/easylist/blob/cc917d0d907ef683973700dd5906a0bf5982e92d/easylist_cookie/easylist_cookie_thirdparty.txt#L120

https://github.com/easylist/easylist/blob/cc917d0d907ef683973700dd5906a0bf5982e92d/easylist_cookie/easylist_cookie_thirdparty.txt#L17

I am 100% aligned to blocking the consent manager. My request is to block it, but not our _entire domain_ which is used for many other things and causes bugs in unrelated services.

Here are the rules I'm suggesting to be more specific:
1. `cdn.transcend.io/cm/*/ui.js` — If I understand the goal of EasyList Cookie correctly, it's to remove popups, banners, and annoyances—this is achieved by this rule as the UI is entirely encapsulated in `cdn.transcend.io/cm/*/ui.js`. 

2. `cdn.transcend.io/cm/*` (note: `cm` stands for "Consent Manager") — If the goal of EasyList Cookie is to block the software _altogether_, then `cdn.transcend.io/cm/*` should be included. FWIW, `airgap.js` is totally headless; it's the piece that blocks trackers on websites (much like EasyList Privacy!) and listens for browser signal opt-outs, like [navigator.globalPrivacyControl](https://globalprivacycontrol.org/).

Please let me know if I can reopen a PR with one of these options. I'd really appreciate your response.

**Comment by ryanbr** [comment]
Yet we have't seen a use case for the end user where its "needed" for the enduser. 

We're not planning to change the filter.

**Comment by bencmbrook** [comment]
@ryanbr are you open to understanding these use-cases?

Here's another important use case: `cdn.transcend.io/cm/*/airgap.js` is a piece of technology which listens for the Global Privacy Control opt-out signal, [a browser signal Brave helped create and has enabled on every website](https://brave.com/web-standards-at-brave/4-global-privacy-control/). When GPC is detected by `airgap.js`, it then blocks trackers on the company website. 

By blocking `airgap.js` itself, Brave is preventing the signal it sends from being received, preventing the user from successfully opting out. Blocking receipt of the GPC signal is bad for the end-user's privacy, and goes against their expectations when they browse the web with it turned on.

Again, `airgap.js` is headless, meaning there would be no cookie banner / annoyances (as `cdn.transcend.io/cm/*/ui.js` would remain blocked). The user would simply be opted-out as they expect and request.

We're being sincere here, and are not trying to evade the principles of EasyList. I understand that this is often the case when a company comes asking for a rule change. Let me know if you want to dive deeper and understand the use-cases.

**Pull request closed without merging**
