### PR TITLE
Allow OpenStreetMap.org events self-promotion

### PR DESCRIPTION
**Pull request by Firefishy**
PR to remove OpenStreetMap.org which was added in b5c76ea17e12b95c711ce512c2389795fc853bd0

OpenStreetMap.org's banner for announcing our own community conferences and events. This isn't a banner for advertising 3rd party things.

Please don't block our ability to advertise our conferences and our community events on our own site.

### CODE REVIEW

**Comment by timwaters** [comment]
Screenshot of the OpenStreetMap Banner showing a featured community event
 image

**Comment by nsuchy** [comment]
It doesn't matter whether it's advertising something third party or not, in the end it's still an advertisement and subject to blocking. That banner above looks so spammy to me (just my opinion though).

**Comment by RobJN** [comment]
People use OpenStreetMap.org because it's a community portal so they want to see notices of community events.

If all you want is a map based on OpenStreetMap data then openstreetmap.org is not necessarily the place to go.

As a community website I agree with Grant that these event notices shouldn't be blocked. If a user clicks the cross to dismiss this choice is remembered.

**Comment by Firefishy** [comment]
@nsuchy If you don't like the banner, how about a PR? https://github.com/openstreetmap/openstreetmap-website/commit/738e1e9cc60d3d5987acdaf851466961d0f9d437#diff-e34aeecdd8dcbcb2c7ceae5c472cc7f7

**Comment by Firefishy** [comment]
[Here a link to the discussion when this came up last time](https://forums.lanik.us/viewtopic.php?f=62&t=33603).

[Easylist policy](https://easylist.to/pages/policy.html):
> Self-promotion should not be specifically removed by EasyList, although equally should not be whitelisted if it is blocked.

**Comment by nsuchy** [comment]
The last part "although equally should not be whitelisted if it is blocked." if easylist is blocking your promotion, it shouldn't be whitelisted. As I replied to your tweet, I'm not involved with graphic design so that'll be a no on a logo, I also despise advertising (goes back to promotion is still advertising - something most easylist users want blocked) - if users want to see your event notices that badly they can disable their adblocker on your website.

**Comment by Firefishy** [comment]
This PR does not change any of EasyList's whitelists, it just reverts https://github.com/easylist/easylist/commit/b5c76ea17e12b95c711ce512c2389795fc853bd0 which was added a few days ago.

**Comment by nsuchy** [comment]
screen shot 2018-02-11 at 8 29 10 pm
This is the user who made that PR. I think as long as he's been contributing, he thinks this complies with easylist polices. Let's ask @ryanbr since he made the commit: Ryan am I wrong in saying an ad banner promoting something on your own website is still an advertisement blockable by easylist?

**Comment by ryanbr** [comment]
we are only human, but I'll review it later today

**Comment by ryanbr** [comment]
Sure its related content, but not technically a self-promo, Its linking to 3rd party sites, as a banner. 

https://fossgis-konferenz.de/2018/
http://foss4g-it2018.gfoss.it/

**Comment by kachkaev** [comment]
But will it technically become a self-promo if the links are changed to these?

https://www.openstreetmap.org/go/https://fossgis-konferenz.de/2018/

https://www.openstreetmap.org/go/http://foss4g-it2018.gfoss.it/

:–)

I’m a by-passer here, but I’d say I agree with @Firefishy. Semantically, the banner is a self-promotion and to me this is the key point here.

**Comment by ryanbr** [comment]
Hiding a URL behind a redirect, doesn't make it right. If we allowed this, then other sites would suddenly argue the same thing.

Related content != Self promotion
First party hosted = Self promotion.

I hope that clarifies this.

**Comment by kachkaev** [comment]
I’m still not sure what the definition of ‘self’ is. If it’s not the community in the case of OSM, then what?

The conferences are organised by the same people that develop osm.org and fill it with data. Yes, these people don’t wear the same company’s badges and may use different logos, but that does not make them different `selves‘ IMHO.

**Comment by tomhughes** [comment]
Specifically the only people that get banners there are the OpenStreetMap Foundation and affiliated local chapters of the foundation.

**Comment by ryanbr** [comment]
Not sure how this can be argued. there isn't really any Shades of Grey;

```
Related content != Self promotion
First party hosted = Self promotion.
```

I acknowledge the ads used on OpenStreetMap aren't offensive, or overbearing; I would recommend [submitting the site to the Acceptable Ads](https://adblockplus.org/forum/)  which I would see no issues it being added here.

I'm not going to drag this out any further, unless there is something new. I'll close this ticket.

**Comment by Zverik** [comment]
@ryanbr so links to wikimedia events should be blocked on wikipedia, according to your undocumented policy?

OpenStreetMap is de-centralized worldwide community. We host only vital parts of infrastructure on openstreetmap.org website. The are different domains for different groups: local chapters, community events (often run by State of the Map Working Group of OSM Foundation), helper web services. Are you proposing to move everything map-related in the world to a single domain, just so you could remove the domain from the blocking list?

**Comment by ryanbr** [comment]
If its an Advert for wikipedia it'll be blocked like any other advert. Making exemptions for one site, will open a pandora's box for other sites to do the same. A simple text link would be obviously better, and less intrusive than a 300x300 box.

No matter how you guys spin this, its still an Advert. Given this is going in circles I'm closing this.

**Pull request closed without merging**
