### PR TITLE
A: (nsfw) http://hdreporn.com/videos/17021/valentina-ricci-office-emp…

### PR DESCRIPTION
**Pull request by Yuki2718**
…loyee-needs-help-and-my-big-boobs/ (fixes https://github.com/AdguardTeam/AdguardFilters/issues/72226)
https://github.com/AdguardTeam/AdguardFilters/issues/72226

### CODE REVIEW

**Comment by spirillen** [comment]
There are still pop-under - redirect new tab(window)

**Comment by Yuki2718** [comment]
> There are still pop-under - redirect new tab(window)

@spirillen You mean with my rule? How to reproduce?

**Comment by spirillen** [comment]
> > There are still pop-under - redirect new tab(window)
> 
> @spirillen You mean with my rule? How to reproduce?

My bad.... I forgot to notice it was a PR (read it as issue only), with all my excuses... 

**Note:** Haven't followed up with a seconds test

**Comment by Yuki2718** [comment]
Temporary added to uBlock filters: https://github.com/uBlockOrigin/uAssets/commit/7874189a13fc669c1d09cd810ae311477afed04f

**Pull request closed without merging**
