### PR TITLE
A: [NSFW] https://myreadingmanga.info/

### PR DESCRIPTION
**Pull request by felippesantos46**
Hide banner at https://myreadingmanga.info/

Screenshots: 
Screenshot 2021-12-17 at 11 40 46

### CODE REVIEW

**Review by spirillen — APPROVED** [review]
There are more to block, but this rule does what it promise

image

**Comment by felippesantos46** [comment]
Hey @spirillen how you doing ? 
So it could be ##center, or to not be so generic ##center[style*="width: 300px; height: 250px;"], what do you think ?

**Comment by spirillen** [comment]
Hey @felippesantos46, let's admit it, been better (Missing my kids in the Christmas :sob:) and you, heads up - feeds up?

I love broad rules :smiley: Personally I would chose the `##center` as I already have that one, but ryan + khrin probably prefer the `##center[style*="width: 300px; height: 250px;"]`

**Comment by felippesantos46** [comment]
> Hey @felippesantos46, let's admit it, been better (Missing my kids in the Christmas 😭) and you, heads up - feeds up?

Sorry to hear that, for me it's the opposite, my parents live far away. Overall good, looking forward to developing my skills for the next year (within web dev). I believe we will have more reviews before Christmas, but i wish you all the best!

**Pull request closed without merging**
