### PR TITLE
A: https://readcomicsonline.ru

### PR DESCRIPTION
**Pull request by felippesantos46**
Filters for blocking scripts and subdocument related to ads at [readcomicsonline](https://readcomicsonline.ru/comic/inferno-2021/1/3)

Proposed blocking filters: 
Placeholders in all subpages and main page: `||windsplay.com$script`
Referrals after clicking the comics to pass the page: `||everalwerf.xyz^`

How to reproduce the referral: Go to [comics](https://readcomicsonline.ru/comic/sword-2020/8) and click above the cartoon or try to click at "home" button at the header.

Screenshot of placeholders + script:
Screenshot 2021-09-30 at 10 20 52

### CODE REVIEW

**Comment by spirillen** [comment]
I don't see any of this within FF

**Comment by felippesantos46** [comment]
Hey @spirillen, 

True that, on FF you cannot reproduce the referals, on the other hand it's possible to see the placeholders:
Screenshot 2021-09-30 at 13 35 57

On the other hand after testing at Chrome and Opera, we can see the following: https://vimeo.com/619103729/c55f6d4dcf

**Comment by spirillen** [comment]
Hmm have you updated your filters?? or is I just so lucky that some of the rules I import in https://mypdns.org/my-external-stuff/ublockorigin-rules/-/blob/master/ublockorigin-rules.template have this fixed??

<details><summary>With the above rule</summary>

image

</details>

<details><summary>Without them</summary>

image

</details>

I'm sorry I can't reproduce this, maybe some of the lists members can and confirm your contribution. I can see the issue from your end through your video. but try updating the filters and go again.

**Comment by felippesantos46** [comment]
I believe you are the lucky one or maybe i'm the unlucky one 😂 !

No worries at all, I already updated my filters but it's still showing up to me, so maybe the other members can verify.

Thank you for checking on your side !

**Comment by Khrin** [comment]
@felippesantos46 i think that both can be added to the adservers list, among the others with random names, just below line 1: https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt (without the script tag for windsplay)

**Comment by felippesantos46** [comment]
@Khrin Done as requested. Thank you for the tips !

**Pull request merged**
