### PR TITLE
searchenginejournal.com

### PR DESCRIPTION
**Pull request by mediumkreation**
**Found in URL:** https://www.searchenginejournal.com/
searchenginejournal com_18-04-08 20 44 00

**Found in URL:** https://www.searchenginejournal.com/pr-seo-ways-get-coverage/246037/
searchenginejournal com_18-04-08 20 47 34

**Found in URL:** https://www.searchenginejournal.com/pr-seo-ways-get-coverage/246037/
searchenginejournal com_18-05-23 23 38 03 png_18-06-30 21 18 55

### CODE REVIEW

**Comment by smed79** [comment]
@mediumkreation You filters are not written correctly and are not in the right place (files), so please instead of the pull requests (noise), just open issues. 

https://github.com/easylist/easylist/issues/
https://forums.lanik.us/viewforum.php?f=62

**Comment by mediumkreation** [comment]
@smed79 , can you help me figure what need to be changed/improved ? I was creating pull requests as suggested by @monzta .

**Comment by smed79** [comment]
> can you help me figure what need to be changed/improved

Did you see https://github.com/mediumkreation/IndianList/issues/2 ?

**Comment by mediumkreation** [comment]
@smed79  thanks, for sharing the details, I just checked it and it was really informative.

I think , I only missed the convention for title / comment for the PR/commit (i.e. A: / M: / P:) :(
Just came to know about this after reading your links. I will follow it going forward.

You also mentioned "Filters are not written correctly and are not in the right place (files)"
can you help me understand what exactly I missed/misinterpreted ?  
and secondly the file location decision... do we have any documentation for this as well ?

I sincerely, wish to contribute to my fullest and help moderators to get the filter list updated at quickest.

**Comment by monzta** [comment]
@smed79 Could you be specific what isn't correct?

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/a4979d7e49614c2fa2cd3a1b7f325b979cbd09b8

**Pull request closed without merging**
