### PR TITLE
A: https://itsfoss.com/best-email-clients-linux/

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by peace2000** [comment]
Has conflicts now.

**Comment by peace2000** [comment]
Still relevant: https://app.optinmonster.com/login/

kuva

**Comment by peace2000** [comment]
Cannot see connections to `optmnstr.com` on `itsfoss.com`

However, some other adblocking lists have blocked `optmnstr.com`.

**Comment by Khrin** [comment]
It isn't advertising. https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_annoyance_thirdparty.txt#L231

**Pull request closed without merging**
