### PR TITLE
A: outlook.live.com

### PR DESCRIPTION
**Pull request by peace2000**
Remnant banner on the right, after ads inside of it are blocked.

remnant banner

### CODE REVIEW

**Comment by ryanbr** [comment]
No pull, anti-adblock message..

**Comment by peace2000** [comment]
Ok, however if ads inside that bar would have not been blocked, that ad bar would just be a normal ad bar. In that case it could have been hid?

It always depends how things are interpreted. :)

**Comment by peace2000** [comment]
outlook mainos

Still no? @ryanbr

**Comment by ryanbr** [comment]
I checked outlook here, and no advert was seen.

**Comment by peace2000** [comment]
If you disable Easylist, then it's visible.

**Comment by peace2000** [comment]
My point just was that I consider this a legitimate target because when ads are not blocked, this is just a normal ad bar, that couöd be hid as a normal ad hiding process.

**Pull request closed without merging**
