### PR TITLE
A: bot-hosting.net

### PR DESCRIPTION
**Pull request by MathiasDPX**

### CODE REVIEW

**Comment by Yuki2718** [comment]
No explanation and no link? Anyway, wrong syntax.

**Comment by Khrin** [comment]
> No explanation and no link? Anyway, wrong syntax.

https://github.com/easylist/easylist/issues/18430 I think

**Comment by MathiasDPX** [comment]
Can I get an explication please,
This is my first filter

**Comment by Yuki2718** [comment]
> Can I get an explication please, This is my first filter

`||` is domain anchor and should not be added to element-hiding rules. Read https://help.eyeo.com/en/adblockplus/how-to-write-filters and https://adblockplus.org/en/filter-cheatsheet

**Comment by MathiasDPX** [comment]
Ooh ok I read everything you send to me,
Si If I remove the domain anchor everything should bé done ?

**Comment by Yuki2718** [comment]
> Si If I remove the domain anchor everything should be done ?

No, as I cannot reproduce the original issue https://github.com/easylist/easylist/issues/18430. We do not add rules just because someone claims the rules are useful. The story could be different if you're one of the long-term contributor, but even if so we prefer having evidences that the rules are needed AND they don't cause trouble. We need at least screenshot(s) of DOM around the ad element which will be shown in devtools.

**Pull request closed without merging**
