### PR TITLE
M: Update 59f024a42b1

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by peace2000** [comment]
Is there any site still using that?

**Comment by peace2000** [comment]
Is there any site still using that?

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/issues/227
https://forums.lanik.us/viewtopic.php?f=62&t=37604

Checked many sample links but could not find sites that still use that.

**Comment by Khrin** [comment]
I don't think that's necessary anymore.

**Pull request closed without merging**
