### PR TITLE
exception for custom salesforce pages beginning with adv_

### PR DESCRIPTION
**Pull request by gbutt**

### CODE REVIEW

**Comment by Khrin** [comment]
Can you give an actual example where this false positive is occurring?

**Comment by gbutt** [comment]
It's a protected site, but widely used by all students in the our university. Here are some example URLs: 

- Production https://customdomain.force.com/adv_MyPage
- Sandbox https://somesandbox--c.cs50.visual.force.com/adv_MyPage

**Comment by Khrin** [comment]
Apparently both are dead links. We'll need a demo account.

**Comment by gbutt** [comment]
@Khrin, I received permission to grant you access as a student to our testing environment. I can send you the credentials and some steps to reproduce. Would this work?

**Comment by gbutt** [comment]
I think it's OK to provide more detail - I didn't want to overstep my boundaries.

The University of Colorado has a website that is available to all currently enrolled students that allows them to schedule time with their Advisors and other mentors. A major part of our application that allows students to schedule appointments with their advisors is not working when adblockers are enabled.

Demo: [https://www.screencast.com/t/eIOFk7BhhhY](https://www.screencast.com/t/eIOFk7BhhhY)

This adblock rule specifically affects our page at https://mycuhub.force.com/adv_Schedule_Advising_Session because it contains .com/adv_. This pull request will allow all pages hosted on the force.com domain to bypass this rule.

**Comment by Khrin** [comment]
Sorry, I should have asked for more details to you before, this video is enough for me. https://github.com/easylist/easylist/commit/cad7f34ab9a58caae592c27e51fe176f5c74b9e0 After forcing an update of EasyList, please tell me if is solved now or not.

**Comment by gbutt** [comment]
Yup it works - thanks for merging. Cheers

**Pull request closed without merging**
