### PR TITLE
A: https://edx.readthedocs.io/projects/edx-installing-configuring-and…

### PR DESCRIPTION
**Pull request by 0o5rlubm**
…-running/en/latest/

### CODE REVIEW

**Comment by Yuki2718** [comment]
Can `https://edx.readthedocs.io/_/static/javascript/readthedocs-analytics.js` be blocked?

**Comment by 0o5rlubm** [comment]
call to `https://edx.readthedocs.io/_/api/v2/analytics/` is made by another script than `readthedocs-analytics.js`.

`readthedocs-analytics.js` currently loads GTM, so yes let's block it too

**Comment by nemanjan00** [comment]
This is just insane... You can not just block `api/v2/analytics` on all sites... 

This broke multiple of websites I worked on, and route has nothing to do with tracking, it is for showing users analytics about their progress...

**Comment by Yuki2718** [comment]
@nemanjan00 Please provide an actual link broken by the rule so that EL maintainer can judge and adjust the rule if needed.

**Comment by nemanjan00** [comment]
Those are internal company portals, I can not share more info.

However it should be obvious that rule that is this generic should not be on block list. According to the issues, I am not the only one affected

**Comment by Yuki2718** [comment]
So you can not share even some clues, partially sealed screenshots, or anything else? Although I tend to understand your claim, we need an evidence. What rule would you suggest?

**Comment by nemanjan00** [comment]
What kind of screenshot do you need?

**Comment by wiederin-skew** [comment]
Hi all,

Login is required to access prime.coinbase.com, but please find a screenshot of the failing requests below.

image (5)

I have flagged this issue on issue https://github.com/easylist/easylist/issues/14634.

Thanks for the support!

**Comment by jmiller0** [comment]
Hi, can we submit a PR to rollback this commit [1bb791f](https://github.com/easylist/easylist/pull/13878/commits/1bb791f21babeeda9c1f1af25dd3ea201156eac8) please?

**Comment by 0o5rlubm** [comment]
PR submitted to fix that, please move discussion to the issue #14634, thanks

**Pull request merged**
