### PR TITLE
Bug: Fix AdguardTeam/AdguardFilters#70876

### PR DESCRIPTION
**Pull request by piquark6046**
AdguardTeam/AdguardFilters#70876

### CODE REVIEW

**Review by wout-codes — APPROVED** [review]

**Comment by DandelionSprout** [comment]
Closely related: https://github.com/AdguardTeam/AdguardForWindows/issues/3570

**Comment by DandelionSprout** [comment]
I also propose changing the PR's entry to `/antiadblock.$domain=~github.com|~raw.githubusercontent.com`

**Comment by piquark6046** [comment]
> 
> 
> I also propose changing the PR's entry to `/antiadblock.$domain=~github.com|~raw.githubusercontent.com`

Your request is applied. Thank you.

**Comment by duryytt** [comment]
@ryanbr @Khrin
Why not merge this pull request? 5 months passed but still pending.

**Review by duryytt — APPROVED** [review]

**Comment by duryytt** [comment]
@ryanbr @Khrin 

I can still reproduce this problem

<details>
 <summary>Image</summary>

japon



</details>

<details>
 <summary>Image</summary>

w2


</details>

With `EasyList` enabled, click on the `antiadblock.txt` file in the repo. It shows an error saying the contributors could not be loaded.
Also, sometimes the `antiadblock.txt` page loads too late.

I think this should be merged now.

**Pull request closed without merging**
