### PR TITLE
Update easyprivacy_general.txt

### PR DESCRIPTION
**Pull request by agrofx1**
Added /telemetry/* endpoint

This endpoint is used by wiris.com math plugin for telemetry

### CODE REVIEW

**Comment by Khrin** [comment]
any steps on how to reproduce it? or can you share the full url to block? 

proposed filter looks a bit too generic for easyprivacy...

**Comment by agrofx1** [comment]
The endpoint is https://data.wiris.cloud/telemetry/v1. 
image

The editor is sending this data: `
{
  "tim_sen": "2024-06-17T17:28:12.225Z",
  "evs": [
    {
      "tim_cre": "2024-06-17T17:28:07.079Z",
      "typ": "STARTED_TELEMETRY_SESSION"
    }
  ],
  "sen": {
    "sen_id": "REDACTED",
    "dev_id": "REDACTED",
    "sol": "MathType for TinyMCE",
    "sol_ver": "8.5.0",
    "hos": [
      {
        "nam": "compilation",
        "fam": "telemeter",
        "ver": "1.0.4",
        "target_triple": "wasm32-unknown-unknown",
        "build_profile": "release"
      },
      {
        "nam": "chrome",
        "fam": "browser",
        "ver": "126.0.0.0"
      },
      {
        "nam": "tinymce",
        "fam": "html-editor",
        "ver": "6.7.0"
      },
      {
        "nam": "REDACTED",
        "fam": "os"
      },
      {
        "nam": "REDACTED",
        "fam": "domain"
      }
    ]
  },
  "ses": {
    "id": "REDACTED",
    "pag": 0
  }
}`
This endpoint requires access token (because this is a paid plugin)

**Comment by agrofx1** [comment]
I moved to specific.txt

**Comment by Khrin** [comment]
Can you confirm that `||data.wiris.cloud/telemetry/` doesn't cause any obvious problems when blocked?

**Comment by agrofx1** [comment]
I already use it with uBlock Origin custom filters. Nothing breaks

**Pull request closed without merging**
