### PR TITLE
P: iltalehti.fi (videos don't work without accepting cookies)

### PR DESCRIPTION
**Pull request by peace2000**
https://www.iltalehti.fi/ulkomaat/a/fac86480-df24-41b8-be6c-6ab6ff6476e4

Cookies have to be accepted in order to get videos to work. In other cases, it's ok to hide that banner. But not for video pages. This rule forces the banner to be shown on video pages.

Here's a sample of a non-video page:
https://www.iltalehti.fi/kotimaa/a/34978951-3b71-403f-bd30-43db57e4b2fa

### CODE REVIEW

**Comment by krystian3w** [comment]
So ABP no longer suppport unhide bar?

Or very fastly implemented style and include directivr?

**Comment by ryanbr** [comment]
I couldn't get this to work, maybe create a PR to just allow the certain cookie elements to open?

**Comment by peace2000** [comment]
Ok this PR wen't broken during edit...

What if you test in incognito mode @ryanbr ?

And if that doesn't help, try to disable this existing filter `iltalehti.fi##.alma-cmpv2-container` (it's currently in EL Cookie)

And try to combine these two:

`iltalehti.fi##.alma-cmpv2-container:style(display: none)`
`iltalehti.fi##script[src="https://script.ilcdn.fi/il-iltv-player/iltv-player.min.js"] ~ .alma-cmpv2-container:style(display: block !important)`

**Comment by ryanbr** [comment]
Its not worth the "fix", I'll leave this.

**Comment by peace2000** [comment]
@ryanbr How so? This site is one of the most popular news websites in Finland, how come it's not worth to fix video playing errors on it?

**Comment by ryanbr** [comment]
Its just a hack, video does currently play atm?  which we fixed in a previous commit

**Comment by ryanbr** [comment]
Create a snippet (aopr/aopw/acis/etc) to break the cmp consent requirement would be considered here and much more desirable

**Comment by krystian3w** [comment]
I added `iltalehti.fi##+js(clickTimeout, almacmp-modalConfirmBtn)` to [PCCassets](https://github.com/FiltersHeroes/PCCassets)/[sections](https://github.com/FiltersHeroes/PCCassets/tree/main/sections)/[euCDB](https://github.com/FiltersHeroes/PCCassets/tree/main/sections/euCDB)/[cTimeout.txt](https://github.com/FiltersHeroes/PCCassets/blob/main/sections/euCDB/cTimeout.txt)

As long no found scriptlet to repair a non-video page via uBO standard scriptlets (without manual click if pop-up are unhidden).


Syntax:

https://polishannoyancefilters.netlify.app/en/PolishCookieConsent/syntax/

And Polish Cookie Consent are open to add more fi pages where works:

- addToStorage.js
- bakeCookie.js
- clickInteractive.js
- clickTimeout.js
- clickComplete.js
- redirect.js

also are open to improve scriptlets (e.g. enable click in pop-ups on youtube.com or any vary late loaded on page), for now we don't support actions in iframes so many de pages with pop-ups maybe are not fixable today.

**Comment by Nojuuu** [comment]
> Create a snippet (aopr/aopw/acis/etc) to break the cmp consent requirement would be considered here and much more desirable

Try `iltalehti.fi##+js(set, jwAlmaCMPLoaded, true)`

**Comment by peace2000** [comment]
> > Create a snippet (aopr/aopw/acis/etc) to break the cmp consent requirement would be considered here and much more desirable
> 
> Try `iltalehti.fi##+js(set, jwAlmaCMPLoaded, true)`

This doesn't seem to work for me.

**Pull request closed without merging**
