### PR TITLE
A: https://areena.yle.fi/

### PR DESCRIPTION
**Pull request by Nojuuu**
tracking

### CODE REVIEW

**Comment by Nojuuu** [comment]
@peace2000 

content not loading with these:?

Easyprivacy: `/analytics-sdk.`
AdGuard tracking protection: `||analytics-sdk.yle.fi^`

`https://areena.yle.fi/tv`
`https://areena.yle.fi/tv/ohjelmat/sarjat`

**Comment by peace2000** [comment]
Yeah it seems to.

How about:

`areena.yle.fi##+js(set, window.yleAnalytics, noopFunc)` ?

**Comment by Nojuuu** [comment]
> How about:
>areena.yle.fi##+js(set, window.yleAnalytics, noopFunc) ?


That seems to help

`dax.yle.fi/yle/areena/s` should probably be blocked if `analytics-sdk.yle.fi` gets allowlisted here

**Comment by peace2000** [comment]
I'd say that just let it be. This can be fixed in uAssets and in AG.

ABP doesn't use EP as a default list anyway...

I remember that `areena.yle.fi` was fixed long time ago but probably the fix has been removed as part of cleaning operations I think.

**Comment by peace2000** [comment]
The best would be if EP would contain a different section for uBO to so that scriptlets could be added but this was refused https://github.com/easylist/easylist/pull/8317 (I think it's because policies of ABP.....)

**Comment by peace2000** [comment]
Fixed for uBO https://github.com/uBlockOrigin/uAssets/commit/3550cc1197e9857038f711e725980f004af410f9

**Comment by peace2000** [comment]
@Yuki2718 

Can you add Adguard version of this filter:

`areena.yle.fi##+js(set, window.yleAnalytics, noopFunc)`

To Adguard tracking protection?

**Comment by Yuki2718** [comment]
> 
> Can you add Adguard version of this filter:
> 

A problem is AG has wide range of products some not supporting scriptlet. What should I add for platforms not supporting scriptlet, `@@||analytics-sdk.yle.fi^$domain=areena.yle.fi`?

**Comment by peace2000** [comment]
@Nojuuu 

Too bad EP whitelisted that https://github.com/easylist/easylist/commit/d6e068f960d9ba6771e4b50ef6515e195290716b

Let's block it then on uAssets https://github.com/uBlockOrigin/uAssets/commit/30e49d3d79afcd9b34a28929d0b1a6e87ba35a57

**Comment by peace2000** [comment]
> > Can you add Adguard version of this filter:
> 
> A problem is AG has wide range of products some not supporting scriptlet. What should I add for platforms not supporting scriptlet, `@@||analytics-sdk.yle.fi^$domain=areena.yle.fi`?

Well, if some products on AG won't support set-constant then that needs to be whitelisted. The breakage is not minor so it should be fixed some way.

**Comment by Nojuuu** [comment]
@Khrin @Yuki2718 
Blocking at least `||dax.yle.fi/yle/areena/s` should be fine

image

**Comment by peace2000** [comment]
Ok, that set-constant rule was bad after all.

https://github.com/uBlockOrigin/uAssets/commit/30e49d3d79afcd9b34a28929d0b1a6e87ba35a57#commitcomment-118531536

**Pull request closed without merging**
