### PR TITLE
Actualize presearch blocking

### PR DESCRIPTION
**Pull request by karolyi**
Hey,

three changes here:

1: Removing outdated blocking from presearch, add the new variant of ad blocking, whereas ads are served as "backgrounds", with clickable boxes in one corner of the result pages.

2: Blocking sponsored carousels, that lead to big-tech pages (mostly amazon) via tracker URLs

3: Turn off autosuggestion "feature" that often contains ads

### CODE REVIEW

**Comment by mapx-** [comment]
No, you can not use `matches-attr` (uBO / AG specific) in EL (used by al adblockers). You have to propose classic filters

**Comment by karolyi** [comment]
Well, then please help me out here, how do you match the following with the old syntax:

```html
<div class="md:block" :class="ads.showAdInfo ? '' : 'hidden'">
```

Last time I checked, I had to use the new syntax because the old couldn't handle this, but I might have been missing something.

**Comment by mapx-** [comment]
Did you test

```
||assets.presearch.com/backgrounds/$image,1p
presearch.com##[href*="background-url"]
```

**Comment by karolyi** [comment]
The HTML code excerpt is the div that shows the clickable link for the current served background, be it an ad or an actual photo.

Maybe  you're using other instances.

The code you provided seems to be working, but there's still the issue of the `:click` attribute.

**Comment by mapx-** [comment]
yeah, I confirm, no such code on my side:

image

**Comment by karolyi** [comment]
Probably coming from an instance with a different version of the presearch docker container.

Anyway, I think we have the proper filterset now.

**Comment by mapx-** [comment]
You cannot use `1p`

Replace it by `~third-party`

**Comment by karolyi** [comment]
Done.

**Comment by karolyi** [comment]
In the meantime, I also took the change and added turning off the "autosuggestion" feature, that will contain ads in the responses:

```json
[
    "buy ",
    [
        "buy here pay here",
        "buy here pay here columbus ohio",
        "buy here pay here dublin ohio",
        "buy buy baby",
        "buy now pay later",
        "buy buy baby easton",
        "buy nothing day",
        "buy instagram followers",
        "buy sell trade",
        "buy gold",
        "buy miracle smile",
        "buy tiktok followers",
        "buy dirt lyrics",
        "buy lottery tickets online",
        "buy dirt"
    ],
    [
        {
            "t": "Shop at walmart product!",
            "a": "Sponsored",
            "q": "clickurl=https%3A%2F%2Frt53.literallysafe.com%2FcUtil%2F9Lqme67E6UF7Qbi3DF7Bi1&impressionURL=https%3A%2F%2Frt53.literallysafe.com%2FiUtil%2F9Lqme67E6UF7Qbi3DF7Bi1",
            "i": "https://www.walmart.com/favicon.ico"
        }
    ]
]
```

**Comment by ryanbr** [comment]
presearch.com###background-cover
||assets.presearch.com/backgrounds/
presearch.com##.items-center.bg-transparent

The old rule is still working also. Removing the background will affect non-ad backgrounds

**Comment by karolyi** [comment]
I can live without backgrounds, if that means ads will go away too.

As for the old rule, I can't find any such text in the newly generated search results.

**Comment by karolyi** [comment]
I'll make another PR with the carousel and autosuggestion blocking. Besides the one rule you added that does nothing, you left out those in here.

**Pull request closed without merging**
