### PR TITLE
A: https://www.pstream.net/e/KJxQ2W0P91WW00L

### PR DESCRIPTION
**Pull request by smed79**
https://github.com/abp-filters/abp-filters-anti-cv/issues/364

### CODE REVIEW

**Comment by ryanbr** [comment]
Why the removal of `||epnycpszmpvft.com^$third-party` @smed79

**Comment by Crystal-RainSlide** [comment]
> Why the removal of `||epnycpszmpvft.com^$third-party` @smed79

It seems this domain is not resolved any more, at least on 8.8.8.8 and Level 3.

**Comment by smed79** [comment]
@ryanbr Not intentional, bad timing of submitting the pull request. 

Fixed ...

**Comment by smed79** [comment]
@Khrin

**Pull request merged**
