### PR TITLE
fix risepeople.com for browser.sentry-cdn.com

### PR DESCRIPTION
**Pull request by adarsh0d**
URL: https://risepeople.com

image

### CODE REVIEW

**Comment by spirillen** [comment]
I can find a lot of other spyware, but not sentry.io...

image

**Comment by adarsh0d** [comment]
> I can find a lot of other spyware, but not sentry.io...
> 
> image

where did you find it ? I didn't understand

**Comment by spirillen** [comment]
I do NOT see `browser.sentry-cdn.com` on `risepeople.com`. Better?

**Comment by adarsh0d** [comment]
> I do NOT see `browser.sentry-cdn.com` on `risepeople.com`. Better?

Hey, we are using it internally after login, that's why I attached this screenshot
image

**Comment by adarsh0d** [comment]
Please merge

**Comment by ryanbr** [comment]
Won't be merged unless its reproducable. @adarsh0d

**Comment by ryanbr** [comment]
Closing. 20 days later, and no details to reproduce this.

**Pull request closed without merging**
