### PR TITLE
added img2.storyblok.com a.storyblok.com to white list

### PR DESCRIPTION
**Pull request by Slackman2015**
Adding image domains to the white list because adblockers identify images in certain sizes as ads. The size of the images appears in the links of the images:
https://a.storyblok.com/f/61085/2848x4272/45e8702160/photo-of-green-leaves-3571551.jpg
https://img2.storyblok.com/300x0/f/61085/2848x4272/45e8702160/photo-of-green-leaves-3571551.jpg

### CODE REVIEW

**Comment by Khrin** [comment]
Not sure what you attempted to do, but I don't like it.

**Comment by Slackman2015** [comment]
I will explain what I'm trying to achieve:
One of our customers complained that certain images getting blocked by adblockers depending on their size.
The domain a.storyblok.com is for assets of all types and images too. When you take a look at this example https://a.storyblok.com/f/61085/350x200/f1b0e4056d/demo-image.jpeg then you will see that the size is inside of the URL of the image and the adblockers can recognize this already as an ad. It's similar for the img2 domain of our image service that allows to modify images https://img2.storyblok.com/250x0/f/61085/350x200/f1b0e4056d/demo-image.jpeg
Our CMS powers now 15000+ projects and I can't tell you how many pages are suffering from the same problem. Just one perceived and reported this.

**Comment by llacb47** [comment]
Then please explain why you modified a rule concerning `imasdk.googleapis.com`??

**Comment by Slackman2015** [comment]
Oh I see that I added the two domains at the wrong place :-/
I'm sorry for that mistake.

**Pull request closed without merging**
