### PR TITLE
M: Init AGLint and FOP.py

### PR DESCRIPTION
**Pull request by piquark6046**
> [!IMPORTANT]
> Please check https://github.com/easylist/easylist/settings/actions before approve it.

Installing a `AGLint` or `lint-staged` package on your local development environment is not required.
It checks filters ordering issue as mentioned in `FOP.py` and [`if-closed` error](https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#if-closed) on a GitHub-hosted actions runner after you push a commit to GitHub.

### CODE REVIEW

**Comment by ryanbr** [comment]
- What are the requirememts
- Can we still use the old method of commiting
- What docs/usage of linting for a noob

**Comment by piquark6046** [comment]
> * What are the requirememts

Installing any npm package or lint-stage checker is not necessary.
You can still develop EasyList without any additional installation.

> Can we still use the old method of commiting

Yes. It is independent between this changes and creating a commit using `FOP.py`.

> What docs/usage of linting for a noob

If you push an incorrect commit about ordering issue as mentioned in FOP.py and [if-closed error](https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#if-closed), each GitHub job step will throw an error.

**Comment by piquark6046** [comment]
@ryanbr What's option selected in Actions permissions section of https://github.com/easylist/easylist/settings/actions?

**Comment by Yuki2718** [comment]
Does AG already run GH actions in the same way? There are occasional cases we want to ignore Lint (with a special comment).

**Comment by piquark6046** [comment]
@Yuki2718 commented:
> Does AG already run GH actions in the same way? There are occasional cases we want to ignore Lint (with a special comment). 

AdGuard runs AGLint only. If AGLint installed in AdguardFilters finds an error, the GitHub actions workflows run will send the notification to AdGuard internal Slack.
But, with current configuration, you will notified via GitHub inbox if your new change does not follow `FOP.py` or [`if-closed` error](https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#if-closed) is detected.

We can ignore the lint because it does not prevent any commit. Only be notified.

**Comment by Yuki2718** [comment]
> 
> But, with current configuration, you will notified via GitHub inbox if your new change does not follow `FOP.py` or [`if-closed` error](https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#if-closed) is detected.
> 

I think this can become notification spam which @ryanbr and I are already suffering.

**Comment by piquark6046** [comment]
> > But, with current configuration, you will notified via GitHub inbox if your new change does not follow `FOP.py` or [`if-closed` error](https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#if-closed) is detected.
> 
> I think this can become notification spam which @ryanbr and I are already suffering.

Why? Due to a contributor opening a PR?

**Comment by Yuki2718** [comment]
FOP.py may not be something suitable to run on Actions - ordering is not too important. If possible, maybe minimal syntax and typo check will be what should be done.

**Comment by Yuki2718** [comment]
> Why? Due to a contributor opening a PR?

Yes, if we get notification just because PRs didn't follow FOP's order, it will be spam. This happens too often and has been silently fixed by next commit of us via FOP.

**Comment by piquark6046** [comment]
> > Why? Due to a contributor opening a PR?
> 
> Yes, if we get notification just because PRs didn't follow FOP's order, it will be spam. This happens too often and has been silently fixed by next commit of us via FOP.

We can configure this settings:
<details><summary>Screenshot</summary>
<p>

image


</p>
</details>

**Comment by piquark6046** [comment]
> FOP.py may not be something suitable to run on Actions - ordering is not too important. If possible, maybe minimal syntax and typo check will be what should be done.

But, it seems that the ordering is important for all `.txt` files except ending with `_uBO.txt`.

**Comment by piquark6046** [comment]
> FOP.py may not be something suitable to run on Actions - ordering is not too important. If possible, maybe minimal syntax and typo check will be what should be done.

Or, we can limit condition of running `jobs.fop`.

**Review by monzta — APPROVED** [review]
LGTM.

**Review by Khrin — APPROVED** [review]

**Review by ryanbr — APPROVED** [review]

**Comment by Yuki2718** [comment]
It caught the error https://github.com/easylist/easylist/pull/19439 GJ!

**Comment by peace2000** [comment]
Why the usage of `:has` is considered erroneous? It's native CSS spec nowadays.

**Comment by Yuki2718** [comment]
Maybe should adjust FOP eventually.

**Pull request merged**
