### PR TITLE
A: http://prostylex.org/

### PR DESCRIPTION
**Pull request by mimmiepower**
Aliexpress ads on `http://prostylex.org/`. Does not seem to break anything. I have not logged in though.

### CODE REVIEW

**Comment by spirillen** [comment]
So ali is showing ads for a torrent site :smiley:  that's a new one :new:

**Comment by llacb47** [comment]
Generic? `##[href^="http://s.click.aliexpress.com"]`

**Comment by mimmiepower** [comment]
> 
> 
> Generic? `##[href^="http://s.click.aliexpress.com"]`

Would have to test on other sites with aliexpress ads, I can only confirm that it works for prostylex.org, but a generic filter would of course be nice. I blocked the connection completely due to privacy, but maybe you could have both.

**Comment by AnonymousPoster** [comment]
We have blocked `s.click.aliexpress.com` for over a year in our DNS, no comments received

And to share a few other, which have been there just as long without comments

```
adservice.aliexpress.com
acookie.aliexpress.com
best.aliexpress.com
pcookie.aliexpress.com
```

You could check if you have these, or for those actually using `aliexpress.com` could test these for us if they actually are any good, or they brake anything :)

PS: thanks for the `prostylex.org` that one was funny :smiley: a web-store advertising for a torrent site :rofl:

**Comment by mimmiepower** [comment]
> 
> 
> We have blocked `s.click.aliexpress.com` for over a year in our DNS, no comments received

I see. Thank you for informing. I do not use the DNS. But I will think of that before posting network blocks.

**Pull request closed without merging**
