### PR TITLE
A: `https://www.romaniatv.net/alexandru-rafila-despre-restrictiile-din-noaptea-de-revelion-nu-vor-fi-luate-masuri-stupide_6036768.html`

### PR DESCRIPTION
**Pull request by LikesHisComputer**

### CODE REVIEW

**Comment by iam-py-test** [comment]
> No description provided.

Please provide more details

**Comment by LikesHisComputer** [comment]
image

**Comment by iam-py-test** [comment]
> image

Not sure, is that an ad-placeholder/an ad which failed to load, or what. I also didn't see it in my very quick test but more detailed testing is needed
More details still would be nice

**Comment by LikesHisComputer** [comment]
edited screenshot

**Comment by ryanbr** [comment]
Easylist is specifically English site, any reason why would add this? @LikesHisComputer

**Comment by LikesHisComputer** [comment]
> Easylist is specifically English site, any reason why we would add this? @LikesHisComputer

I thought AdNow was international.

**Comment by LikesHisComputer** [comment]
@Yuki2718 could you explain? AG Base used to have `##.SC_TBlock`.

**Pull request closed without merging**
