### PR TITLE
A: Tracedock domains

### PR DESCRIPTION
**Pull request by nickspaargaren**
host10.carl-ras.dk
alpha.tracedock.com
apollo.plein.nl
beta.simpel.nl
dtch.brunel.nl
exc.ns.nl
host10.ncoi.nl
host11.polaroid.com
host12.rvshare.com
r.kleertjes.com
s3.smartphonehoesjes.nl
sta.tracedock.com
style.onvz.nl
tdapi.wickey.nl
tdep.hema.nl
tdep.kvk.nl
tdk.petsplace.nl
two.tracedock.com

### CODE REVIEW

**Comment by nickspaargaren** [comment]
Special thanks to @pietvanzoen

https://gist.github.com/pietvanzoen/ed7b8322a552542bc00a83ced7332d33#file-domains

**Comment by ryanbr** [comment]
This should be addressed in https://github.com/AdguardTeam/cname-trackers/blob/master/trackers/tracedock.txt @nickspaargaren

**Comment by spirillen** [comment]
Do you guys not mean cm.com?? tracedock is cm now....

https://mypdns.org/my-privacy-dns/matrix/-/issues/3255#relevant-logs-andor-screenshots

**Comment by nickspaargaren** [comment]
> This should be addressed in https://github.com/AdguardTeam/cname-trackers/blob/master/trackers/tracedock.txt

@ryanbr, please see:  https://github.com/AdguardTeam/cname-trackers/issues/22#issuecomment-965330168

**Pull request closed without merging**
