### PR TITLE
P: https://www.legacy.com/charity/memorial-charity-donations/

### PR DESCRIPTION
**Pull request by edivaniadc**
### Issue 1
Cookie consent message is blocked.

lgc2

### Issue 2 
Charity partners banners are blocked 
_Note: although banners link to **pubads.g.doubleclick** page looks broken._

lgc1

lgc3

### Suggested filters:
**1 - To allow the cookie consent message**
Added:
**legacy.com** to existing rule: `@@||g.doubleclick.net/tag/js/gpt.js$script,xmlhttprequest,domain= `
**legacy.com** to existing rule: `@@||g.doubleclick.net/pagead/ppub_config?$domain= `
**legacy.com** to existing rule: `@@||g.doubleclick.net/gpt/pubads_impl_$script,domain=`

**2 - To allow the Charity partners banners** 
Added:
`legacy.com#@#a[href^="http://pubads.g.doubleclick.net/"]`
`legacy.com#@#a[href^="https://pubads.g.doubleclick.net/"]`
`@@||g.doubleclick.net/gampad/clk?$popup,domain=legacy.com` 
_Note: without the `$popup` option links don’t open._

### CODE REVIEW

**Comment by ryanbr** [comment]
I'm on the fence with this, these are technically `sponsors of..`

**Comment by edivaniadc** [comment]
> I'm on the fence with this, these are technically `sponsors of..`

Hi @ryanbr regarding the **Charity partners banners** I believe it make sense to allow it as is part of the website content - menu `Send Flowers` > `Charity Donations`
lgc

**Comment by edivaniadc** [comment]
> > I'm on the fence with this, these are technically `sponsors of..`
> 
> Hi @ryanbr just wondering whether those could be allowed or not^

**Comment by ryanbr** [comment]
Allowing 3rd-party doubleclick scripts is bad for privacy just to show a consent message.

**Pull request closed without merging**
