### PR TITLE
Reduce overblocking

### PR DESCRIPTION
**Pull request by salim-b**
Moves a too unspecific hiding rule from general to specific file, fixing i.a. the manifesto signing on https://aktionvierviertel.ch/manifest/

### CODE REVIEW

**Comment by Yuki2718** [comment]
Such a PR would require at least a few real examples of breakage.

**Comment by salim-b** [comment]
Signing the manifesto on https://aktionvierviertel.ch/manifest/ is a real example (link target of the repsective button is https://aktionvierviertel.ch/manifest/#elementor-action%3Aaction%3Dpopup%3Aopen%26settings%3DeyJpZCI6IjI2MDciLCJ0b2dnbGUiOmZhbHNlfQ%3D%3D )

**Comment by Yuki2718** [comment]
I mean just one example will not be enough to convert a generic filter.

**Comment by salim-b** [comment]
I see. I just figured from the CSS selector `##.elementor-popup-modal.dialog-widget` that it is probably used for non-cookie popups on various other sites, too, since *Elementor* is simply an [open-source (WordPress) website builder](https://github.com/elementor/elementor/).

If you decide to not merge this PR, I'll submit an exception rule for https://aktionvierviertel.ch instead. Just let me know.

**Comment by Yuki2718** [comment]
> 
> If you decide to not merge this PR, 

To be clear, I'm not an EL maintainer so has no right to decide. Just saying.

**Pull request closed without merging**
