### PR TITLE
P: https://taboolanews.com/summary-page/-1149866408393889774

### PR DESCRIPTION
**Pull request by Yuki2718**

### CODE REVIEW

**Comment by ryanbr** [comment]
Should this be fixed? @Yuki271 Taboola own site, does anyone actually visit?

**Comment by Yuki2718** [comment]
> Should this be fixed? 

Doesn't EL fix even advertiser's sites unless too abusive? 24.9M visitors/month: https://www.similarweb.com/website/taboolanews.com/#keywords

BTW you mentioned a wrong person.

**Comment by Khrin** [comment]
@Yuki2718 Looks like spam, better avoid to allow ads.

**Comment by Yuki2718** [comment]
Okay

**Pull request closed without merging**
