### PR TITLE
ethereumads.com || https://www.mypdns.org/T3970

### PR DESCRIPTION
**Pull request by spirillen**
Found through https://www.mypdns.org/T3969

### CODE REVIEW

**Comment by ryanbr** [comment]
If its a legit site, making it $third-party would be preferable @spirillen

**Comment by spirillen** [comment]
> If its a legit site...

:smirk: wouldn't that depend on who you asks?? :smirk: And how should we bw able to determine what is a Legit site, where are (if) the company registered etc.

If you would like me to add `$third-party` I'll do it, but on the other hand, or also in time noticed a lot of other noticed a number of "legit" adware servers/sites that don't have the `$third-party`. 

Non the less it's the same to me, they are blocked in my rpz...

**Comment by ryanbr** [comment]
(and move it the third-party section also..) @spirillen 

Most, if not all non-third-party aren't hosting a homepage.  which is why `^` was preferred in that case.

**Comment by spirillen** [comment]
> (and move it the third-party section also..) @spirillen
> 
> Most, if not all non-third-party aren't hosting a homepage. which is why `^` was preferred in that case.

Does it look more right for you now??

**Pull request merged**
