### PR TITLE
A: keygames.com placehoders

### PR DESCRIPTION
**Pull request by Alex4567890**
Placeholders / ad spaces (at least two of them)

### CODE REVIEW

**Comment by Alex4567890** [comment]
At least 2 placeholders can be seen at: https://keygames.com/html5-games/

**Comment by ryanbr** [comment]
Can `keygames.com##.left.featured.game` be minimised? `keygames.com##.left` or `keygames.com##.featured` ? @Alex4567890

**Comment by Alex4567890** [comment]
`keygames.com##.banner` and `keygames.com##.featured` seem to fix the issue.

**Comment by ryanbr** [comment]
adjust your PR, and I'll land

**Comment by Alex4567890** [comment]
Sorry, I was tired. `keygames.com##.left seems to work.`

**Pull request merged**
