### PR TITLE
A: aristeguinoticias.com

### PR DESCRIPTION
**Pull request by jabonsolo**

### CODE REVIEW

**Comment by Khrin** [comment]
Wouldn't be better to have these filters added in Easylist spanish?

**Comment by jabonsolo** [comment]
I was thinking about it, but as this is not to block an ad, it is actually to prevent a page to break, but if you consider it is better to add it there I'm ok with that.

**Comment by Khrin** [comment]
Yes, if it's possible, also fixing filters for easylist should be added to supplemental filters lists

**Comment by jabonsolo** [comment]
Added filters to EL spanish.
https://github.com/easylist/easylistspanish/commit/19435d1bedd53eb8078940c37a73634eb87acde8

**Pull request closed without merging**
