### PR TITLE
A: (nsfw) https://www.rolite.eu/anal/sunny-leone-first-time-anal-sex.php

### PR DESCRIPTION
**Pull request by Yuki2718**
…(fixes https://github.com/AdguardTeam/AdguardFilters/issues/70725)
https://github.com/AdguardTeam/AdguardFilters/issues/70725

### CODE REVIEW

**Comment by ryanbr** [comment]
Why not `||rolite.eu/banners/` ? @Yuki2718

**Comment by Yuki2718** [comment]
Will change soon.

**Comment by ryanbr** [comment]
You need to rebase this, a few conflicts. Also rule34hentai filter was merged for some reason.

**Comment by Yuki2718** [comment]
Simply resolved the conflict via web interface, but if there's still a problem please fix on your end.

**Comment by spirillen** [comment]
While you are at it, you should ad this annoyance


```
! 2020-12-27 https://www.pornhub.com
pornhub.com##.active.fanclub-info-pop
```

**Comment by Yuki2718** [comment]
> ##.active.fanclub-info-pop

I don't see that, and this is not PH issue.

**Comment by spirillen** [comment]
Hmm, it poped straight up in my face with the tor browser :smirk:

**Pull request closed without merging**
