### PR TITLE
A: [NSFW] https://www.deviants.com/

### PR DESCRIPTION
**Pull request by felippesantos46**
Hide ads placeholder inside the videos at https://www.deviants.com/

Proposed filter: `deviants.com###_iframe_content`

Screenshot:
Screenshot 2021-12-01 at 09 49 45

### CODE REVIEW

**Comment by spirillen** [comment]
Not to be on the evil site, but I did not see the rule tricked, nor experience any overlay on `https://www.deviants.com/videos/31383/redhead-fucked-and-creampied-at-home/`

image

**Comment by felippesantos46** [comment]
Hey oh @spirillen, so i can see this ID just after play and pause the video. On my side the Filter was triggered, but i dunno 😅

Screenshot 2021-12-02 at 11 22 29

**Comment by spirillen** [comment]
Well it is not uncommon that it will vary depending on countries or other regional things. That's is mostly why I do post either comments of `NOT SEEN` or approve the commit (In lack of a I saw this one too), as a help to get rules verified.

PS: personally I like your second screenshot the most

**Comment by felippesantos46** [comment]
> Well it is not uncommon that it will vary depending on countries or other regional things. That's is mostly why I do post either comments of `NOT SEEN` or approve the commit (In lack of a I saw this one too), as a help to get rules verified.
> 
> PS: personally I like your second screenshot the most

Got it, makes total sense ! and noted i will provide better screenshots next time 😅. Thank you for the advises.

**Pull request merged**
