### PR TITLE
Remove lead.im private service domain

### PR DESCRIPTION
**Pull request by psyafter**
We are lead.im private solution.
Our scripts not collect any private information

### CODE REVIEW

**Comment by ryanbr** [comment]
`http://cdn.lead.im/js/lm_url2form.js`  Do explain.

**Comment by psyafter** [comment]
> `http://cdn.lead.im/js/lm_url2form.js` Do explain.

This script save query parameters into html form, so customer will know which pages he  visited in his session.

ps: If it something that not permitted - why block whole domain but not this script only?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/db37300a0828074cb16145a9098c6ecce91c785a Not a new filter. Also a company that tracks can't be trusted, easier to change a file name than a domain.

**Comment by psyafter** [comment]
what you mean? I can change file name. I can remove using on original page.
Can this filter to be changed to block single file instead of domain?

**Comment by ryanbr** [comment]
based on another tracking script `https://cdn.lead.im/api/v2/leadim.api.js` we're leaving the block.

**Pull request closed without merging**
