### PR TITLE
A: https://cybermap.kaspersky.com/

### PR DESCRIPTION
**Pull request by shenzhiming88**
image

### CODE REVIEW

**Review by peace2000 — APPROVED** [review]

**Comment by shenzhiming88** [comment]
@ryanbr Please merge it. Thanks!

**Comment by peace2000** [comment]
Hi! I just send a review that this looks ok to me, but it doesn't mean that it's merged yet, I don't have write access to this list.

@shenzhiming88

**Comment by peace2000** [comment]
Ok neverming, you already opened a new: https://github.com/easylist/easylist/pull/8945/

**Comment by shenzhiming88** [comment]
@peace2000 I didn't think he would check the previous PR, so I recreated one

**Pull request closed without merging**
