### PR TITLE
M: Specific domain in white list rule for kinitv.com

### PR DESCRIPTION
**Pull request by hoang-rio**
Some site use embed dailymotion video as Advertisment

### CODE REVIEW

**Comment by smed79** [comment]
@ryanbr I totally disagree with this change ad5c1905441

As noted above, too many websites embed dailymotion videos as ads with auto play and some of them are incorporate in 1x1 iframes.

**Comment by Khrin** [comment]
Anyway, this pull request is rejected because the proposed rule is invalid.

**Comment by Khrin** [comment]
@smed79 Some examples?

**Comment by smed79** [comment]
other old reports
https://forums.lanik.us/viewtopic.php?f=62&t=37321
https://forums.lanik.us/viewtopic.php?f=62&t=38166
https://forums.lanik.us/viewtopic.php?f=62&t=36899
https://forums.lanik.us/viewtopic.php?f=62&t=32431
https://forums.lanik.us/viewtopic.php?f=62&t=30704
https://forums.lanik.us/viewtopic.php?f=62&t=29405

**Comment by smed79** [comment]
Another example `https://www.cartoon3rbi.net/` with a hidden 1px iframe 

https://vgy.me/ztTvYv.png

```
<iframe name="V5" src="https://www.cartoon3rbi.net/dm.php?vid=x6gqx1r" scrolling="no" border="0" style="height: 1px; width: 1px;" frameborder="0" align="middle" style="display: none;"></iframe>
```

**Comment by hoang-rio** [comment]
Invalid keyword domain now fixed. That is my mistake but whilelist all dailymotion embed video will unblock a lot of ads

**Comment by ryanbr** [comment]
Its just a subdocument request, it won't stop ads anyways.

**Comment by smed79** [comment]
We are not talking about the preroll video ads, the subdocument request it' self is an advert.

**Pull request closed without merging**
