### PR TITLE
A: (nsfw) www.pornhub.com (fixes https://github.com/AdguardTeam/Adgua…

### PR DESCRIPTION
**Pull request by Yuki2718**
…rdFilters/issues/137210)
https://github.com/AdguardTeam/AdguardFilters/issues/137210

### CODE REVIEW

**Comment by Khrin** [comment]
It is supposed to be used on the home page? No hits for me, anyway. (And it looks like quite too much generic)

**Comment by Yuki2718** [comment]
@Khrin I also can't always reproduce, maybe reload many times.

<details>
<summary>Screenshot [NSFW]</summary>

ph

</details>

How about `##.emptyBlockSpace[style="display: block;"]` or `###singleFeedSection > .emptyBlockSpace` then?

**Comment by zloyden** [comment]
@Yuki2718 @Khrin could you also take a look at this? https://github.com/AdguardTeam/AdguardFilters/issues/137210#issuecomment-1347620067

**Comment by Khrin** [comment]
@zloyden I see that `/_xa/ads_` in EL and `/_xa/ads_batch?ads=$xmlhttprequest,script` which apparently is listed in Adguard are blocking the very same elements, so I don't really know what exactly should I look for.

Also, can you reproduce and confirm the need of `pornhub.com##.emptyBlockSpace`? (or at least the filters proposed here by @Yuki2718 )

**Comment by zloyden** [comment]
He mentioned that with only `EasyList` turned on he saw the ad in the right column of the video feed.

> Also, can you reproduce and confirm the need of

Yep, I can. In fact, it is blocked by AdGuard Base. Looks like `pornhub.com##.emptyBlockSpace` is enough and I don't see incorrect blocking with the rule.

<details><summary>Screenshot:</summary>

image

</details><br/>

**Comment by Yuki2718** [comment]
As said, `/_xa/ads_` is working and I don't see the ad even if I disabled anything other than EL.

**Comment by Yuki2718** [comment]
> re-insertion by `https://static.trafficjunky.com/ab/ads_test.js`.

AG or uBO user won't see, but to hide within EL maybe `###singleFeedSection > .alpha`.

**Pull request merged**
