### PR TITLE
Additions to easylist_general_hide.txt

### PR DESCRIPTION
**Pull request by diaux**
Found several div IDs and classes that, imho, should be included into EasyList.

### CODE REVIEW

**Comment by Khrin** [comment]
I can't find these elements on the page you've referenced...

**Comment by diaux** [comment]
Jackpot! They changed the code of the website in between my commit and your checkout, it was there when I checked. See this [link](view-source:http://web.archive.org/web/20170120090505/http://deportes.televisa.com/) for the website source code 4 days ago (January 20th). Your call: (1) include the filters into EasyList if you like or (2) close this Pull Request without merging anything. Either way, I will have to go through the website again to adjust/add any filters for EasyList Spanish. Thanks much Khrin!

**Comment by diaux** [comment]
Markdown I hate you! Here's the link, sorry: http://web.archive.org/web/20170120090505/http://deportes.televisa.com/

**Comment by Khrin** [comment]
We still have the references, still valid for me.

**Pull request merged**
