### PR TITLE
A: https://www.radiozuidrand.be/

### PR DESCRIPTION
**Pull request by felippesantos46**
Filter to hide ads and title: ONZE ADVERTEERDERS / PARTNERS
`##aside[id^="text-15"]`

[radiozuidrand](https://www.radiozuidrand.be/)

Screenshot 2021-09-08 at 23 17 04

### CODE REVIEW

**Comment by ryanbr** [comment]
`##aside[id^="text-15"]` way to generic.

**Comment by ryanbr** [comment]
Also non-english site, Easylist = English only

**Comment by edivaniadc** [comment]
Hi @ryanbr this PR was created because of a previous [commit](https://github.com/easylist/easylist/commit/a58bcf2) where rule: `/banner-sponsors.` blocks the same ads on the top and mid page and to EL since we don't have an specific list for BE. In case is fine for you to add new rule we can replace `##aside[id^="text-15"]`  with `##aside[class="widget widget_text clearfix"]`. Thank you in advance.

**Comment by Khrin** [comment]
It's already in EasyList Dutch, the site is in Dutch language: https://github.com/easylist/easylistdutch/commit/533041db8f3ddbce7f2559dbae072139f45681cf

**Comment by edivaniadc** [comment]
@Khrin thank you so much for that.

**Pull request closed without merging**
