### PR TITLE
R: https://www.bradyunited.org/

### PR DESCRIPTION
**Pull request by lebowitz**
This blocks embedded donation forms for many charities

### CODE REVIEW

**Comment by Khrin** [comment]
Please can you be more specific about what's supposedly broken? The "Donate" page seems to be loading correctly.

**Comment by lebowitz** [comment]
Was unbroken by uBlock for us https://forums.lanik.us/viewtopic.php?f=62&t=43350

**Comment by Khrin** [comment]
That's should be an answer?

**Comment by itsdrewmiller** [comment]
@Khrin the at.js file is being blocked on https://www.bradyunited.org/donate (and many other sites) which generates an HTML form to fill out with contact info and (appropriate iframed) credit card info.  In addition to that specific file, there are other assets on the cloudfront domain such as client-uploaded images that are being erroneously blocked.  ublock origin has reverted the change for that blocker which is great, but we would like this to be fixed for adblock and others who use easylist.

**Comment by Khrin** [comment]
Thank you.

**Comment by itsdrewmiller** [comment]
Thanks!

**Pull request closed without merging**
