### PR TITLE
wp-cookie-notification-banner

### PR DESCRIPTION
**Pull request by SeriousHoax**
` https://my.kaspersky.com/`

<details><summary>Screenshot:</summary>

</details><br/>

### CODE REVIEW

**Comment by SeriousHoax** [comment]
@Khrin Hi. Looks like I may have made a mistake? Sorry about that. I think I should've committed this to EasyList cookie instead I made it to Fanboy's addon. Do I need to make this commit to EasyList or is this one will be merged later?

**Comment by Khrin** [comment]
I should apologize to you, I didn't check properly before pulling the change, so I didn't notice it wasn't going to be added to the Annoyances list, instead of EasyList Cookie. Now it's in the proper list.

**Comment by SeriousHoax** [comment]
> I should apologize to you, I didn't check properly before pulling the change, so I didn't notice it wasn't going to be added to the Annoyances list, instead of EasyList Cookie. Now it's in the proper list.

I made the initial mistake by committing in the wrong section. Actually I'm still new to this so making mistakes sometimes. Just trying to help whenever I come across such issues. Anyway, thanks :)

**Comment by Yuki2718** [comment]
@Khrin @SeriousHoax The added rule is wrong. Please check before commit/merge.

**Comment by SeriousHoax** [comment]
> @Khrin @SeriousHoax The added rule is wrong. Please check before commit/merge.

Shit. I should stop making pull requests and stick to creating issues only. Making tons of mistakes. Really sorry about that. @Khrin please make the proper change.

**Comment by Yuki2718** [comment]
> > @Khrin @SeriousHoax The added rule is wrong. Please check before commit/merge.
> 
> Shit. I should stop making pull requests and stick to creating issues only. Making tons of mistakes. Really sorry about that. @Khrin please make the necessary change.

Relax, I too sometimes make mistake. Usually maintainers check the rules but we're all human.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/c5c5133d7a73535eeca2d8af8d9432bdbd9a9163

**Pull request merged**
