### PR TITLE
A: [NSFW] https://rule34.xxx/

### PR DESCRIPTION
**Pull request by felippesantos46**
Hide bottom banners at https://rule34.xxx/ and sub https://rule34.xxx/index.php?page=comment&s=list

Screenshot 2021-12-07 at 08 49 13

### CODE REVIEW

**Comment by slayerduck** [comment]
https://easylist.to/pages/policy.html
_Self-promotion should not be specifically removed by EasyList, although equally should not be allowed if it is blocked._

Kanako.store, at the top:
_It's a rule34.xxx official store. For payment gateway we work with VivaWallet (there can be delays using paypal)_

**Comment by ryanbr** [comment]
Yeah I'll leave this

**Comment by felippesantos46** [comment]
@slayerduck Oh, i didn't realize that it was a self-promo. 
Thank you for that !

**Comment by spirillen** [comment]
@felippesantos46 added here https://mypdns.org/my-external-stuff/ublockorigin-rules/-/commit/f4a4ad2735119d567ee011e04ba962847998642c

**Pull request closed without merging**
