### PR TITLE
A: (nsfw) https://www.theyarehuge.com/v/54118809920-brazzers-codi-vor…

### PR DESCRIPTION
**Pull request by Yuki2718**
…e-s-older-lover-steve-holmes-sneaks-past-her-clueless-boyfriend.big-boobs/
`https://www.theyarehuge.com/v/54118809920-brazzers-codi-vore-s-older-lover-steve-holmes-sneaks-past-her-clueless-boyfriend.big-boobs/`

<details>
<summary>Screenshots</summary>

theyarehuge

theyarehuge1

</details>

### CODE REVIEW

**Comment by spirillen** [comment]
Second click on page still make a pop-up(under) => redirect

image

**Comment by Yuki2718** [comment]
@spirillen I see two new banners of Brazzers Network but don't get popup. What's the second click?

**Comment by spirillen** [comment]
> What's the second click?

When I click one the first time anywhere one the site, that do as expected, but if you click 2 or 3 times on links (or page, had nice sleep since) then you get a pop-up(under) redirection as in the screenshot.

I suspect a click-counter for redirection

**Comment by Yuki2718** [comment]
@spirillen Reproduced, I'll fix in uAssets & AG.

**Comment by Yuki2718** [comment]
@smed79 Maybe you can open PR in ABP anti-CV? popMagic but may not always be present.

**Comment by smed79** [comment]
@Yuki2718 https://github.com/abp-filters/abp-filters-anti-cv/pull/576

**Pull request closed without merging**
