### PR TITLE
A: https://www.romania-insider.com/

### PR DESCRIPTION
**Pull request by Nojuuu**
On smaller screen/window sizes:

Front page:
https://www.romania-insider.com/

</img>

Article page:
https://www.romania-insider.com/rugby-fans-plant-trees-oaks-romania-2023

</img></img></img>

### CODE REVIEW

**Comment by ryanbr** [comment]
Can you remove any other unused filters on the site also? @Nojuuu

**Comment by Nojuuu** [comment]
All of the still seem to get hits in logger
image

**Comment by Nojuuu** [comment]
Maybe `.job-item` should be changed to `.field--name-field-ad-body-2`?

image

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/8acdff588c3f81417813f8eca822bd854eafce1f

**Pull request closed without merging**
