### PR TITLE
A: userengage.com

### PR DESCRIPTION
**Pull request by simivar**
Block userengage.com that spies on users

### CODE REVIEW

**Comment by ryanbr** [comment]
Link to example site?

**Comment by simivar** [comment]
https://euco.pl/
https://developres.pl/

**Comment by ryanbr** [comment]
isn't userengage a website chat program?

**Comment by ryanbr** [comment]
If you visit their site, its fine. Its not "spying on you", does have a minor tracker script but going by previous requests, blocking this will break the site interaction.

**Comment by simivar** [comment]
@ryanbr: Nope, userengage is not website chat program. Chat is one of features. They do  "spying" as well: https://userengage.com/en-us/user-tracking/

**Pull request closed without merging**
