### PR TITLE
address bolighub.dk dataunlocker

### PR DESCRIPTION
**Pull request by JobcenterTycoon**

### CODE REVIEW

**Comment by Yuki2718** [comment]
This site also uses server-side GTM that bypasses current filters.

**Comment by JobcenterTycoon** [comment]
What do you mean with this?

**Comment by JobcenterTycoon** [comment]
But how to they send the data? I see only 3 xhr but with no data send.

**Comment by Yuki2718** [comment]
Hm, you're right. Maybe this site doesn't engage in analytics with GTM.

**Pull request merged**
