### PR TITLE
A: https://strtpe.link/

### PR DESCRIPTION
**Pull request by felippesantos46**
Bundle of filters to block redirects and popups at https://strtpe.link/e/GWgeZokOGmi18jG/ready

Proposed filters: 
||pqorwmmlkf.com^
||bksijiunc.com^
||onyhgvqdknxdesb.top^
||strtpe.link/ad.js
||rewardunderneathreport.com$popup

Screenshots:
Screenshot 2021-12-17 at 14 01 46
Screenshot 2021-12-17 at 14 00 00
Screenshot 2021-12-17 at 13 56 36

### CODE REVIEW

**Comment by felippesantos46** [comment]
https://strtpe.link/e/9kzD6JlZgPiaW36/Hakuouki2021_OVA_02_SUB_ITA.mp4

Screenshot 2021-12-20 at 09 33 16
Screenshot 2021-12-20 at 09 29 47

**Comment by ryanbr** [comment]
Why block `strtpe.link/ad.js` , this is a bait @felippesantos46

**Comment by felippesantos46** [comment]
> Why block `strtpe.link/ad.js` , this is a bait @felippesantos46

@ryanbr My bad ! Removed

**Comment by spirillen** [comment]
@felippesantos46  What happened to 

```
pqorwmmlkf.com
bksijiunc.com
rewardunderneathreport.com
```

I can only see `onyhgvqdknxdesb.top` in your commit, even as you suggested 3 more domains.

**Pull request merged**
