### PR TITLE
P: https://okwave.jp/qa/q6781762.html

### PR DESCRIPTION
**Pull request by hirorpt**
### List the website(s) you're having issues:
`https://okwave.jp/qa/q6781762.html`

### What happens?
The right sidebar does not show up.

### Screenshot
<details><summary>Screenshot 1</summary>

Screenshot 1
</details>

<details><summary>Screenshot 2</summary>

Screenshot 2
</details>

### CODE REVIEW

**Comment by spirillen** [comment]
I don't speak Japanese , can you help with what it says in the right column?

**Comment by hirorpt** [comment]
@spirillen
Use machine translation.
<details><summary>MT screenshot</summary>

Screenshot from 2021-06-29 11-56-26
</details>
DeepL translates some parts to completely different meanings, but it's not critical here.

**Comment by hirorpt** [comment]
I just found out that `@@||google-analytics.com/analytics.js$script,redirect-rule,domain=okwave.jp` is also needed on ublock origin v1.36.0 (Not reproduced on v1.35.2).

**Comment by spirillen** [comment]
> @spirillen
> Use machine translation.
> MT screenshot
> DeepL translates some parts to completely different meanings, but it's not critical here.

That's overkill as only the basics was needed to understand what it's about :)

**Comment by uBlock-user** [comment]
@gorhill, see https://github.com/easylist/easylist/pull/8200#issuecomment-870198471

**Comment by gorhill** [comment]
> Not reproduced on v1.35.2

I can reproduce with 1.35.2.

**Comment by hirorpt** [comment]
> On my side the browser is pulling `google-analytics.com/ga.js`, not `google-analytics.com/analytics.js`.

On my side <details><summary>Screenshot</summary>

Screenshot
</details>

---------------------------------------

Umm..., I tested it again and the result is the same.  @Yuki2718, can you check this issue again?

To clarify, the exception filter for displaying the left sidebar is as follows.
~~~
! v1.35.2 

! Not included in defaults filters
@@||googletagmanager.com/gtm.js$script,domain=okwave.jp
~~~
~~~
! v1.36.0 & 1.36.1b1 

! Not included in defaults filters
@@||googletagmanager.com/gtm.js$script,domain=okwave.jp
! included in Unbreak filters
@@||google-analytics.com/analytics.js$script,redirect-rule,domain=okwave.jp
~~~
Also, I am not the only person who noticed the problem caused on `okwave.jp` by updated `google-analytics_analytics.js`. https://github.com/tofukko/filter/issues/24

In addition, https://github.com/uBlockOrigin/uAssets/issues/9505 is the similar issue.
I also found two similar breakage regressions. I haven't reported them yet because they are trivial.

**Comment by gorhill** [comment]
>  To clarify, the exception filter for displaying the right sidebar is as follows.
> 
>     @@||googletagmanager.com/gtm.js$script,domain=okwave.jp

I can reproduce with that exception filter.

**Comment by Yuki2718** [comment]
`@@||google-analytics.com/analytics.js$script,redirect-rule,domain=okwave.jp|viviennewestwood-tokyo.com` is needed to diplay the sidebar on 1.36.0. IDK if it's different in 1.35.2, is this what you want me to check @hirorpt ?

**Comment by hirorpt** [comment]
Yeah, that's right. In other words, I would like you to verify what gorhil states that cannot be confirmed.

**Comment by Yuki2718** [comment]
With 1.35.2 `@@||googletagmanager.com/gtm.js$script,domain=okwave.jp` is enough to display the sidebar:

okwave

So the issue seems to be specific to 1.36+.

**Comment by gorhill** [comment]
> So the issue seems to be specific to 1.36+.

Yes, because of <https://github.com/gorhill/uBlock/commit/8cd2a1d263a96421487b39040c1d23eb01169484>, so the `redirect-rule` exception [shown here](https://github.com/easylist/easylist/pull/8200#issuecomment-872273197) needs to be add.

**Pull request closed without merging**
