### PR TITLE
Update easylist_general_hide.txt

### PR DESCRIPTION
**Pull request by AirSayy**
Screenshot (18)
Added a Filter found in a banner in the website on the above screenshot.

### CODE REVIEW

**Comment by Yuki2718** [comment]
Self-promo, not ads + on my end it's `##.app-banner__message` (double underscore)

**Comment by AirSayy** [comment]
> Self-promo, not ads + on my end it's ~`##.app-banner__message` (double underscore)~ `##.app-banner`

i copied the direct class on the message in the banner. Probably the reason. Thank-you.

**Comment by ryanbr** [comment]
Doesn't seem to be needed? https://www.similarweb.com/top-websites/south-africa/ shows no message

**Comment by Yuki2718** [comment]
@ryanbr With FA enabled:

similarweb

**Comment by Khrin** [comment]
@Yuki2718 is still there for you? i can't see it

**Comment by Yuki2718** [comment]
@Khrin Yeah, still shown:
similarweb

`similarweb.com##.app-banner`

**Pull request closed without merging**
