### PR TITLE
A: snrbox.com, snrcdn.net

### PR DESCRIPTION
**Pull request by trackerless**
Browser fingerprinting & Analytics

### CODE REVIEW

**Comment by Khrin** [comment]
Except that likely are in the wrong section, so this won't be approved anyway, where have you seen these?

**Comment by trackerless** [comment]
https://www.eobuwie.com.pl/

If this pull request is in wrong section please tell me where should I move it.
Thanks to this, my next commits will be sent correctly.

**Comment by mbalus** [comment]
snrcdn.net: Is a domain hosted on AWS CloudFront Service, this domain serve only static content without getting any information about users.

snrbox.com: This domain is using for native web push service. Users have given permission to send them things like web push notifications, information isn't sold or shared with third parties.

**Comment by Khrin** [comment]
Thank you @mbalus

"snrbox" is clearly a tracker, blocked now in EasyPrivacy. "snrcdn" is now listed along with other similar services.

**Pull request closed without merging**
