### PR TITLE
M: Update propellerads adservers

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by llacb47** [comment]
On which site were these adservers loaded?

**Comment by ryanbr** [comment]
We can make this non-flagged @smed79   in Easylist adservers

**Comment by smed79** [comment]
@llacb47 

> On which site were these adservers loaded?

example: here [topwwnews.com](https://git.io/Jf122)

@ryanbr 

Done [\_here\_](https://github.com/easylist/easylist/pull/5481) + remove redundancy

**Comment by smed79** [comment]
@ryanbr I have a request which is : move the `Non-flagged (Revolving ad servers)` section to the bottom of the file easylist_adservers.txt

**Pull request closed without merging**
