### PR TITLE
Update existing and add new rule for Target.com sponsored results

### PR DESCRIPTION
**Pull request by dividedby**
Add upward(1) to hide whitespace left from blocking sponsored products

Add new rule to block leftover "sponsored" text and remove whitespace

### CODE REVIEW

**Comment by liamengland1** [comment]
`upward` is not supported in ABP.

**Comment by dividedby** [comment]
Thanks, I use uBlock Origin so didn't know. Anyhow the new rule is still valid (and I removed the upward stuff)

**Comment by krystian3w** [comment]
Need rewrite to `-abp-has`: https://github.com/AdguardTeam/ExtendedCss/issues/102#issuecomment-619898058

So newbie version will be:

```adb
target.com#?#*:-abp-has(> div[data-test="@web/site-top-of-funnel/ProductCardWrapper"]:-abp-contains(sponsored))
target.com#?#*:-abp-has(> p[data-test="sponsored-text"]:-abp-contains(sponsored))
```

But it is better to replace `*` with something specific to the site of this discount store like div with rare stable attribute.

**Review by krystian3w — CHANGES_REQUESTED** [review]
https://github.com/easylist/easylist/pull/15585#issuecomment-1514262088

**Comment by dividedby** [comment]
I updated the commit with your suggested changes, also they worked for me in uBlock Origin.

**Comment by Khrin** [comment]
> Also ignore **Khrin** lament about mark my [comment](https://github.com/easylist/easylist/pull/15585#issuecomment-1514262088) as spam.

I don't know what you're babbling about, and honestly, it doesn't look like you know as well.

If you've to write incoherent sentences just to randomly attack someone else, please next time keep them for yourself. Nobody's interested. 

Thank you.

**Review by krystian3w — APPROVED** [review]

**Comment by ryanbr** [comment]
- https://www.target.com/p/the-seven-husbands-of-evelyn-hugo-by-taylor-jenkins-reid/-/A-89756459#lnk=sametab
- https://www.target.com/s?searchTerm=womens+sweaters&tref=typeahead%7Chistory%7C0%7Cwomens+sweaters%7Cwomens+sweaters%7C%7C%7Cservice%7C10%7C%7C%7C%7C&category=0%7CAll%7Cmatchallpartial%7Call+categories&searchTermRaw=
- https://www.target.com/p/lands-end-women-s-sweater-fleece-blazer-jacket-the-blazer/-/A-87678861?preselect=89886656#lnk=sametab

Not seeing any hits to any of these filter. Will close this PR

**Pull request closed without merging**
