### PR TITLE
A:`olx.bg`

### PR DESCRIPTION
**Pull request by eporubin**
Hi, there is a video advertisement on the [page](https://www.olx.bg/d/ad/top-podarak-digitalna-karikatura-po-snimka-izrabotka-po-vash-dizayn-CID262-ID8NmEs.html ), I know the domain it's Bulgarian, I have contacted the Bulgarian list author  but I did not get any reply over for more than a month. 
Thank you

### CODE REVIEW

**Comment by ryanbr** [comment]
I'm not seeing other sites using baxter-placeholder--ad--baxter-right-first

**Comment by ryanbr** [comment]
It looks generic, but if it applies to no other sites then is it really generic? Is there other sites using this element?

**Comment by eporubin** [comment]
Hi @ryanbr nope there is no over sites, I would of set it as specific, but the domain is bulgarian and us I have said have tried to contact the FLA of that list without any success

**Comment by Khrin** [comment]
This filter appears to have been added to the Bulgarian list. I'm closing here.

**Pull request closed without merging**
