### PR TITLE
A: IP-loggers owned by Grabify

### PR DESCRIPTION
**Pull request by TotoDude21903**

### CODE REVIEW

**Comment by Khrin** [comment]
@TotoDude21903 Where you've seen these elements?

**Comment by llacb47** [comment]
Visit `https://grabify.link/track/SH9X7V` and click `Change domain/Make a custom link`

**Comment by Khrin** [comment]
I need to see them on another website, beyond their own.

**Comment by ryanbr** [comment]
A few examples of these sites in action, too easy to add dead domains actually not in use really. Just to bloat the lists.

**Comment by spirillen** [comment]
Subscribing to the ping-list @spirillen

**Comment by ryanbr** [comment]
Closing.

**Pull request closed without merging**
