### PR TITLE
M: Removed coin-hive.com

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by elvey** [comment]
Perhaps you’ve confused coinhive.com and coin-hive.com

The former has already been moved to easylist annoyances?

**Comment by smed79** [comment]
@elvey I see no privacy issues, so it's can be removed from EasyPrivacy (moved to annoyances @ryanbr).
see also https://github.com/troyhunt/Coinhive/issues/12#issuecomment-1064687787

**Comment by elvey** [comment]
my concern been resolved by Troy’s comment on my issue that you link to. (It wasn’t a privacy issue.)

**Comment by ryanbr** [comment]
Can you patch out Annoyances ver  and /coinhive.min.js @smed79  also

**Comment by iam-py-test** [comment]
> and /coinhive.min.js

Couldn't some websites self-host CoinHive?

**Comment by ryanbr** [comment]
I would say its unlikely, at least to publicwww

**Comment by smed79** [comment]
> Can you patch out Annoyances ver and `/coinhive.min.js`

@ryanbr https://github.com/easylist/easylist/pull/11242

**Pull request merged**
