### PR TITLE
A: https://www.opensubtitles.org

### PR DESCRIPTION
**Pull request by peace2000**
"Watch online" ad and empty ad containers on search results.

Sample page: https://www.opensubtitles.org/en/search2/sublanguageid-all/moviename-nightmare+on+elm+street

kuva

### CODE REVIEW

**Comment by Yuki2718** [comment]
On my end background-color is different:

opensubtitles1

**Comment by peace2000** [comment]
@Yuki2718 Interesting, it has changed. Yeah that filter will do better, I'll change.

**Comment by peace2000** [comment]
Lol, this pull req has also now conflicts.. :D

**Comment by peace2000** [comment]
Fixed now.

**Pull request merged**
