### PR TITLE
africacheck.org

### PR DESCRIPTION
**Pull request by chirag127**
**Issue URL (Annoyance)**: https://africacheck.org/fact-checks/fbchecks/woman-gives-birth-puppies-no-humans-and-dogs-cant-reproduce

<details><summary>Screenshots:</summary>

image
image

</details><br/>

<details><summary>System configuration:</summary>

image
</details><br/>

### CODE REVIEW

**Comment by ryanbr** [comment]
Put in the right ! sections @chirag127

**Comment by chirag127** [comment]
Well I have put it in the right section according to my intellect . Can you please tell where I have to put it?

**Comment by ryanbr** [comment]
`! Newsletter/signup elements`  would be the correct section

**Comment by chirag127** [comment]
done.

**Pull request merged**
