### PR TITLE
M: Remove new Instagram cookie wall

### PR DESCRIPTION
**Pull request by Forage**

### CODE REVIEW

**Comment by peace2000** [comment]
This will break scrolling, unfortunately.

**Comment by Forage** [comment]
Darn. Sorry, I don't have an account so I did not test that. It appears to be working fine without logging in, but I realize that's not sufficient.
Let me know if you want me to delete the change.

**Review by krystian3w — CHANGES_REQUESTED** [review]

**Comment by krystian3w** [comment]
Better close, EasyList Cookies can break page if try block pop-up with `$csp=...`

**Comment by krystian3w** [comment]
@Forage disable filter from `uBO Annoyances` when you should locked scrolling.

**Pull request closed without merging**
