### PR TITLE
Remove bad filter for unsplash.com

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes https://github.com/easylist/easylist/issues/10645

cc @Edivania

### CODE REVIEW

**Comment by OliverJAsh** [comment]
@ryanbr Thanks! Is there any way we can prevent https://github.com/easylist/easylist/issues/10645 from happening again? This is the second time it's happened this year.

**Comment by edivaniadc** [comment]
> @ryanbr Thanks! Is there any way we can prevent #10645 from happening again? This is the second time it's happened this year.

@OliverJAsh and @ryanbr as removing `unsplash.com##.eziW_` ([previous case](https://github.com/easylist/easylist/commit/7badbbf1f78ef19775097017fbbd79a69e0e8514#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2)) the `Ad label` is back, could you please test whether one of below custom filters would block other styling links?
`unsplash.com##.LBDpZ.eziW_`
`unsplash.com##.RAaYj`

Just wanna make sure it won't be another problematic filter so it could be a way to prevent future issues in trying to hide this Ad label. Thanks in advance.

al2
al1

**Comment by OliverJAsh** [comment]
@edivaniadc Let me take a look. If there isn't already a class that targets that item specifically then I can add one for you. Does it have to be a class or can it be any selector?

**Comment by edivaniadc** [comment]
> @edivaniadc Let me take a look. If there isn't already a class that targets that item specifically then I can add one for you. Does it have to be a class or can it be any selector e.g. an attribute?

Thanks @OliverJAsh it could be either a class or a selector.
The most important is to be something more specific so it would not block any part of the content.

**Comment by OliverJAsh** [comment]
I've just deployed a change that adds an attribute called `data-ad` to the container element. This CSS would hide the entire ad, including the ad label and any padding beneath.

```css
[data-ad] {
    display: none;
}
```

**Comment by edivaniadc** [comment]
> data-ad
Thank you so much!
Just waiting for the changes to go live so I can test again.
unp

**Comment by OliverJAsh** [comment]
Try now, I just purged the cache.

**Comment by edivaniadc** [comment]
> Try now, I just purged the cache.
@OliverJAsh is still the same - Ad label: `.LBDpZ .eziW_ `  > `.RAaYj` 
https://unsplash.com/t/history
https://unsplash.com/t/current-events

**Comment by OliverJAsh** [comment]
Hmm, this is what I'm seeing. Try clearing your browser cache?

image

image

**Comment by edivaniadc** [comment]
@OliverJAsh just [added it](https://github.com/easylist/easylist/pull/11767). Thanks a lot.

**Pull request merged**
