### PR TITLE
Remove general block dimensions rules breaking Wagtail CMS

### LINKED ISSUE #7621: sfi.pl (or any Wagtail CMS based site) false positive
### List the website(s) you're having issues:

`https://sfi.pl/en/editions/16th-sfi-academic-it-festival/lectures/atomowki-vs-inzynierski-mojo-jojo-czyli-dlaczego-nie-warto-bac-sie-skomplikowanych-projektow-na-poczatku-kariery/`

### What happens?

Some images blocked by easylist (regular site content, blocked by easylist_general_block_dimensions)

This site is build using the Wagtail CMS (https://wagtail.io/). Wagtail uses `{scaling mode}-{dim X}x{dim Y}.format-{file type}` naming scheme for serving alternative image rendition (ie. serving different image sizes and types for mobile or hidpi). This clashes with some of easylist_general_block_dimensions rules. This is not specific to the reported website but to any website build on Wagtail CMS.

### List Subscriptions you're using:
```
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware",
    "easyprivacy",
    "fanboy-enhanced",
    "urlhaus-1",
    "spam404-0",
    "adguard-annoyance",
    "fanboy-thirdparty_social",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
 ```

### Your settings

- OS/version: Arch Linux/current (rolling release)
- Browser/version: Google Chrome/89.0.4389.114 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin/v1.34.0

### Other details:

Problematic filters that break Wagtail CMS image system:
```
-120x240.
-120x300.
-120x400.
-120x60.
-120x600.
-160x600.
-300x600.
-460x68.
-468x60.
-468x70.
-468x80.
-468x90.
-480x120.
-480x60.
-486x60.
-500x100.
-600x70.
-720x90.
-728x90.
-800x150.
-988x60.
```
Screenshot from 2021-04-09 15-55-09

Here is a manual on how Wagtail CMS handles images: https://docs.wagtail.io/en/stable/topics/images.html

### PR DESCRIPTION
**Pull request by apardyl**
Remove 21 rules in `easylist_general_block_dimensions.txt` that break the Wagtail CMS image rendition system.

Wagtail CMS (@wagtail https://wagtail.io/) uses the following uploaded image naming convention:
```
{original file name}.{hash}.{scaling mode}-{width}x{height}.format-{file type}.{ext}
```
This clashes with several filters in `easylist_general_block_dimensions.txt` causing false positives. Wagtail CMS has over 10k stars on GitHub, any site build with it can be affected (if the developer specifies any widthxheight pair that is listed in `easylist_general_block_dimensions.txt`). This pull request removes all problematic entries.

Example affected site (1p): `https://sfi.pl/en/editions/16th-sfi-academic-it-festival/lectures/atomowki-vs-inzynierski-mojo-jojo-czyli-dlaczego-nie-warto-bac-sie-skomplikowanych-projektow-na-poczatku-kariery/` (reported in #7621)

Fixes #7621

### CODE REVIEW

**Comment by ryanbr** [comment]
Way too much change imo

**Comment by apardyl** [comment]
> Way too much change imo

@ryanbr I agree this changelist is quite extensive, unfortunately this is the only way to stop EasyList from breaking Wagtail CMS based websites.

What can I say - I use adblocking on all of my devices (with the current state of most Polish sites its virtually impossible not to), but I do prefer to see one ad more from time to time than to have legitimate content removed because of a too broad filter. In this case it is even more problematic as **those rules can break all sites built using the Wagtail framework not just the one reported**.

**Comment by ryanbr** [comment]
Can the cms change, some/most of these rules probably predate Wagtail CMS. The 468/480/728 filters is my main concern.

**Comment by apardyl** [comment]
> Can the cms change, some/most of these rules probably predate Wagtail CMS. The 468/480/728 filters is my main concern.

@ryanbr I can open an issue on their repo, but I guess they might be reluctant to make the change on their side and it would be perfectly understandable. After all `my-site-logo2.max-500x100.format-jpeg.jpegquality-70.jpg` is perfectly valid file name and should not raise any concerns nor should it be detected as an ad.

By the way, I see most if not all of those rules are from over 7 year ago, are you sure that they are still useful?

**Pull request closed without merging**
