### PR TITLE
A: https://www.bilibili.com/blackboard/activity-DsYC2yN43x.html

### PR DESCRIPTION
**Pull request by shenzhiming88**
Collect user's privacy
image
image

### CODE REVIEW

**Comment by shenzhiming88** [comment]
@ryanbr

**Comment by ryanbr** [comment]
`/activity-report.` too generic

**Comment by shenzhiming88** [comment]
@ryanbr I have created a new one.

**Comment by lvzhenbo** [comment]
这个规则导致拿不到小心心，请求撤回PR
This rule results in not getting the little heart gift, please withdraw the PR
This rule is designed to track how long a user is on the air in order to obtain live gifts, not malicious tracking

**Pull request closed without merging**
