### PR TITLE
Remove clipconverter.cc from easylist_specific_block

### PR DESCRIPTION
**Pull request by josiasmontag**
Why? 

This very general "3rd party" filter breaks the Recaptcha used on this site:

https://www.clipconverter.cc/captcha

### CODE REVIEW

**Comment by Khrin** [comment]
Where's that captcha?

**Comment by josiasmontag** [comment]
This captcha page automatically comes up if a user did a certain amount of requests.

**Comment by josiasmontag** [comment]
@Khrin why did you close it?

**Comment by Khrin** [comment]
See https://github.com/easylist/easylist/commit/9164b8230641859aa2efb24fe0b3203d37a70efd

**Comment by josiasmontag** [comment]
Thanks!

**Pull request closed without merging**
