### PR TITLE
Add more Admiral hosts

### PR DESCRIPTION
**Pull request by migueldemoura**
Admiral homepage: https://www.getadmiral.com/.

These hosts reply to a `GET /` with something like:
```
This domain is used by digital publishers to control access to copyrighted
content in accordance with the Digital Millennium Copyright Act and
understand how visitors are accessing their copyrighted content.
```

If the response bodies are hashed with sha256, we get the following:
- `0c04a9bf2ca61527c5b4d1b07ad9f5f5e71984eb6b360eab7d67d8a4a13b7901`
- `2bb5ca9c173d7b5b72c48c6a899014cbc8fc47339ecdc7c40745ffd451a6d07d`
- `53d5d2477cf35502ac35e2c91a1786a7fec9fc408c2dc4dff0c0fecbaf88073d`
- `6b7f9abdc5cbdf259f0e452aa9aeeb3cd2f0edc884ff507479536599b88f841a`
- `a97df4c021b1233952629fbff95c5778c2dd7ecd14eedd71a76eaca7d9d75232`
- `b5344789bcc38f4e88c02440589e8359792c082654849236ba120f05fee24ffe`

The responses only have slight variations - the content is the same.

**Note to reviewers:** The description above should help with validation, but happy to provide the basic script I used to do so. Also, I used the `||host^` format instead of `||host^$third-party` since the existing list uses a mix of both and I don't see a reason to allow 1st party access to these. I don't keep the host from which these are being used, not sure if that's a requirement. Thanks!

### CODE REVIEW

**Comment by spirillen** [comment]
That is one big list.... thanks good.

is there by any change you would post this in a clear style by a file, syntax as

```
example.org
example.com
example.net
...
```

That would help me import it in my project here (https://mypdns.org/my-privacy-dns/matrix/-/issues/3023)

**Comment by ryanbr** [comment]
`borderbrush.com                                                                                      INACTIVE    STDLOOKUP`

Is that domain still used? @migueldemoura

**Comment by spirillen** [comment]
> borderbrush.com

I doubt...

```
whois borderbrush.com
No match for domain "BORDERBRUSH.COM".
>>> Last update of whois database: 2021-11-18T08:09:02Z <<<
```

Same same happens with all test enabled in @pyfunceble

image

**Comment by migueldemoura** [comment]
> That is one big list.... thanks good.
> 
> is there by any change you would post this in a clear style by a file, syntax as
> 
> ```
> example.org
> example.com
> example.net
> ...
> ```
> 
> That would help me import it in my project here (https://mypdns.org/my-privacy-dns/matrix/-/issues/3023)

`git diff -U0 HEAD~ | grep -E '^\+\|' | sed -r 's/\+\|\|(.*)\^/\1/'`

Output:
<details>
2znp09oa.com
4jnzhl0d0.com
5mcwl.pw
82o9v830.com
abackchain.com
abandonedaction.com
aboardamusement.com
aboardlevel.com
aboriginalboats.com
abruptroad.com
absentstream.com
absurdwater.com
acousticairplane.com
acousticsapparel.com
acquireattention.com
actuallysheep.com
actuallysnake.com
adorableanger.com
advertisementafterthought.com
agreeablestew.com
ajaralarm.com
ak0gsh40.com
alertafterthought.com
alikearm.com
alleyskin.com
ambiguousalarm.com
ambiguousquilt.com
ambitiousagreement.com
amusementmorning.com
annoyedfifth.com
apathetictheory.com
aquaticalarm.com
aquaticowl.com
ar1nvz5.com
archswimming.com
arcticamber.com
argyresthia.com
ariseboundary.com
arithmeticadjustment.com
aromamirror.com
attractiveafternoon.com
automaticflock.com
balancemailbox.com
balloonbit.com
balloontexture.com
barbarousnerve.com
batbuilding.com
battlebalance.com
battlehope.com
bawdybeast.com
bawdypets.com
beadbears.com
beamincrease.com
beastbeef.com
beneficialbeef.com
benthose.com
bewilderedbattle.com
bewilderedblade.com
bhcumsc.com
billowybead.com
bitterbear.com
blotburn.com
blushingbeast.com
blushingboundary.com
blushingwar.com
boilingumbrella.com
boneregret.com
boredborder.com
boringberry.com
boringcoat.com
bouncyproperty.com
brandybison.com
bravebone.com
bravecalculator.com
briefbears.com
briefstem.com
broadboundary.com
bruisebaseball.com
btez8.xyz
bucketbean.com
bulbbait.com
burgerbrush.com
burstblade.com
businessbells.com
bustlinganimal.com
calculatingcircle.com
calculatingtoothbrush.com
calculatorcamera.com
calmcough.com
cannonjudo.com
capablecows.com
capablecup.com
carriagecan.com
catalogdiscovery.com
catschickens.com
chairscrack.com
channelcamp.com
cheerfulrange.com
chemicalcoach.com
chemicalsnake.com
chesscherry.com
chesscolor.com
chewcoat.com
childlikeform.com
chinsnakes.com
chunkycactus.com
clearcabbage.com
cloisteredhydrant.com
cloudsdestruction.com
coachquartz.com
coatfood.com
colossalchance.com
combclover.com
comfortablecheese.com
commonalmanac.com
commonswing.com
completecabbage.com
concernedcondition.com
consistpotato.com
controlswim.com
coordinatedbedroom.com
copperchickens.com
copyrightaccesscontrols.com
correctchaos.com
crafthenry.com
crawlclocks.com
crayoncompetition.com
cumbersomecar.com
cumbersomecloud.com
cutecalculator.com
cutecushion.com
cuteturkey.com
dancemistake.com
dashingdirt.com
dashingdrop.com
dashingsweater.com
deadpantruck.com
deafeningdock.com
debonairway.com
decidedrum.com
decisiveducks.com
decoroustitle.com
decoycreation.com
defectivesun.com
defiantrice.com
delightfulhour.com
desertedbreath.com
desertedrat.com
detailedglue.com
detailedgovernment.com
detailedkitten.com
detectdinner.com
dispensablestranger.com
dk4ywix.com
docksalmon.com
dogsshoes.com
donkeyleaf.com
doorbrazil.com
doubtfulrainstorm.com
drabsize.com
draconiancurve.com
dragzebra.com
dramaticcondition.com
drawservant.com
dressexpansion.com
dripappliance.com
driverequest.com
drivingdirt.com
dustyrabbits.com
dustywave.com
earthquakescarf.com
earthycopy.com
economicpizzas.com
educatedeggnog.com
efficaciouscactus.com
elasticchange.com
elderlyinsect.com
elderlyscissors.com
elderlytown.com
elephantqueue.com
emptyescort.com
enchantedtop.com
encourageidea.com
encouragingwilderness.com
endurableshop.com
energeticexample.com
entertainingeyes.com
enthusiasticdad.com
enviousthread.com
erraticreaction.com
evaluateend.com
evanescentedge.com
exclusivebrass.com
expansioneggnog.com
experienceeggs.com
exuberanteyes.com
exuberantsoda.com
facilitategrandfather.com
fadedprofit.com
falsefeet.com
famousquarter.com
fantasticsmash.com
farethief.com
fascinatedfeather.com
faultyfowl.com
fearfowl.com
fearfulfish.com
fearlessfaucet.com
feebleshock.com
finalizeforce.com
flimsycircle.com
floodprincipal.com
floweryoperation.com
foamyfood.com
foregoingfowl.com
forgetfulflowers.com
fourarithmetic.com
fourfork.com
frailflock.com
franticcarpenter.com
fretfulfurniture.com
frightenedpotato.com
fujiladder.com
fumblingselection.com
functionalcrown.com
funnyairplane.com
furryhorses.com
futuristicfairies.com
futuristicfold.com
fuzzyflavor.com
fuzzyweather.com
gaudybeginner.com
giftedglue.com
giftedthumb.com
gleamingtrade.com
gloriouscracker.com
glossysense.com
gracefulsock.com
grandioseguide.com
grandmotherunit.com
greasegarden.com
greasemotion.com
greetzebra.com
guaranteelamp.com
guardedschool.com
guitargrandmother.com
h78xb.pw
haltinggold.com
handleteeth.com
handsomeindustry.com
handyfield.com
happenhistory.com
harborcub.com
hardtofindmilk.com
hatefulrequest.com
headyhook.com
heavyplayground.com
hfc195b.com
highfalutinbox.com
highfalutinroom.com
historicalrequest.com
honeybulb.com
honeygoldfish.com
honorablehall.com
hosenews.com
humdrumhat.com
hurtgrape.com
hurtteeth.com
hypnoticwound.com
hystericalhelp.com
i9w8p.pw
icebergindigo.com
illfatedsnail.com
illustriousoatmeal.com
imperfectinstrument.com
importedpolice.com
importlocate.com
impossiblemove.com
impulsehands.com
informengine.com
innocentwax.com
instrumentsponge.com
interestsmoke.com
internalsink.com
inventionpassenger.com
investigatepin.com
invitesugar.com
ivykiosk.com
joblessdrum.com
justicejudo.com
k54nw.pw
kitesquirrel.com
knottysticks.com
lackadaisicalkite.com
lagoonolivia.com
languagelake.com
laughablecopper.com
laughablelizards.com
laughdrum.com
leapfaucet.com
learnedmarket.com
lettucecopper.com
lettucelimit.com
lightcushion.com
literatelight.com
livelumber.com
longinglettuce.com
lp3tdqle.com
maddeningpowder.com
magnificentmeasure.com
magnificentmist.com
makeshiftmine.com
maniacalappliance.com
markedcrayon.com
markedpail.com
massivebasket.com
materialisticfan.com
materialisticmark.com
medusasailor.com
memopilot.com
memorycobweb.com
meremark.com
messagenovice.com
mightyspiders.com
militaryverse.com
mimosamajor.com
mindlessmark.com
minormeeting.com
miscreantmine.com
mixedreading.com
modifyeyes.com
moldyicicle.com
motionlessbag.com
mountainouspear.com
muddledaftermath.com
murkymeeting.com
mysteriousmonth.com
necessarywax.com
negotiatetime.com
niftyjelly.com
noiselessplough.com
nonchalantnerve.com
nondescriptcrowd.com
nondescriptsmile.com
nondescriptstocking.com
nostalgicknot.com
nostalgicneed.com
nothingmethod.com
nulldiscussion.com
nullnorth.com
nuttyorganization.com
obscenesidewalk.com
observantice.com
omniscientfeeling.com
omniscientspark.com
operationkettle.com
opinionsurprise.com
oppositeoperation.com
optimallimit.com
orangeoperation.com
ovalweek.com
overratedchalk.com
owlsr.us
paddleangle.com
paintplantation.com
paleleaf.com
pamelarandom.com
panoramicbutter.com
paradoxfactor.com
parchedangle.com
passengerpage.com
pastepot.com
pegasusplate.com
perpetualpail.com
persuadesock.com
persuadesupport.com
pigspie.com
pinpointpotato.com
piquantpigs.com
piquantstove.com
pizzasnut.com
plainplayground.com
plainrequest.com
plantpotato.com
pocketsonic.com
podiumpresto.com
pointlessrifle.com
poisedpig.com
possessivebucket.com
possibleboats.com
powderprofit.com
preciouseffect.com
preciousyoke.com
prefixpatriot.com
presetrabbits.com
presssensor.com
previousplayground.com
previouspotato.com
pricklyplastic.com
printerplasma.com
productivepear.com
purchasesuggestion.com
quacksquirrel.com
quarterbean.com
quicksandear.com
railwayrainstorm.com
rainydirt.com
rainyhand.com
rambunctiousvoyage.com
rapidkittens.com
readgoldfish.com
readingguilt.com
readingopera.com
readysnails.com
rebelsubway.com
receptivebranch.com
receptiveink.com
recommenddoor.com
reconditeprison.com
reconditerespect.com
referdriving.com
reflectivereward.com
resolutekey.com
respectrain.com
rhymezebra.com
rhythmmoney.com
righteouscrayon.com
ringsrecord.com
robustbelieve.com
rodeopolice.com
roughroll.com
ruddywash.com
ruthlessmilk.com
ruthlessrobin.com
sablesmile.com
sailsuit.com
satisfyingshow.com
satisfyingspark.com
savorystructure.com
saysidewalk.com
scarcesign.com
scarecrowslip.com
scaredcomfort.com
scaredsidewalk.com
scatteredheat.com
scatteredstream.com
scientificsneeze.com
scratchsofa.com
screechingfurniture.com
scrollservice.com
seashoresociety.com
secretivecub.com
secretspiders.com
seedscissors.com
selectionship.com
separateshow.com
shaggytank.com
shakesuggestion.com
shakytaste.com
shallowsmile.com
shinesavage.com
shopbreakfast.com
showsteel.com
showstranger.com
shutseashore.com
silentcredit.com
silentwrench.com
siliconslow.com
silkysquirrel.com
sillyscrew.com
simplisticstem.com
sincerebuffalo.com
sixscissors.com
sizesidewalk.com
slaysweater.com
sleepcartoon.com
slimopinion.com
slimyscarf.com
slipperysack.com
sloppyearthquake.com
smashshoe.com
smilingshake.com
smilingwaves.com
snailsengine.com
snakemineral.com
sneakystew.com
snoresmile.com
soaprange.com
sombersea.com
sombersquirrel.com
songssmoke.com
sophisticatedstory.com
sophisticatedstove.com
soresneeze.com
sorethunder.com
sortsail.com
sowlettuce.com
sparklesleet.com
sparklingnumber.com
specialsnake.com
specialstatement.com
spendpest.com
spidersboats.com
spirebaboon.com
spongesalt.com
spookyslope.com
spotstring.com
spottedsnow.com
springaftermath.com
spuriousstranger.com
spysubstance.com
squashfriction.com
stakingscrew.com
stakingslope.com
staleseat.com
standingnest.com
standingsack.com
standtrouble.com
statementsweater.com
statuesquebrush.com
steadfastsystem.com
stereoproxy.com
stickssheep.com
stickysheet.com
storescissors.com
storeslope.com
stoveseashore.com
straightnest.com
strangesink.com
stretchsister.com
stripedburst.com
structurerod.com
subsequentsand.com
subsequentstew.com
substantialcarpenter.com
succeedscene.com
suddensnake.com
suddensoda.com
sulkybutter.com
summerobject.com
supervisegoldfish.com
suspendseed.com
sweepsheep.com
swellstocking.com
swimslope.com
swordgoose.com
symbolizebeast.com
systemizecoat.com
talentedsteel.com
tarttendency.com
tastefulsongs.com
tastelesstrees.com
tdzvm.pw
tedioustooth.com
teenytinytongue.com
teenyvolcano.com
teethfan.com
tempttalk.com
tendersugar.com
terriblethumb.com
texturetrick.com
therapeuticcars.com
thicktrucks.com
thingsafterthought.com
thinkablefloor.com
thinkablerice.com
thinkabletrick.com
thirstyswing.com
threechurch.com
threetruck.com
throattrees.com
thunderingrose.com
timeterritory.com
timetwig.com
toothbrushnote.com
topichawaii.com
torpidtongue.com
torpidtoothpaste.com
toweringrun.com
translateoatmeal.com
trappush.com
trapteaching.com
treadbun.com
tremendousplastic.com
tremendoustime.com
tremendoustreatment.com
trickycelery.com
truckstomatoes.com
tumblebirds.com
tzwaw.pw
ultraoranges.com
uncoveredexpert.com
unevenstring.com
unifyaddition.com
unknowntray.com
unnaturalcaption.com
untidyquestion.com
unusedquestion.com
unusedstone.com
unusualtitle.com
unwrittenspot.com
usedexample.com
uttermosthobbies.com
vanfireworks.com
venusgloria.com
verifyvegetable.com
voicevegetable.com
vq1qi.pw
waggishpig.com
wakefulcook.com
warmquiver.com
warnwing.com
waryfog.com
wateryvan.com
wearywater.com
wellgroomedbat.com
wellmadefrog.com
whineattempt.com
whirlwealth.com
whiskyqueue.com
whisperingbadge.com
whisperingcrib.com
wigglygeese.com
wildernesscamera.com
wistfulflight.com
workableachiever.com
workoperation.com
worriednumber.com
wreckvolcano.com
writewealth.com
wrongpotato.com
wryfinger.com
xovq5nemr.com
youngmarble.com
zbwp6ghm.com
zealousfield.com
zippywind.com
</details>

**Comment by migueldemoura** [comment]
> `borderbrush.com INACTIVE STDLOOKUP`
> 
> Is that domain still used? @migueldemoura

Seems like it's inactive. I have it on my list but it isn't part of this commit since [it was already included](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L3237).
Also, I only validated the domains in the commit, not the existing ones.

**Comment by migueldemoura** [comment]
Add a few more to the PR, @spirillen:
<details>
    <summary>A few (163) more</summary>

    aboardfork.com
    aboardkettle.com
    actoramusement.com
    alpineactor.com
    ambiguousanger.com
    ambiguousincome.com
    amusinggirls.com
    apparatuslip.com
    arizonapuzzle.com
    aspiringattempt.com
    auntants.com
    averageamusement.com
    beautifulhobbies.com
    bedsberry.com
    begintrain.com
    boilingcredit.com
    bouncyfront.com
    brashbead.com
    breadbalance.com
    breakableinsurance.com
    brothersbucket.com
    brushdaughter.com
    bunchance.com
    bustlingbath.com
    calendarrate.com
    carefuldolls.com
    childlikecook.com
    circlelevel.com
    clamcelery.com
    clammytree.com
    clumsyrock.com
    colossalclouds.com
    combativedetail.com
    competitionbeetle.com
    conceptualizereading.com
    copytitle.com
    coverapparatus.com
    cumbersomecake.com
    currentcollar.com
    cutepopcorn.com
    debonairdust.com
    decisivebase.com
    defectivedress.com
    desirebucket.com
    deskdecision.com
    difficultfog.com
    divergentoffer.com
    dolldetail.com
    dramaticdirection.com
    drawermice.com
    earthquakeend.com
    enchantedjudge.com
    encouragingleaf.com
    energeticladybug.com
    fancyactivity.com
    fangfeeling.com
    fastenfather.com
    fifthborder.com
    frailfruit.com
    frantictrail.com
    fronttoad.com
    fumblingform.com
    godlygeese.com
    grayreceipt.com
    gripcorn.com
    grouchypush.com
    gullibleguitar.com
    habitualhumor.com
    hesitanttoothpaste.com
    highfalutinhoney.com
    hystericalfinger.com
    importedplay.com
    impossibleglue.com
    infamousstream.com
    instrumentinsect.com
    jadedjoke.com
    jailbulb.com
    knotkettle.com
    mailboxmeeting.com
    maliciousmusic.com
    materialexample.com
    measurecaption.com
    melodicminute.com
    messyoranges.com
    metroaverage.com
    miscreantmoon.com
    modularmental.com
    outstandingincome.com
    outstandingsnails.com
    pastoralcorn.com
    piquantprice.com
    planesorder.com
    plantrelation.com
    plotparent.com
    politegoldfish.com
    promopassage.com
    propertypotato.com
    proudprose.com
    punyplant.com
    puzzlingproperty.com
    quaintborder.com
    rainyrule.com
    rainystretch.com
    replaceroute.com
    representativeray.com
    richreceipt.com
    rightfulfall.com
    rigidrobin.com
    ritzyveil.com
    roomyreading.com
    ruddycast.com
    samestretch.com
    scarecrowslope.com
    scaredstory.com
    scarfthought.com
    scrawnystart.com
    shakegoldfish.com
    shakysurprise.com
    shallowblade.com
    simplesidewalk.com
    skillfuldrop.com
    sloppycalculator.com
    snakesshop.com
    somberattack.com
    somberstructure.com
    sootheside.com
    soretrain.com
    sortstructure.com
    spoonsilk.com
    spottedsmile.com
    springsister.com
    squeamishspot.com
    steadfastseat.com
    steadycopper.com
    stereotypedclub.com
    stereotypedsugar.com
    stockingsneeze.com
    stringsmile.com
    stupendousselection.com
    stupidsnake.com
    substantialstraw.com
    successfulscent.com
    suddenstructure.com
    superficialspring.com
    synonymousrule.com
    synthesizespoon.com
    terrificgoose.com
    terrifictooth.com
    testedtouch.com
    thickticket.com
    thirstylettuce.com
    toedrawer.com
    toothpasterabbits.com
    tutorthing.com
    uncoveredcircle.com
    virgoplato.com
    warmafterthought.com
    wearbasin.com
    wigglyindustry.com
    wrapstretch.com
    wtaccesscontrol.com
    youthfulnoise.com
    zlp6s.pw
</details>

**Comment by spirillen** [comment]
Super thanks, was just about to commit :smiley:

**Comment by spirillen** [comment]
@ryanbr if you are testing these with pyfunceble before merging you might have a peek into the list before merging.as I just found these in my active list. See bug report here: https://github.com/funilrys/PyFunceble/issues/275

```
functionalclam.com (UnResponSive)

..SNIP..

ga87z2o.com (Temporarily Down for Maintenance.)
```

**Pull request merged**
