### PR TITLE
A: nettimoto.com (tracking pixel)

### PR DESCRIPTION
**Pull request by peace2000**
Sample pages:
https://www.nettimoto.com/
https://www.nettikone.com/

There are more as well.

### CODE REVIEW

**Comment by spirillen** [comment]
Didn't you forget this one, or it that one in the polish filter...

`nettimoto.com##.huge-banner`

<details><summary>Screenshot</summary>

image

</details>

I tested with this rule: `||api.nettix.fi^` I didn't see anything in the log calling this domain

image


It's not even in my dns log...

```
grepq('nettix.fi')
Time    Client                                          Server       ID    Name                      Type  Lat.   TC RD AA Rcode
-497.6  192.168.1.100:60533                                          39350 auth.nettix.fi.           A               RD    Question
-497.6  192.168.1.100:60533                                          64445 auth.nettix.fi.           AAAA            RD    Question
-497.6  192.168.1.100:60533                             127.0.0.1:5302 64445 auth.nettix.fi.           AAAA  33.7      RD    No Error. 2 answers
-497.6  192.168.1.100:60533                             127.0.0.1:5302 39350 auth.nettix.fi.           A     36.2      RD    No Error. 2 answers
-497.0  192.168.1.100:44723                                          57039 script.nettix.fi.         A               RD    Question
-497.0  192.168.1.100:44723                                          22003 script.nettix.fi.         AAAA            RD    Question
-497.0  192.168.1.100:44723                             127.0.0.1:5302 57039 script.nettix.fi.         A     7.1       RD    No Error. 2 answers
-497.0  192.168.1.100:44723                             127.0.0.1:5302 22003 script.nettix.fi.         AAAA  7.7       RD    No Error. 2 answers
-496.9  192.168.1.100:59000                                          11293 cdn.nettix.fi.            A               RD    Question
-496.9  192.168.1.100:59000                                          38162 cdn.nettix.fi.            AAAA            RD    Question
-496.9  192.168.1.100:59000                             127.0.0.1:5302 11293 cdn.nettix.fi.            A     6.4       RD    No Error. 2 answers
-496.9  192.168.1.100:59000                             127.0.0.1:5302 38162 cdn.nettix.fi.            AAAA  6.6       RD    No Error. 2 answers
-496.9  192.168.1.100:52469                                          40205 script.nettix.fi.         A               RD    Question
-496.9  192.168.1.100:52469                                          56433 script.nettix.fi.         AAAA            RD    Question
-496.8  192.168.1.100:44204                                          39999 cdn.nettix.fi.            A               RD    Question
-496.8  192.168.1.100:44204                                          816   cdn.nettix.fi.            AAAA            RD    Question
-131.0  192.168.1.100:46998                                          20663 auth.nettix.fi.           A               RD    Question
-130.1  192.168.1.100:33357                                          40161 script.nettix.fi.         A               RD    Question
-130.1  192.168.1.100:33357                                          19941 script.nettix.fi.         AAAA            RD    Question
-129.9  192.168.1.100:50598                                          10793 cdn.nettix.fi.            A               RD    Question
-129.9  192.168.1.100:50598                                          34596 cdn.nettix.fi.            AAAA            RD    Question
```

**Comment by peace2000** [comment]
`nettimoto.com##.huge-banner` is already in the Finnish Easylist: https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/0af7e0c77d1115c22df6c00d8bbfd2333901050e/Finland_adb.txt#L717

Well that's strange, maybe then it's a regional thing, I don't know. But I see it:

kuva

**Comment by peace2000** [comment]
Can you open this link?

https://api.nettix.fi/counter/bike?type=showcase-view&id=2722150&idShowcase=6803&time=1632608991948

**Comment by spirillen** [comment]
I can :heavy_check_mark: 

and it does. :heavy_check_mark: 

But the Q is. Would it brake anything by blocking the api.domain? which was what I would have tested in the first place

**Pull request merged**
