### PR TITLE
Speeds up build time to less than 30 seconds

### PR DESCRIPTION
**Pull request by spirillen**
This commit will lower build time to less than 30 seconds with an avarage of ~28 sec

It also ads a test of submission with FOP.py, and makes sure it runs this script on all submission that's not the `gh-pages`

### CODE REVIEW

**Comment by spirillen** [comment]
To See test results from this PR please visit https://travis-ci.com/spirillen/improve-easylist/builds

Any TRAVIS >= [Build #79](https://travis-ci.com/spirillen/improve-easylist/builds/130582532) are working from the plan.

Please dubbel check especially [.travis-ci.yml](https://github.com/easylist/easylist/blob/f00a2e2c0da213757995ea3bea91450840532968/.travis.yml) for any typos and errors before merging

**Comment by ryanbr** [comment]
> build time seem to be below 30 sec already: https://travis-ci.org/easylist/easylist/builds

**Comment by spirillen** [comment]
Nice, But last time I was trying to see that build stat, I couldn't find it :eyes:

**Comment by ryanbr** [comment]
I'll close this, since its working as intending, don't want make change for the sake of change (especially when our build times are low already)

**Pull request closed without merging**
