### PR TITLE
block gelbooru header ad

### PR DESCRIPTION
**Pull request by Znunu**
This banner is blocked atm, but leaves an empty space behind. This should take care of that. I hope edited the correct file. I just looked for existing gelbooru entries
image

### CODE REVIEW

**Review by spirillen — COMMENTED** [review]
A couple of alternative for more generic rules could be

```css
gelbooru.com##div[style^="width: 728px; height: 90px"]
gelbooru.com##a[href^="https://buymyshit.moneygrubbingwhore.com/"]
```

I believe it would be better if you changed the rule to

```css
gelbooru.com##.headerAd
```

**Comment by spirillen** [comment]
Wee he

new rule...

gelbooru.com##video
```

**Comment by Znunu** [comment]
Sorry for getting back so late
##
> I believe it would be better if you changed the rule to

Good idea. It's done

##
`gelbooru.com##video`
`gelbooru.com##div[style^="width: 728px; height: 90px"]`

Not sure I understand what these are for? From my own testing, they match the same `.headerAd` again.

##
`gelbooru.com##a[href^="https://buymyshit.moneygrubbingwhore.com/"]`

I tested this rule and it only seems to block the store button on the main menu...?
image

**Comment by spirillen** [comment]
As I was on one of the sites the top banner appeared within this css name, hence this one should be added along side your rule

```css
gelbooru.com##.video
```

this is a alternative rule, which is blocking based on dimensions of the banner and should be covering both cases with one rule.
```css
gelbooru.com##div[style^="width: 728px; height: 90px"]
```

Try them both before you make your final contribution

**Comment by Znunu** [comment]
Alright! I've added `gelbooru.com##.video` too. I figure it's more stable than matching size & height

**Review by spirillen — APPROVED** [review]

**Comment by Znunu** [comment]
What's gonna happen now?

**Comment by spirillen** [comment]
sit back and wait :unamused: some ain't handle before in six month :unamused: it surely depends on?? how fast they are handled.

**Comment by Znunu** [comment]
Wait, you're saying the maintainers don't care? I guess that explains the nearly 700 open PRs. Frankly I thought you had permission to merge. Did you just happen to stumble over my PR?
##
Is there any other list (that adblockers use) where I can suggest this change instead? I don't want to wait.

**Comment by spirillen** [comment]
> Wait, you're saying the maintainers don't care?

Nope not at all, I just say I have never found the pattern in what is merged quickly (same day), and what is left hanging (the 700)

> Frankly I thought you had permission to merge

Happily not :smirk: I just have the old school idea we should help each other, this was my 2 cents to you

> Did you just happen to stumble over my PR?

Nope I'm am actively monitoring this repository, as there comes a lot of "good" stuff I can use in my RPZ driven project. and yours happen to fit in the NSFW filter: https://mypdns.org/my-privacy-dns/porn-records/-/issues/2123 That's why it got more attention. as I visited the side anyway, I of curse tested your commit

**Comment by Yuki2718** [comment]
I don't think this PR is likely to be merged. The problem is they put ads (should be blocked) and self-promo (should NOT be blocked by EL) under the same class: https://github.com/uBlockOrigin/uAssets/commit/64e96974137f3e66b884fa5ab5567d951cf6adf5

**Comment by Znunu** [comment]
@Yuki2718 I read the thread you linked. I see you pretty much had the same issues as me. As far as I can see, the new rules just pushed by ryanbr (above me) got rid of all the self promotion too.
##
I've tested with ublock origin and it works perfectly. The placeholder is gone. However adblock plus, seems to ignore the `.headerAd` rule in the filterlist. Which is weird, because `.headerAd` as a _custom rule_ works. I'm aware that this is a _adblock plus problem_, but I still find it worth mentioning.

**Comment by Khrin** [comment]
> I've tested with ublock origin and it works perfectly. The placeholder is gone. However adblock plus, seems to ignore the `.headerAd` rule in the filterlist. Which is weird, because `.headerAd` as a _custom rule_ works. I'm aware that this is a _adblock plus problem_, but I still find it worth mentioning.

Have you tried to update the filter lists, first?

**Comment by Znunu** [comment]
Yeah, I updated. it's right here. Can you test too maybe? Maybe I got something else configured poorly.
image
While searching for this rule, I stumbled over this one too, which already existed
image
That covers the gelbooru case too right? Am I an idiot and have been trying to add something that already exists?

**Comment by gelbooru** [comment]
Hello, I noticed you blocked our store once again, and our self promoted website, Realbooru. These are all sites that are directly related to each other, as they are owned and operated by us. I was told many times that self promotion, specifically our store, is allowed, and yet here we are once more, in this situation. Can you clarify why these are blocked?

**Comment by Znunu** [comment]
I can't speak on behalf on the maintainers or guidelines, but I can clarify my intentions with this PR. The purpose of my PR was to get rid of placeholders and 'realbooru'. I wasn't bothered by anything related to the store.

You're putting both self-promo and 3p in the same div (.headerAd). To get rid of the placeholder, I made a rule to filter the element altogether. See this discussion where Yuki had the same issue: https://github.com/uBlockOrigin/uAssets/commit/64e96974137f3e66b884fa5ab5567d951cf6adf5

The animated realbooru ad is just really bad and gross, whether it's owned by you or not. (Link to the PR that filtered this:  
 https://github.com/easylist/easylist/pull/10540#issuecomment-1066158523)

The store (moneygrubbingwhore) banners and links were filtered here https://github.com/easylist/easylist/commit/f99019dc212714b7d88d1c6d3d25e90d76b837f7. This even got rid of the store button. I'm guessing that was ryanbr being hasty.

**Comment by gelbooru** [comment]
"Bad and gross", that's pretty vague description, if not subjective, of content that is on an adult website. Can you clarify this?

**Pull request closed without merging**
