### PR TITLE
A: ylasatakunta.fi (cookie specific hide uBO)

### PR DESCRIPTION
**Pull request by peace2000**
https://www.ylasatakunta.fi/

Specific hiding rule for uBO, due to blinking issue with generic filter.

### CODE REVIEW

**Comment by spirillen** [comment]
Evening CookieMonster aka @peace2000 wouldn't it be possible to make this one global

```css
##.ag_cookie_banner
```

**Comment by peace2000** [comment]
Evening. It's already a global filter but it blinks occasionally for this site in uBO. Sometimes you'll have to add a specific filter for uBO to avoid blinking issues with elements. That's because uBO doesn't inject all many thousands of generic filters unconditionally on each site like ABP does. It's an important performance optimization. Though it has a drawback: elements occasionally blink in some websites if they don't have a specific filter and only have a generic.

**Comment by spirillen** [comment]
Hey thanks for that info... that might explain why my rules sometimes flicker for mypdns...

**Comment by peace2000** [comment]
Very likely. Official source for that info: https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

**Comment by peace2000** [comment]
Also it's possible to make uBO to inject a cosmetic filter unconditionally by adding an asterisk before it: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic

Though that should nout be overused :D

**Comment by spirillen** [comment]
Super thanks for the info @peace2000 very useful tricks

**Comment by peace2000** [comment]
Great that it was useful, I struggled with the same issue for a long time before I was told about this... :D

**Pull request merged**
