### PR TITLE
A: [NSFW] https://xnxbang.com/

### PR DESCRIPTION
**Pull request by felippesantos46**
Block adserver responsible for banners at https//xnxbang.com/

Screenshots:
Screenshot 2021-12-21 at 10 06 35
Screenshot 2021-12-21 at 10 11 46

### CODE REVIEW

**Comment by Yuki2718** [comment]
`||xnxbang.com/sw.js` too.

**Comment by felippesantos46** [comment]
Hey @Yuki2718 Thank you for that. I believe it's being blocked by this one `/^https?:\/\/.*\/.*sw[0-9._].*/$script,xmlhttprequest` at least it is on my side !

**Comment by Yuki2718** [comment]
> I believe it's being blocked by this one `/^https?:\/\/.*\/.*sw[0-9._].*/$script,xmlhttprequest` at least it is on my side !

Right, my bad.

**Review by spirillen — APPROVED** [review]

**Comment by spirillen** [comment]
> > I believe it's being blocked by this one `/^https?:\/\/.*\/.*sw[0-9._].*/$script,xmlhttprequest` at least it is on my side !
> 
> Right, my bad.

I love people who it tall enough to admit a mistake.

**Pull request closed without merging**
