### PR TITLE
A:`electricianforum.co.uk`

### PR DESCRIPTION
**Pull request by eporubin**
3-rd party advertising banners on top of the page:
image

### CODE REVIEW

**Comment by ryanbr** [comment]
Why not electricianforum.co.uk##.gb-sponsored ? All 4 images are technically advertising

**Comment by Daxy7** [comment]
`Advertise with us` is like 1p advertising but as an image instead of the footer. (but it's off-center)

**Comment by eporubin** [comment]
I was thinking about blocking all with electricianforum.co.uk##.gb-sponsored , but had the same concern as @Daxy7 it's not redirecting to 3-rd party even if you click on it actually.

**Comment by ryanbr** [comment]
I think its messey doing it this way tbh.

**Comment by eporubin** [comment]
@ryanbr I can change it to `electricianforum.co.uk##.gb-sponsored`.  i agree with you just want to avoid future complains from them about blocking their self advertising.

**Comment by ryanbr** [comment]
Lets change it, if they complain, we can re-address it.

**Comment by eporubin** [comment]
@ryanbr sure, changed as suggested 🙌

**Pull request merged**
