### PR TITLE
M: update #7734 (addresses https://github.com/easylist/easylist/commi…

### PR DESCRIPTION
**Pull request by Yuki2718**
…t/9efef25582cd1d00584fa9a63e8e8d81e2162404#commitcomment-54950823)
Just a few examples from 900+ sites according to publicwww (all NSFW):
```
http://arohadesign.com/chapter/eq924853/chapter_26
https://movieclassic.net/kr-awmgx/244810/
https://vivevegano.org/album/250214/%E6%88%91%E6%B1%BA%E5%AE%9A%E4%B8%8D%E7%95%B6%E7%B6%A0%E8%8C%B6%E5%A9%8A%E4%BA%86-%E8%8C%89%E7%BE%8E%E3%83%9D%E3%83%86%E3%83%88-%E9%9A%A0%E3%82%8C%E3%83%93%E3%83%83%E3%83%81-%E5%8D%92%E6%A5%AD%E3%81%97%E3%81%BE%E3%81%99
```
`/images/b/` is called from `/apis-2.js` - in short it's just an update of
```
/pub/pop.js| ->/pub/js_min.js
/invoke-2.js -> /apis-2.js
```

### CODE REVIEW

**Comment by ryanbr** [comment]
These are bad generic's
From: `https://movieclassic.net/apis-2.js`
`document.write('<a href="/krwh/5-" target="_blank" rel="nofollow"></a>');`  

Seems to minor.

**Comment by Yuki2718** [comment]
In publicwww I only saw these crap sites but yes, `||systemleadb.com^$popup` helps. How about `##[href$="/5-"][target="_blank"][rel="nofollow"]` for ads? Also if popup is allowed I saw `cm-trk5.com` which should be added.

**Comment by ryanbr** [comment]
`##a[href$="/5-"][target="_blank"][rel="nofollow"]` not a fan of this either

**Comment by Yuki2718** [comment]
@ryanbr So you leave the ads? But well, apparently most of them are Chinese NSFW sites.

@cjx82630 I wonder if you can address them.

**Comment by Yuki2718** [comment]
@Alex-302 How about fixing in AG Chinese. If
```
/apis-2.js
/pub/js_min.js
```
is risky, we can go with regex.

**Comment by spirillen** [comment]
@rebase

**Comment by ryanbr** [comment]
hmm not a good rebase. @Yuki2718  update the PR or new PR.

**Comment by Yuki2718** [comment]
I thought it's declined, which set of rules you prefer? The current ones in this PR?

**Pull request closed without merging**
