### PR TITLE
P: (nsfw) https://www.cmoa.jp/title/71936/ (related: https://github.com/Adgu…

### PR DESCRIPTION
**Pull request by Yuki2718**
…ardTeam/AdguardFilters/issues/105180)

<details>
<summary>Screenshot</summary>

cmoa1

cmoa2

</details>

Even with the exception it requires reloading twice.

### CODE REVIEW

**Comment by spirillen** [comment]
Can't reproduce the need for unblocking any google here

image

```yml
uBlock Origin: 1.40.2
Firefox: 91
filterset (summary): 
  network: 153870
  cosmetic: 159044
  scriptlet: 33741
  html: 1301
listset (total-discarded, last updated): 
  added: 
    https://my-external-stuff.github.io/ublockorigin-rules/blockrules.txt: 288118-21581, 2h.27m
    NOR-0: 2607-36, 2h.29m
  default: 
    ublock-filters: 30631-30590, 2d.23h.15m
    ublock-badware: 3635-3634, 2d.23h.15m
    ublock-privacy: 181-180, 2d.23h.15m
    ublock-abuse: 81-75, 2d.23h.14m
    ublock-unbreak: 1723-210, 2d.23h.14m
    easylist: 62342-5727, 2d.23h.14m
    easyprivacy: 26558-13186, 2d.23h.14m
    urlhaus-1: 7612-0, 17h.45m
    plowe-0: 3679-3677, 2d.23h.14m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5100 ms

```

**Comment by Yuki2718** [comment]
> Can't reproduce the need for unblocking any google here
> 

Scroll down more.

**Comment by spirillen** [comment]
went to the bottom...

**Comment by ryanbr** [comment]
`@@||google-analytics.com/analytics.js$script,domain=cmoa.jp` Should fix this @Yuki2718  the other filters wern't needed

**Pull request closed without merging**
