### PR TITLE
More Tor coverage + allow feedback to be manually sent to DuckDuckGo

### LINKED ISSUE #15173: https://improving.duckduckgo.com/t/fb*
### List the website(s) you're having issues:

```
https://improving.duckduckgo.com/t/fb*
```

### What happens?

When I explicitly choose to share feedback with DuckDuckGo about their site, easylist appears to be blocking the feedback from being sent. Specifically, all of the `https://improving.duckduckgo.com/t/fb*` requests are blocked, sending my feedback to `/dev/null` instead of to DuckDuckGo.

This can be reproduced by going to `https://duckduckgo.com/?q=easylist` and clicking on the "Share Feedback" button on the bottom right of the page. Select any of the feedback options, positive or negative, and they will all be blocked.

### List Subscriptions you're using:

The defaults with uBlockOrigin. I believe it is `EasyPrivacy` which is resulting in this feedback being blocked. Specifically, [this line](https://github.com/easylist/easylist/blob/23241e4f392542a862784d727dc7ff8629f88e40/easyprivacy/easyprivacy_specific.txt#L318).

### Your settings

- OS/version: macOS Ventura 13.2.1
- Browser/version: Firefox 110.0.1 
- Adblock Extension/version: uBlock Origin 1.47.2

### Other details:

I don't think my explicit attempts to share feedback with a site should result in it being blocked. It looks like `https://improving.duckduckgo.com/t/` is [used to send other pixels by DuckDuckGo](https://help.duckduckgo.com/duckduckgo-help-pages/privacy/atb/), which I'm fine being blocked. I'd like for any of the `https://improving.duckduckgo.com/t/fb*` requests to not be blocked since it appears those are used to submit explicit feedback.

For reference, this sort of feedback is not blocked on any other search engine (Google, Bing, Brave, etc.).

### PR DESCRIPTION
**Pull request by jbmagination**
Closes #15173. This pull request allows feedback to manually be sent to DuckDuckGo with the `@@||duckduckgo.com/t/fb*$image,~third-party` filter.

This pull request *also* adds more coverage for .onion domains. Specifically:
* Filters for v2 .onion addresses have been removed as they can no longer be accessed
* Adds filters for multiple Reddit .onion addresses
* Adds filters for multiple Twitter .onion addresses
* Adds more filters for the Facebook .onion address
* Adds more filters for the Brave Search .onion address
* Adds filters for the ProPublica .onion address
* Adds filters for the DuckDuckGo .onion address
* Adds filters for the New York Times .onion address

I'm sure I've messed up a lot - and missed a lot more. This is my first contribution to an adblock list *ever*, so please forgive me if I've not done things quite right.

### CODE REVIEW

**Comment by ryanbr** [comment]
[Didn't twitter stop supporting tor? ](https://www.engadget.com/twitter-tor-service-no-longer-working-063541843.html)

Does put in jeopardy the legitness of this PR.

**Comment by ryanbr** [comment]
```
@@||duckduckgo.com/t/fb$image,~third-party
@@||duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/t/fb$image,~third-party
```

Also. why? lets just give DDG trackers a free pass.

**Comment by ryanbr** [comment]
Closing.

**Comment by jbmagination** [comment]
> [Didn't twitter stop supporting tor? ](https://www.engadget.com/twitter-tor-service-no-longer-working-063541843.html)
> 
> Does put in jeopardy the legitness of this PR.

I can see why. Twitter's certificates expired, but the service itself is still accessible with some hacky workarounds. For good measure, I added them - but I'm willing to remove everything to do with Twitter's Tor service if you would prefer that.

> ```
> @@||duckduckgo.com/t/fb$image,~third-party
> @@||duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/t/fb$image,~third-party
> ```
> 
> Also. why? lets just give DDG trackers a free pass.

What's being unblocked here are feedback endpoints. With the current EasyList rules, all feedback sent through the "Send Feedback" button doesn't work, so this rule allows those requests to go through. No other `duckduckgo.com/t/` endpoints are unblocked (which yes, are trackers!) As best as I can tell, no other tracking endpoint is on `duckduckgo.com/t/fb*`, and no feedback is sent unless you specifically send it yourself with the feedback dialog. 

I can see why one could argue that they could abuse this rule and change it, but you're already placing trust in DuckDuckGo that they're not storing your search history and abusing it for nefarious purposes (which they absolutely could be!). As you're already trusting them with your queries, I see no reason why this is different.

@ryanbr

**Pull request closed without merging**
