### PR TITLE
screening.mhanational.org

### PR DESCRIPTION
**Pull request by chirag127**
**Issue URL (Annoyance)**: https://screening.mhanational.org/screening-tools/depression/#gf_1

<details><summary>Screenshots:</summary>

image

</details><br/>

<details><summary>System configuration:</summary>

image
</details><br/>

### CODE REVIEW

**Comment by ryanbr** [comment]
Make it generic `###footer-sign-up` @chirag127

**Comment by chirag127** [comment]
done @ryanbr

**Comment by ryanbr** [comment]
in the Newsletter section?

**Comment by chirag127** [comment]
hopefully now.

**Pull request merged**
