### PR TITLE
CRM XenForo 2.x

### LINKED ISSUE #14971: CRM: XenForo 2.x
### List the website(s) you're having issues:

Any websites that use XenForo 2.x

For example: https://xenforo.com/community/

### What happens?

Various tools on the site accessible to logged in users don't work due to an overzealous rule in https://github.com/easylist/easylist/commit/90e52f62f839:

```
##.js-bottomFixTarget.u-bottomFixer
```

In particular, any bulk thread selection tools won't work since they appear as descendants of `.js-bottomFixTarget.u-bottomFixer`.

As far as I know, it isn't possible to repro the false positives without logging in.

### List Subscriptions you're using:

* easylist_cookie_general_hide.txt

### Your settings

N/A

### Other details:

PR incoming.

### PR DESCRIPTION
**Pull request by Zenexer**
Fixes #14971

### CODE REVIEW

**Comment by Zenexer** [comment]
Removed erroneous merge commit from the PR.

**Comment by ryanbr** [comment]
`##.js-notices.notice--cookieAdvanced` -> `##.notice--cookieAdvanced`

**Comment by Zenexer** [comment]
Thanks, @ryanbr.  Updated and rebased.

**Comment by krystian3w** [comment]
possible mix into one:

`##[class*="notice--cookie"]`

**Pull request merged**
