### PR TITLE
P: (tumblr.com) https://forums.lanik.us/viewtopic.php?f=64&t=40185

### PR DESCRIPTION
**Pull request by SMed79**

### CODE REVIEW

**Comment by SMed79** [comment]
@ryanbr fyi.

**Comment by nightpool** [comment]
an exception for http(s)://new-xkit.github.io would also solve the problem for us. We've had hundreds of users in our chat rooms and ask box over the past two days due to this change, and likely 10x more who haven't reached out to us or haven't reached the 24 hour window where the extension checks for updates yet.

**Comment by nightpool** [comment]
any update on this? we're on day two of triaging support requests.

**Comment by Khrin** [comment]
Our filter has been modified. 
https://github.com/easylist/easylist/commit/536b5ece1fa1cced0ea2144c9a22a5b124062e2f

**Pull request closed without merging**
