### PR TITLE
P: https://ad-maven.com/advertisers

### PR DESCRIPTION
**Pull request by edivaniadc**
1 - EasyList rule blocks image icons
`/advertisers/*$domain=~ads.pinterest.com|~datalift360.com|~home.tapjoy.com|~panel.rightflow.com|~propelmedia.com|~publisuites.com|~qubeslate.com`

images

2 - EasyList rules hide widget under **Multiple Ad Formats**
```
##.widget-ads
##.ad-push
##.ad-btn
##.ad-banner
##.ad-full
##.ad-img
```
widget

### CODE REVIEW

**Comment by ryanbr** [comment]
Might be easier to use generic hide here

**Comment by edivaniadc** [comment]
> 5378b64

Thanks @ryanbr, here are the changes: https://github.com/easylist/easylist/pull/12032/commits/5378b643628079175bcd3d20832107f47bcc091a

**Comment by Noamicoco** [comment]
can anyone please elaborate why are you blocking elements on ad-maven.com ? the website is the brand's website, it contains zero ads.

**Comment by edivaniadc** [comment]
> 6b0dbaa

The blocking was not intentional. This [PR](https://github.com/easylist/easylist/pull/12032) was to fix that.
See https://github.com/easylist/easylist/pull/12032/commits/5378b643628079175bcd3d20832107f47bcc091a
https://github.com/easylist/easylist/commit/6b0dbaade84125c4d5cb3160dacb55299eefe5e5

**Pull request merged**
