### PR TITLE
Update easyprivacy_specific.txt

### PR DESCRIPTION
**Pull request by Sonic5435325**
To hopefully address https://github.com/easylist/easylist/issues/16383.

### CODE REVIEW

**Comment by ryanbr** [comment]
Will this interfere with the consents?

**Comment by Sonic5435325** [comment]
I doubt it will.

**Comment by Sonic5435325** [comment]
I feel like it won't, but I'll test them to see if there's anything that breaks the cookie consent message with the filters on.

**Comment by Sonic5435325** [comment]
So far, everything seems to work fine with the suggested filters. No breakage on the cookie consent message or it's preferences setting as far as I'm aware of.

**Pull request merged**
