### PR TITLE
P: https://animepahe.com/

### PR DESCRIPTION
**Pull request by smed79**
https://forums.lanik.us/viewtopic.php?f=64&t=41432

### CODE REVIEW

**Comment by smed79** [comment]
@ryanbr fyi.

**Comment by peace2000** [comment]
This seems to be whitelisted.

`@@||jsdelivr.net^$script,domain=animepahe.com|bilasport.me|kwik.cx`

**Comment by peace2000** [comment]
@ryanbr this is ok.

**Comment by peace2000** [comment]
This is ok @Khrin

**Comment by peace2000** [comment]
Whitelisted at least now, by this rule:

`@@||jsdelivr.net^$script,domain=animepahe.com|bilasport.me|kwik.cx`

**Pull request closed without merging**
