### PR TITLE
P: (nsfw) https://www1.myhdjav.net/ssni-915 (fixes https://github.com…

### PR DESCRIPTION
**Pull request by Yuki2718**
…/AdguardTeam/AdguardFilters/issues/71509)
https://github.com/AdguardTeam/AdguardFilters/issues/71509#issuecomment-753865560

<details>
<summary>Screenshot</summary>

bitporno

</details>

### CODE REVIEW

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/72530#issuecomment-762203418

**Comment by spirillen** [comment]
I'll suggest you add `##.player-sidebar` as well. (Empty place holder)

**Comment by Yuki2718** [comment]
@spirillen 
<details>
<summary>Screenshot</summary>

myhdjav

</details>

I don't see actual difference by adding `##.player-sidebar`.

**Comment by spirillen** [comment]
Ok, It just didn't come to me :smile: 

>  don't see actual difference by adding ##.player-sidebar.

Nope, but it's there, and if you add it,  we are a step ahead, if the underlying ads code changes. It's more about that :+1:

**Comment by Yuki2718** [comment]
> 
> Nope, but it's there, and if you add it, we are a step ahead, if the underlying ads code changes.

Will do only if requested by EL maintainer.

**Pull request closed without merging**
