### PR TITLE
A:mkvcage.ws

### PR DESCRIPTION
**Pull request by mediumkreation**
Found in URL: https://www.mkvcage.ws
Issue: Hidden link redirects.

mkvcage ws_18-12-17 14 07 08

### CODE REVIEW

**Comment by mediumkreation** [comment]
@monzta, updated with requested changes

**Comment by peace2000** [comment]
Domain is dead.

@monzta

**Comment by spirillen** [comment]
Which domain is dead?

`d0p21g2fep.com` redirects to `||google.*$important`

`i62e2b4mfy.com`

> This URL is used by Adsterra Advertising Network for ad serving. If you have any questions or would like to monetize your inventory, run an ad campaign, click HERE

**Comment by peace2000** [comment]
Hi! Mkvcage is dead.

**Comment by spirillen** [comment]
Hijacked yes, dead no.

```
whois mkvcage.ws
Domain Name: MKVCAGE.WS
Domain ID: 67ED5633962A4E7BE050010AAC01EAB1
WHOIS Server: whois.namecheap.com
Registrar URL: https://www.namecheap.com/domains/whois.aspx
Updated Date: 2019-04-16T15:56:51Z
Creation Date: 2018-05-17T00:29:49Z
Registrar Registration Expiration Date: 2020-05-17T00:29:49Z
Registrar: Namecheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Domain Status: clientTransferProhibited
Name Server: dns1.registrar-servers.com
Name Server: dns2.registrar-servers.com

```
dig mkvcage.ws

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mkvcage.ws.                    IN      A

;; ANSWER SECTION:
mkvcage.ws.             21600   IN      A       192.64.119.50
```

![image](https://user-images.githubusercontent.com/44526987/72128798-5431e380-3374-11ea-895f-f110a681eaf5.png)

**Comment by peace2000** [comment]
All right.

**Comment by peace2000** [comment]
This request is not relevant anymore.

**Pull request closed without merging**
