### PR TITLE
M: filter adjusting, performance reasons

### PR DESCRIPTION
**Pull request by peace2000**
See my comment here: https://github.com/easylist/easylist/pull/13055#issuecomment-1227212174

### CODE REVIEW

**Comment by Yuki2718** [comment]
In the similar vein it is better to rewrite filters like `#?#div:-abp-has` if possible.

**Comment by peace2000** [comment]
@Yuki2718  what do you mean?

**Comment by Yuki2718** [comment]
> what do you mean?
`#?#div:-abp-has` => procedural filter js code evaluates all the div on the page, if the numbers are big it has the same issue as you pointed out.

**Comment by peace2000** [comment]
Well, a quick way to literally get rid off `#?#div:-abp-has` entries could be achieved by doing this: https://github.com/easylist/easylist/issues/12861, lol :D

Yeah, got what you mean.

Are there many such entries in EL?

One easy (maybe) way could be to make the filter a bit more specific.

Like:

`div:-abp-has(.adcrap)`

->

`.article-container > div:-abp-has(.adcrap)`

Then it would only check divs under article-container and ignore all the other divs in the page.

But, that would probably require a separate issue :P

Also, doesn't native `:has` perform better anyway? It's about to land soon.

**Comment by peace2000** [comment]
Well, made one PR: https://github.com/easylist/easylist/pull/13087

This is not small project to check all of those.. :D

**Comment by Yuki2718** [comment]
> Are there many such entries in EL?

No, only 3 including the one you opened PR.

> Also, doesn't native :has perform better anyway? It's about to land soon.

Only on Chrome? This is a bit of my concern as probably I have to rewrite some :upward with :has, once uBO starts to take this as native selector.

**Comment by peace2000** [comment]
Firefox soon as well: https://caniuse.com/css-has :) they have experimental support now.

**Pull request merged**
