### PR TITLE
A:horriblesubs.info

### PR DESCRIPTION
**Pull request by mediumkreation**
**Found in URL**: horriblesubs.info
horriblesubs info_18-10-15 23 29 12
horriblesubs info_18-10-15 23 29 00
 

**Found in URL**: https://horriblesubs.info/shows/puzzle-and-dragons-cross/

horriblesubs info_18-10-15 23 33 20

**Suggested filters** : 
```
horriblesubs.info##.latest-sponsor
horriblesubs.info##.homepage-sponsor
horriblesubs.info##.rls-sponsor
```

### CODE REVIEW

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/724c77886b8088314c8fddea033607a2ab25d06b

**Comment by zeroZshadow** [comment]
Do note that this PR has not only removed the advertisements. But also broke the website's ability to display their releases list.

**Comment by tostercx** [comment]
@zeroZshadow no it's probably this https://github.com/easylist/easylist/commit/724c77886b8088314c8fddea033607a2ab25d06b

**Comment by zeroZshadow** [comment]
@tostercx That is the commit linked above my comment

**Comment by tostercx** [comment]
Oh, nvm then, carry on.

**Comment by Palizangetsu** [comment]
[724c778](https://github.com/easylist/easylist/commit/724c77886b8088314c8fddea033607a2ab25d06b)
Please remove this does nothing but break the website ads were being blocked properly prior to this commit.

**Comment by sledgehammer999** [comment]
I created online PR #4286 that fixes this.

**Pull request closed without merging**
