### PR TITLE
A: (nsfw) https://tuberel.com/ (fixes https://github.com/AdguardTeam/…

### PR DESCRIPTION
**Pull request by Yuki2718**
…AdguardFilters/issues/70112)
https://github.com/AdguardTeam/AdguardFilters/issues/70112
Also fixes https://github.com/AdguardTeam/AdguardFilters/issues/69956

### CODE REVIEW

**Comment by Yuki2718** [comment]
Domains are generated in mostly random manner, added regex to cover them.

**Comment by ryanbr** [comment]
Remove the regex filter @Yuki2718

**Comment by ryanbr** [comment]
Reference
```
https://9a98494f4d4b694d4f6713.online/9a98494f4d4b694d4f6713.js
https://9a9d494f4d4b694d4f6763.online/9a9d494f4d4b694d4f6763.js
https://9798494f4d4b694d4f6710.online/9798494f4d4b694d4f6710.js
https://999g494f4d4b694d4f6792.online/999g494f4d4b694d4f6792.js
```

**Comment by Yuki2718** [comment]
Okay, should `||9997494f4d4b694d4f6702.online^$third-party` also be removed?

**Pull request closed without merging**
