### PR TITLE
A: [NSFW] https://javtiful.com/

### PR DESCRIPTION
**Pull request by felippesantos46**
Filters to block adservers and hide placeholders at [javtiful](https://javtiful.com/)

Proposed filters:
Redirect popup after play a video - `||b7om8bdayac6at.com^$popup`
Redirect popups after click in any content - `||bncloudfl.com^$third-party` & `||nomorepecans.com^$third-party
Hide placeholders - `javtiful.com###showerm` & `javtiful.com##[class*="jtmoney-"]`

Screenshots:
Screenshot 2021-11-18 at 12 40 59
Screenshot 2021-11-18 at 13 29 43
Screenshot 2021-11-18 at 13 29 37
Screenshot 2021-11-18 at 13 29 21
`

### CODE REVIEW

**Comment by spirillen** [comment]
Looking good.

I would how ever which someone could make rules for these two empty placeholders

image
image

**Comment by felippesantos46** [comment]
@spirillen Hey oh ! Thank you for that, i've also noticed another adserver responsible for popup ads. both were added to this PR.

Screenshot 2021-11-19 at 09 30 20

Ps: I'm quite new to everything so if you would like my help with something (including your lists) you can ping me somehow 😅, ready to help !

**Comment by spirillen** [comment]
> Ps: I'm quite new to everything so if you would like my help with something (including your lists) you can ping me somehow sweat_smile, ready to help !

You are most welcome.

As this is easylists forum you should just git me up on https://mypdns.org/mypdns/support/-/issues and lets have a talk about what have your biggest interest.

**Comment by spirillen** [comment]
You are missing one in the adserver list...

`8b4b041006.com`

**Pull request closed without merging**
