### PR TITLE
A: https://sportzonline.to/channels/pt/sporttv4.php

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by spirillen** [comment]
Hi @smed79 

Why did you add `click.alibaba.com`? tacking, spam, adware?

**Comment by smed79** [comment]
@spirillen I would not recommend you to block that subdomain in the hosts file.

`click.alibaba.com` is a legitimate sharing hyperlink of alibaba.com items.

example `https://click.alibaba.com/rd/63prl94p` 
(same as aliexpress sharing link `http://s.click.aliexpress.com/e/bEqnuJQ`)

The issue is that some webmasters and ad network abuse and embed the sharing link in an iframe.

example: https://imgur.com/2eOzI2t.png

**Comment by spirillen** [comment]
But the conflict here is, `s.click.aliexpress.com`is used for redirecting and tracking by obfuscating real destinations and that is not something I 'out of the box' is up for....

Just because something is big, means we have to stick to it and what the want's.

**Comment by smed79** [comment]
When you do a search on google for "`adblock plus`", google modify the search result links to track your click when you click them. 

If you right-click the link in order to copy it you get something like:

`https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjHsdyRjqLnAhUDBGMBHXOpDQwQFjAAegQIAxAB&url=https%3A%2F%2Fadblockplus.org%2F&usg=AOvVaw1B9XYwyNRT6aBTYkkZSxHP`

Which will redirect you to: https://adblockplus.org/

The question is : 

Are you going to block `www.google.com` ?

**Comment by smed79** [comment]
@spirillen GitHub track our clicks

example 

`https://github.com/easylist/easylist/pull/4792?email_source=notifications&email_token=5CNFSM4KLNZL2HS4DFVF3ADN5REKTAAOJJ4ZSGYXGW2YY3PNVWUHIWK3TUL543VM3EQLPP3Q7XEWW2ZLOORPVBW63LNMVXHJS32RD7WSZGOEJ5Z#issuecomment-578525725`

(https://github.com/jparise/chrome-utm-stripper/issues/16#issuecomment-522278430)

**Comment by spirillen** [comment]
> Are you going to block `www.google.com` ?

Absolutly: https://gitlab.com/rpz-zones/google.tld

> GitHub track our clicks 

Why I prefer Gitlab.com, but there issue system is [very broken](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/74) at the moment

**Comment by ryanbr** [comment]
To avoid breaking their clickthroughs. 

`||click.alibaba.com^$subocument,third-party`

**Comment by spirillen** [comment]
A late an OT reply, but for those who likes to block google likes with dnsdist from powerdns.com

Then the regex i use for that is
```lua
addAction(RegexRule("(^|[.])(207|admob|cookiebot|cxense|doubleclick|firebaseapp|google|google(-)?analytics|googleapis|googletagmanager)[.][a-z]{2,5}(([.][a-z]{0,2})?)$"),RCodeAction(DNSRCode.NXDOMAIN))
```

Alternatively to spoof the IP to one you decide yourself

```lua
addAction(RegexRule("(^|[.])(207|admob|cookiebot|cxense|doubleclick|firebaseapp|google|google(-)?analytics|googleapis|googletagmanager)[.][a-z]{2,5}(([.][a-z]{0,2})?)$"), SpoofAction('127.0.0.1','6:0:0:g:1:3:'))
```

**Pull request merged**
