### PR TITLE
A: (nsfw) ​https://filemoon.sx/e/3diyyubuudxs (on https://7mmtv.sx/ja…

### PR DESCRIPTION
**Pull request by Yuki2718**
…/censored_content/99749/GIHHD-075.html, fixes https://github.com/AdguardTeam/AdguardFilters/issues/131568#issuecomment-1271485037)
https://github.com/AdguardTeam/AdguardFilters/issues/131568#issuecomment-1271485037

### CODE REVIEW

**Comment by ghajini** [comment]
there's `.to` tld also

**Comment by Yuki2718** [comment]
> there's `.to` tld also(`filemoon.to`)

Are the same rules needed? Example link?

**Comment by ghajini** [comment]
> > there's `.to` tld also(`filemoon.to`)
> 
> Are the same rules needed? Example link?

`https://filemoon.to/d/djlzuoeu1cv3/`

rules needed

**Comment by Yuki2718** [comment]
Here `.js?dfp=` is bait.

**Comment by ghajini** [comment]
yes

**Pull request merged**
