### PR TITLE
A: https://www.01net.com/actualites/appels-indesirables-les-services-…

### PR DESCRIPTION
**Pull request by 0o5rlubm**
…clients-ne-pourront-plus-utiliser-les-numeros-en-06-et-07.html

ad block on mobile view

### CODE REVIEW

**Comment by ryanbr** [comment]
Should be taken care of in ListFR?

**Comment by Khrin** [comment]
@smed79

**Comment by 0o5rlubm** [comment]
> Should be taken care of in ListFR?

you mean https://github.com/AdguardTeam/AdguardFilters/blob/master/FrenchFilter/sections/specific.txt ?

**Comment by smed79** [comment]
> you mean 

@0o5rlubm https://github.com/easylist/listefr

> ad block on mobile view

added ...

**Comment by 0o5rlubm** [comment]
> > you mean
> 
> @0o5rlubm https://github.com/easylist/listefr
> 
> > ad block on mobile view
> 
> added [easylist/listefr@6c50492](https://github.com/easylist/listefr/commit/6c50492865aba33e255dc9e59184341cd7333526)

wow, world is wonderful! thanks!

**Pull request closed without merging**
