### PR TITLE
A: (nsfw) `hdzog.tube`

### PR DESCRIPTION
**Pull request by eporubin**
Hi, please add the filter causing redirection of the content in another tab and opening ads in the previous. Thank you

### CODE REVIEW

**Comment by eporubin** [comment]
The issue still persists.

**Comment by eporubin** [comment]
Moreover all the websites which were in the first block of filters: `/evgeno7.*.js^$script,domain=hdzog.tube /klesd7.*.js^$script,domain=vjav.com
/lemon7.*.js^$script,domain=vxxx.com
/lolop7.*.js^$script,domain=txxx.com
/quas7.*.js^$script,domain=tubepornclassic.com
/rass7.*.js^$script,domain= desiporn.tube|hdzog.com|tubepornclassic.com` now all have the same issue pop with content in another tab and open ads ads in previous tab.

**Comment by ryanbr** [comment]
Many of these were not current, and removed

**Comment by eporubin** [comment]
Hi I have further looked into this and cross checked the domain with the filters and updated the with the right filters, hope this helps: 
image

**Pull request merged**
