### PR TITLE
Adding some cookie banners

### PR DESCRIPTION
**Pull request by iam-py-test**
This PR attempts to fix a few issues related to Cookie Banners:
- fixes https://github.com/easylist/easylist/issues/8823
- fixes https://github.com/easylist/easylist/issues/8822
- fixes https://github.com/easylist/easylist/issues/8805

CC @DandelionSprout

### CODE REVIEW

**Comment by peace2000** [comment]
Hi, this fix can only be used in uBO and AG as ABP still doesn't support style injection: https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/210

These filters should be moved to uBO list:

kuva

**Comment by iam-py-test** [comment]
> 
> 
> Hi, this fix can only be used in uBO and AG as ABP still doesn't support style injection: https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/210
> 
> Filters in this PR should be moved to uBO list:
> 
> kuva

Ok, thank you!

**Comment by peace2000** [comment]
Only filters concerning `savoriurbane.com`, I was blind and didn't notice other domains.

**Comment by peace2000** [comment]
Sorry to bother again, but shouldn't these words be `visible` ?

kuva

**Comment by iam-py-test** [comment]
> 
> 
> Sorry to bother again, but shouldn't these words be `visible` ?
> 
> kuva

I don't think their needed, considering they had a typo in them
Sorry for the error. Good catch :)

**Comment by iam-py-test** [comment]
@peace2000 any progress?

**Comment by peace2000** [comment]
What you mean?

**Comment by peace2000** [comment]
I don't have a write access here, if that's what you mean.

**Comment by iam-py-test** [comment]
> I don't have a write access here, if that's what you mean.

Ok, sorry

**Comment by ryanbr** [comment]
Incorrect format

**Comment by ryanbr** [comment]
Resolved all 3 sites.

**Comment by iam-py-test** [comment]
> Incorrect format

What is the correct format?

**Comment by ryanbr** [comment]
`#$#:root` isn't specific to ubO here.  Following the format/exisiting filters in `easylist_cookie_specific_hide.txt`.

**Comment by iam-py-test** [comment]
> `#$#:root` isn't specific to ubO here. Following the format/exisiting filters in `easylist_cookie_specific_hide.txt`.

Good point. I moved those based on https://github.com/easylist/easylist/pull/9699#issuecomment-967615529, but maybe I misunderstood that?

**Comment by ryanbr** [comment]
The PR was a mess, too much fixes in a single PR. Anyways, its fixed.

**Comment by peace2000** [comment]
@iam-py-test 

`#$#:root { overflow: visible !important; padding-right: 0 !important;}` is Adguard format, which uBO does support which is why I thought it would be accepted.

But anyway, uBO form of that rule would be:

`##:root:style(overflow: visible !important; padding-right: 0 !important;)`

**Comment by iam-py-test** [comment]
Ah, that makes sense. Thanks

**Pull request closed without merging**
