### PR TITLE
A: iltalehti.fi (tracking server)

### PR DESCRIPTION
**Pull request by peace2000**
`https://www.iltalehti.fi/`

`https://publicwww.com/websites/%22dnt-userreport.com%22/`

### CODE REVIEW

**Comment by peace2000** [comment]
@spirillen You are probably interested as well ;)

**Comment by spirillen** [comment]
> @spirillen You are probably interested as well ;)

Sure is :+100: 

How come you (@peace2000) never have suggested these two [filter rules](https://mypdns.org/my-privacy-dns/matrix/-/issues/2953#easylist-code)

```css
iltalehti.fi##.almacmp-content
iltalehti.fi##.almacmp-background-overlay
```

**Comment by spirillen** [comment]
Alternative, seems to work as well

```css
iltalehti.fi##[class="almacmp-"]
```

**Comment by peace2000** [comment]
Easylist Cookie already hides banners at least for me.

```
iltalehti.fi##.almacmp-content
iltalehti.fi##.almacmp-background-overlay
iltalehti.fi##[class="almacmp-"]
```

Show no hits for me for some reason.

**Comment by spirillen** [comment]
Hmm it came full blown in my head... 

Found it. it's added in the FIN language file :smiley:  https://github.com/finnish-easylist-addition/finnish-easylist-addition

Så det er jo bra

**Pull request merged**
