### PR TITLE
A: Update nsfw sites

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by smed79** [comment]
The regex filter (line 402) will block the revolving scrips.

https://github.com/easylist/easylist/pull/13992/commits/6a35152d8ed2f6acbe59a95148f29efbbd40b219#diff-e3c2f978cb8197f34839191c66f5853b1865a7043a91e48048b8195c1c226956R401

If you want to keep it separated, replace
`|thegay|` by `|`.

**Comment by smed79** [comment]
or to test the regex filter for only `vjav.com` as an example, add

```adblock
/^https?:\/\/(vjav)\.(com)\/(?!assets|build|static|upd)(.*)\.js/$script
```

to test for `vjav.com`, `vxxx.com` & `hdzog.com`
```adblock
/^https?:\/\/(vjav|vxxx|hdzog)\.(com)\/(?!assets|build|static|upd)(.*)\.js/$script
```

**Comment by ryanbr** [comment]
Some of these regex would be removed due to MV3 at some stage.

**Comment by smed79** [comment]
Remain the strict blocking as the ultimate solution.

Closing ...

**Pull request closed without merging**
