### PR TITLE
A: https://www.lemonde.fr trackers

### PR DESCRIPTION
**Pull request by 0o5rlubm**
thanks :heart:

### CODE REVIEW

**Comment by 0o5rlubm** [comment]
not sure if you prefer to specify the origin domain as well, ie. ` ||www.lemonde.fr/lmd$domain=www.lemonde.fr `

**Comment by ryanbr** [comment]
```
||lemonde.fr/lmd?
||lemonde.fr/bucket/*/tagistan.
```

Would be cleaner.

**Comment by ryanbr** [comment]
I'm not seeing ||capping.lemonde.fr & ||capping.sirius.press


@smed79  thoughts

**Comment by 0o5rlubm** [comment]
> @ryanbr  I'm not seeing ||capping.lemonde.fr & ||capping.sirius.press

According to the marketing doc, it's to count account usage. I confirm it only appears when i'm logged on the website.

> Capping: Detect account sharing that exceeds policy limits. Stop fraudulent subscriptions and increase your revenue stream.
https://www.sirius.press/capping

**Comment by ryanbr** [comment]
We can't break paywalls in EL

**Review by 0o5rlubm — COMMENTED** [review]
M: remove https://lemonde.fr antisharing for now

**Comment by ryanbr** [comment]
Is `||lemonde.fr/ajax/bizdev` a tracker?, I'm not seeing it

**Comment by 0o5rlubm** [comment]
> Is `||lemonde.fr/ajax/bizdev` a tracker?, I'm not seeing it

it's not a tracker, it's an annoying, unusfull, static, section shown at the bottom of each article. See "Services" section at the bottom of https://www.lemonde.fr/politique/article/2022/08/22/darmanin-veut-un-encadrement-militaire-pour-les-mineurs-delinquants-dans-les-territoires-d-outre-mer_6138702_823448.html.

I was thinking annoyance stuff (fanboy-addon/fanboy_annoyance_international.txt) was for this, perhaps i'm wrong?

**Comment by ryanbr** [comment]
Limit the patch to trackers.

**Comment by 0o5rlubm** [comment]
done

**Pull request closed without merging**
